INSERT INTO mots (mot, mot_normalized, categorie_id) VALUES
    ('abiu', 'abiu', 6),
    ('abricot', 'abricot', 6),
    ('abricot des antilles', 'abricotdesantilles', 6),
    ('abricot pays', 'abricotpays', 6),
    ('acca sellowiana', 'accasellowiana', 6),
    ('actinidia arguta', 'actinidiaarguta', 6),
    ('actinidia chinensis', 'actinidiachinensis', 6),
    ('acérola', 'acerola', 6),
    ('ail', 'ail', 6),
    ('ail cultivé', 'ailcultive', 6),
    ('ail d’orient', 'aild’orient', 6),
    ('ail rocambole', 'ailrocambole', 6),
    ('airelle', 'airelle', 6),
    ('airelle du mont ida', 'airelledumontida', 6),
    ('airelle rouge', 'airellerouge', 6),
    ('akebia quinata', 'akebiaquinata', 6),
    ('aki', 'aki', 6),
    ('alkékenge', 'alkekenge', 6),
    ('amande', 'amande', 6),
    ('amande tropicale', 'amandetropicale', 6),
    ('amande-pays', 'amande-pays', 6),
    ('amarante', 'amarante', 6),
    ('amarante de chine', 'amarantedechine', 6),
    ('amelanchier canadensis', 'amelanchiercanadensis', 6),
    ('amélanche', 'amelanche', 6),
    ('amélanches du canada', 'amelanchesducanada', 6),
    ('anacardium occidentale', 'anacardiumoccidentale', 6),
    ('ananas', 'ananas', 6),
    ('ananas comosus', 'ananascomosus', 6),
    ('annona glabra', 'annonaglabra', 6),
    ('annona muricata', 'annonamuricata', 6),
    ('annona squamosa', 'annonasquamosa', 6),
    ('anone', 'anone', 6),
    ('anone des marais', 'anonedesmarais', 6),
    ('ansérine bon-henri', 'anserinebon-henri', 6),
    ('arachide', 'arachide', 6),
    ('arbouse', 'arbouse', 6),
    ('arbutus unedo', 'arbutusunedo', 6),
    ('argouse', 'argouse', 6),
    ('aronia', 'aronia', 6),
    ('aronia melanocarpa', 'aroniamelanocarpa', 6),
    ('arracacha', 'arracacha', 6),
    ('arroche', 'arroche', 6),
    ('artichaut', 'artichaut', 6),
    ('artichaut chinois', 'artichautchinois', 6),
    ('artocarpus altilis', 'artocarpusaltilis', 6),
    ('artocarpus odoratissimus', 'artocarpusodoratissimus', 6),
    ('asafoetida', 'asafoetida', 6),
    ('ase fétide', 'asefetide', 6),
    ('asimina triloba', 'asiminatriloba', 6),
    ('asimine', 'asimine', 6),
    ('asperge', 'asperge', 6),
    ('asperge blanche', 'aspergeblanche', 6),
    ('asperge verte', 'aspergeverte', 6),
    ('aspérule', 'asperule', 6),
    ('atoka', 'atoka', 6),
    ('atte', 'atte', 6),
    ('attier', 'attier', 6),
    ('aubergine', 'aubergine', 6),
    ('averrhoa carambola', 'averrhoacarambola', 6),
    ('avocat', 'avocat', 6),
    ('azucki', 'azucki', 6),
    ('azuki', 'azuki', 6),
    ('açaï', 'acai', 6),
    ('añu', 'anu', 6),
    ('baie de sérendipité', 'baiedeserendipite', 6),
    ('bambou', 'bambou', 6),
    ('banane', 'banane', 6),
    ('banane plantain', 'bananeplantain', 6),
    ('banane ‘basrai’', 'banane‘basrai’', 6),
    ('banane ‘dwarf cavendish’', 'banane‘dwarfcavendish’', 6),
    ('banane ‘petite naine’', 'banane‘petitenaine’', 6),
    ('baobab', 'baobab', 6),
    ('barbadine', 'barbadine', 6),
    ('bardane', 'bardane', 6),
    ('baselle', 'baselle', 6),
    ('basilic', 'basilic', 6),
    ('bergamote', 'bergamote', 6),
    ('bette', 'bette', 6),
    ('bette ou blette', 'betteoublette', 6),
    ('bette à carde', 'betteacarde', 6),
    ('betterave', 'betterave', 6),
    ('betterave rouge', 'betteraverouge', 6),
    ('bibace', 'bibace', 6),
    ('bigarade', 'bigarade', 6),
    ('bigarade ou orange amère', 'bigaradeouorangeamere', 6),
    ('bigaradier', 'bigaradier', 6),
    ('blette', 'blette', 6),
    ('bleuet', 'bleuet', 6),
    ('boesenbergia rotunda', 'boesenbergiarotunda', 6),
    ('brahea edulis', 'braheaedulis', 6),
    ('brocoli', 'brocoli', 6),
    ('brocoli chinois', 'brocolichinois', 6),
    ('brugnon', 'brugnon', 6),
    ('brèdes', 'bredes', 6),
    ('bunias d’orient', 'buniasd’orient', 6),
    ('butia capitata', 'butiacapitata', 6),
    ('butternut', 'butternut', 6),
    ('bénincasa', 'benincasa', 6),
    ('cacahuète', 'cacahuete', 6),
    ('cacao', 'cacao', 6),
    ('cacao (fèves)', 'cacao(feves)', 6),
    ('cachiman', 'cachiman', 6),
    ('calamondin', 'calamondin', 6),
    ('calebasse', 'calebasse', 6),
    ('camu-camu', 'camu-camu', 6),
    ('canistel', 'canistel', 6),
    ('canna comestible', 'cannacomestible', 6),
    ('canneberge', 'canneberge', 6),
    ('cantaloup', 'cantaloup', 6),
    ('capucine tubéreuse', 'capucinetubereuse', 6),
    ('carambole', 'carambole', 6),
    ('cardon', 'cardon', 6),
    ('carica papaya', 'caricapapaya', 6),
    ('carica pubescens', 'caricapubescens', 6),
    ('carissa macrocarpa', 'carissamacrocarpa', 6),
    ('carotte', 'carotte', 6),
    ('casimiroa edulis', 'casimiroaedulis', 6),
    ('cassis', 'cassis', 6),
    ('catalonia', 'catalonia', 6),
    ('caïmite', 'caimite', 6),
    ('cempedak', 'cempedak', 6),
    ('cerfeuil', 'cerfeuil', 6),
    ('cerfeuil tubéreux', 'cerfeuiltubereux', 6),
    ('cerise', 'cerise', 6),
    ('cerise de cayenne', 'cerisedecayenne', 6),
    ('cerise de la barbade', 'cerisedelabarbade', 6),
    ('cerise des antilles', 'cerisedesantilles', 6),
    ('cerise des barbades', 'cerisedesbarbades', 6),
    ('cerise douce', 'cerisedouce', 6),
    ('champignon', 'champignon', 6),
    ('chayote', 'chayote', 6),
    ('cherimole', 'cherimole', 6),
    ('chervis', 'chervis', 6),
    ('chia', 'chia', 6),
    ('chichourle', 'chichourle', 6),
    ('chicon', 'chicon', 6),
    ('chicorée', 'chicoree', 6),
    ('chicouté', 'chicoute', 6),
    ('chinotto', 'chinotto', 6),
    ('chou blanc', 'choublanc', 6),
    ('chou brocoli', 'choubrocoli', 6),
    ('chou cabus', 'choucabus', 6),
    ('chou chine', 'chouchine', 6),
    ('chou chinois', 'chouchinois', 6),
    ('chou de bruxelles', 'choudebruxelles', 6),
    ('chou de pékin', 'choudepekin', 6),
    ('chou frisé', 'choufrise', 6),
    ('chou palmier', 'choupalmier', 6),
    ('chou palmiste', 'choupalmiste', 6),
    ('chou pointue', 'choupointue', 6),
    ('chou romanesco', 'chouromanesco', 6),
    ('chou rouge', 'chourouge', 6),
    ('chou-chinois', 'chou-chinois', 6),
    ('chou-fleur', 'chou-fleur', 6),
    ('chou-navet', 'chou-navet', 6),
    ('chou-rave', 'chou-rave', 6),
    ('chou-romanesco', 'chou-romanesco', 6),
    ('choux', 'choux', 6),
    ('christophine', 'christophine', 6),
    ('châtaigne', 'chataigne', 6),
    ('châtaigne de terre', 'chataignedeterre', 6),
    ('châtaigne d’eau chinoise', 'chataigned’eauchinoise', 6),
    ('châtaigne-pays', 'chataigne-pays', 6),
    ('chénopode bon-henri', 'chenopodebon-henri', 6),
    ('chérimole', 'cherimole', 6),
    ('ciboule', 'ciboule', 6),
    ('ciboule de chine', 'cibouledechine', 6),
    ('ciboulette', 'ciboulette', 6),
    ('cima di rapa', 'cimadirapa', 6),
    ('cima di rapa citrouille', 'cimadirapacitrouille', 6),
    ('citron', 'citron', 6),
    ('citron vert', 'citronvert', 6),
    ('citrouille', 'citrouille', 6),
    ('citrus aurantium', 'citrusaurantium', 6),
    ('citrus aurantium ‘bouquetier de fleur’', 'citrusaurantium‘bouquetierdefleur’', 6),
    ('citrus aurantium ‘bouquetier de nice’', 'citrusaurantium‘bouquetierdenice’', 6),
    ('citrus aurantium ‘myrtifolia’', 'citrusaurantium‘myrtifolia’', 6),
    ('citrus bergamia', 'citrusbergamia', 6),
    ('citrus limon', 'citruslimon', 6),
    ('citrus maxima', 'citrusmaxima', 6),
    ('citrus medica', 'citrusmedica', 6),
    ('citrus medica ‘de corse’', 'citrusmedica‘decorse’', 6),
    ('citrus medica ‘diamante’', 'citrusmedica‘diamante’', 6),
    ('citrus medica ‘main de bouddha’', 'citrusmedica‘maindebouddha’', 6),
    ('citrus mitis', 'citrusmitis', 6),
    ('citrus paradisi', 'citrusparadisi', 6),
    ('citrus sinensis', 'citrussinensis', 6),
    ('citrus unshiu', 'citrusunshiu', 6),
    ('citrus unshiu ‘okitsu’', 'citrusunshiu‘okitsu’', 6),
    ('citrus unshiu ‘owari’', 'citrusunshiu‘owari’', 6),
    ('claytone de cuba', 'claytonedecuba', 6),
    ('clémentine', 'clementine', 6),
    ('coccoloba uvifera', 'coccolobauvifera', 6),
    ('cocos nucifera', 'cocosnucifera', 6),
    ('coing', 'coing', 6),
    ('combava', 'combava', 6),
    ('concombre', 'concombre', 6),
    ('concombre cornu d’afrique', 'concombrecornud’afrique', 6),
    ('coqueret du pérou', 'coqueretduperou', 6),
    ('coquito', 'coquito', 6),
    ('cordia sebestena', 'cordiasebestena', 6),
    ('coriandre', 'coriandre', 6),
    ('corme', 'corme', 6),
    ('cornichon', 'cornichon', 6),
    ('cornouille', 'cornouille', 6),
    ('cornouiller du canada', 'cornouillerducanada', 6),
    ('cornus mas', 'cornusmas', 6),
    ('corossol', 'corossol', 6),
    ('corossol des marais', 'corossoldesmarais', 6),
    ('corossol épineux', 'corossolepineux', 6),
    ('corylus avellana', 'corylusavellana', 6),
    ('courbaril', 'courbaril', 6),
    ('courge', 'courge', 6),
    ('courge cireuse', 'courgecireuse', 6),
    ('courge de siam', 'courgedesiam', 6),
    ('courge musquée', 'courgemusquee', 6),
    ('courgette', 'courgette', 6),
    ('courgette boule', 'courgetteboule', 6),
    ('courgette du siam courgette slawi', 'courgettedusiamcourgetteslawi', 6),
    ('cranberry', 'cranberry', 6),
    ('cresson', 'cresson', 6),
    ('cresson alénois', 'cressonalenois', 6),
    ('cresson de fontaine', 'cressondefontaine', 6),
    ('cresson de para', 'cressondepara', 6),
    ('cresson de terre', 'cressondeterre', 6),
    ('cresson des jardins', 'cressondesjardins', 6),
    ('cresson d’hiver', 'cressond’hiver', 6),
    ('crosne', 'crosne', 6),
    ('crosne du japon', 'crosnedujapon', 6),
    ('crosse de fougère', 'crossedefougere', 6),
    ('cubèbe', 'cubebe', 6),
    ('cucumis metuliferus', 'cucumismetuliferus', 6),
    ('curcuma', 'curcuma', 6),
    ('curuba', 'curuba', 6),
    ('curuba equatoriana', 'curubaequatoriana', 6),
    ('curuba india', 'curubaindia', 6),
    ('curuba rouge', 'curubarouge', 6),
    ('cydonia oblonga', 'cydoniaoblonga', 6),
    ('cynorrhodon', 'cynorrhodon', 6),
    ('cyphomandra betacea', 'cyphomandrabetacea', 6),
    ('cédrat', 'cedrat', 6),
    ('cédrat ‘de corse’', 'cedrat‘decorse’', 6),
    ('cédrat ‘diamante’', 'cedrat‘diamante’', 6),
    ('cédrat ‘main de bouddha’', 'cedrat‘maindebouddha’', 6),
    ('céleri', 'celeri', 6),
    ('céleri branche', 'celeribranche', 6),
    ('céleri rave', 'celerirave', 6),
    ('cérimon', 'cerimon', 6),
    ('dachine', 'dachine', 6),
    ('daikon', 'daikon', 6),
    ('damassine', 'damassine', 6),
    ('date chinoise', 'datechinoise', 6),
    ('datte', 'datte', 6),
    ('diospyros kaki', 'diospyroskaki', 6),
    ('diospyros lotus', 'diospyroslotus', 6),
    ('doigts d’homme mort', 'doigtsd’hommemort', 6),
    ('dolique asperge', 'doliqueasperge', 6),
    ('dolique lablab', 'doliquelablab', 6),
    ('durian', 'durian', 6),
    ('elaeagnus umbellata', 'elaeagnusumbellata', 6),
    ('endive', 'endive', 6),
    ('epine noire', 'epinenoire', 6),
    ('eriobotrya japonica', 'eriobotryajaponica', 6),
    ('estragon', 'estragon', 6),
    ('euphoria longan', 'euphorialongan', 6),
    ('evi', 'evi', 6),
    ('feijoa', 'feijoa', 6),
    ('fenouil', 'fenouil', 6),
    ('feuilde boldo', 'feuildeboldo', 6),
    ('feuilde piper auritum', 'feuildepiperauritum', 6),
    ('fe’i', 'fe’i', 6),
    ('ficoïde glaciale', 'ficoideglaciale', 6),
    ('ficus carica', 'ficuscarica', 6),
    ('figue', 'figue', 6),
    ('figue de barbarie', 'figuedebarbarie', 6),
    ('figue d’inde', 'figued’inde', 6),
    ('flacourtia jangomas', 'flacourtiajangomas', 6),
    ('flageolet', 'flageolet', 6),
    ('fonio', 'fonio', 6),
    ('fortunella japonica', 'fortunellajaponica', 6),
    ('fortunella margarita', 'fortunellamargarita', 6),
    ('fortunella obovata', 'fortunellaobovata', 6),
    ('fragaria vesca', 'fragariavesca', 6),
    ('fraise', 'fraise', 6),
    ('fraise commune', 'fraisecommune', 6),
    ('fraise des bois', 'fraisedesbois', 6),
    ('fraise sauvage', 'fraisesauvage', 6),
    ('framboise', 'framboise', 6),
    ('frisée', 'frisee', 6),
    ('fruit de arbre à laque', 'fruitdearbrealaque', 6),
    ('fruit de la passiflore anémone', 'fruitdelapassifloreanemone', 6),
    ('fruit de la passiflore bleue', 'fruitdelapassiflorebleue', 6),
    ('fruit de la passion', 'fruitdelapassion', 6),
    ('fruit de la ronce', 'fruitdelaronce', 6),
    ('fruit de l’arbre à pain', 'fruitdel’arbreapain', 6),
    ('fruit de sapote blanche', 'fruitdesapoteblanche', 6),
    ('fruit de sébestier', 'fruitdesebestier', 6),
    ('fruit du badamier', 'fruitdubadamier', 6),
    ('fruit du baobab', 'fruitdubaobab', 6),
    ('fruit du bunya bunya', 'fruitdubunyabunya', 6),
    ('fruit du cupuaçule', 'fruitducupuacule', 6),
    ('fruit du dragon', 'fruitdudragon', 6),
    ('fruit du jacquier', 'fruitdujacquier', 6),
    ('fruit du keluak', 'fruitdukeluak', 6),
    ('fruit du palmier abricot', 'fruitdupalmierabricot', 6),
    ('fruit du palmier de guadalupe', 'fruitdupalmierdeguadalupe', 6),
    ('fruit du palmier de saint pierre', 'fruitdupalmierdesaintpierre', 6),
    ('fruit du palmier à gelées', 'fruitdupalmieragelees', 6),
    ('fruit du palmier à vinaigre', 'fruitdupalmieravinaigre', 6),
    ('fruit du parinari curatellifolia', 'fruitduparinaricuratellifolia', 6),
    ('fruit du plaqueminier', 'fruitduplaqueminier', 6),
    ('fruit du siraitia grosvenorii', 'fruitdusiraitiagrosvenorii', 6),
    ('fruit délicieux', 'fruitdelicieux', 6),
    ('fruit d’akebia quinata', 'fruitd’akebiaquinata', 6),
    ('fruit miracle', 'fruitmiracle', 6),
    ('fruit-à-pain', 'fruit-a-pain', 6),
    ('fruits de fuchsia rampant', 'fruitsdefuchsiarampant', 6),
    ('fruits de gaulthérie couchée', 'fruitsdegaultheriecouchee', 6),
    ('fruits du châtaignier de morton', 'fruitsduchataignierdemorton', 6),
    ('fruits du mongongo', 'fruitsdumongongo', 6),
    ('fuchsia procumbens', 'fuchsiaprocumbens', 6),
    ('fève', 'feve', 6),
    ('fève tonka', 'fevetonka', 6),
    ('galipe', 'galipe', 6),
    ('garcinia mangostana', 'garciniamangostana', 6),
    ('gesse', 'gesse', 6),
    ('gingembre', 'gingembre', 6),
    ('girembelle', 'girembelle', 6),
    ('giromon', 'giromon', 6),
    ('glycine tubéreuse', 'glycinetubereuse', 6),
    ('gombo', 'gombo', 6),
    ('gourde', 'gourde', 6),
    ('goyave', 'goyave', 6),
    ('goyave ananas', 'goyaveananas', 6),
    ('goyave de chine', 'goyavedechine', 6),
    ('goyave du brésil', 'goyavedubresil', 6),
    ('goyave du chili', 'goyaveduchili', 6),
    ('goyave fraise', 'goyavefraise', 6),
    ('goyave-ananas', 'goyave-ananas', 6),
    ('goyave-fraise', 'goyave-fraise', 6),
    ('goyave-pomme', 'goyave-pomme', 6),
    ('graines de petai', 'grainesdepetai', 6),
    ('graines de sélim', 'grainesdeselim', 6),
    ('graines du caféier du kentucky', 'grainesducafeierdukentucky', 6),
    ('grande bardane', 'grandebardane', 6),
    ('grelos', 'grelos', 6),
    ('grenade', 'grenade', 6),
    ('grenadelle', 'grenadelle', 6),
    ('grenadille', 'grenadille', 6),
    ('grenadille douce', 'grenadilledouce', 6),
    ('grenadille géante', 'grenadillegeante', 6),
    ('grenadille jaune', 'grenadillejaune', 6),
    ('grenadille sauvage', 'grenadillesauvage', 6),
    ('grenadille violette', 'grenadilleviolette', 6),
    ('grenadille ‘black knight’', 'grenadille‘blackknight’', 6),
    ('griotte', 'griotte', 6),
    ('groseildu cap', 'groseilducap', 6),
    ('groseille', 'groseille', 6),
    ('groseille de chine', 'groseilledechine', 6),
    ('groseille du cap', 'groseilleducap', 6),
    ('groseille à maquereau', 'groseilleamaquereau', 6),
    ('groseille étoilée', 'groseilleetoilee', 6),
    ('groseilnépalaise', 'groseilnepalaise', 6),
    ('guigne', 'guigne', 6),
    ('guimauve officinale', 'guimauveofficinale', 6),
    ('gundelia', 'gundelia', 6),
    ('haricot', 'haricot', 6),
    ('haricot de lima (lunatus)', 'haricotdelima(lunatus)', 6),
    ('haricot d’espagne (coccinea)', 'haricotd’espagne(coccinea)', 6),
    ('haricot grimpant', 'haricotgrimpant', 6),
    ('haricot kilomètre (vigna, dolique)', 'haricotkilometre(vigna,dolique)', 6),
    ('haricot mungo (vigna)', 'haricotmungo(vigna)', 6),
    ('haricot rouge du japon', 'haricotrougedujapon', 6),
    ('haricot vert', 'haricotvert', 6),
    ('haricots bleus', 'haricotsbleus', 6),
    ('hippophae rhamnoides', 'hippophaerhamnoides', 6),
    ('hosta', 'hosta', 6),
    ('houttuynia', 'houttuynia', 6),
    ('hylocereus undatus', 'hylocereusundatus', 6),
    ('hélianthi', 'helianthi', 6),
    ('icaque', 'icaque', 6),
    ('ichang papeda', 'ichangpapeda', 6),
    ('igname', 'igname', 6),
    ('igname ailée', 'ignameailee', 6),
    ('jaboticaba', 'jaboticaba', 6),
    ('jacque', 'jacque', 6),
    ('jamalac', 'jamalac', 6),
    ('jambose rouge', 'jamboserouge', 6),
    ('jamelon', 'jamelon', 6),
    ('jaque', 'jaque', 6),
    ('jubaea chilensis', 'jubaeachilensis', 6),
    ('juglans regia', 'juglansregia', 6),
    ('jujube', 'jujube', 6),
    ('kabosu', 'kabosu', 6),
    ('kaki', 'kaki', 6),
    ('kancon', 'kancon', 6),
    ('kiwano', 'kiwano', 6),
    ('kiwaï', 'kiwai', 6),
    ('kiwi', 'kiwi', 6),
    ('kiwi de sibérie', 'kiwidesiberie', 6),
    ('komatsuna', 'komatsuna', 6),
    ('konbu', 'konbu', 6),
    ('kumquat', 'kumquat', 6),
    ('kumquat fukushu', 'kumquatfukushu', 6),
    ('kumquat marumi', 'kumquatmarumi', 6),
    ('kumquat nagami', 'kumquatnagami', 6),
    ('kumquat ovale', 'kumquatovale', 6),
    ('kumquat rond', 'kumquatrond', 6),
    ('laitue', 'laitue', 6),
    ('laitue romaine', 'laitueromaine', 6),
    ('lentille', 'lentille', 6),
    ('letchi', 'letchi', 6),
    ('lime', 'lime', 6),
    ('limette', 'limette', 6),
    ('liseron d’eau', 'liserond’eau', 6),
    ('litchi', 'litchi', 6),
    ('litchi chevelu', 'litchichevelu', 6),
    ('litchi sinensis', 'litchisinensis', 6),
    ('longane', 'longane', 6),
    ('longani', 'longani', 6),
    ('loquat', 'loquat', 6),
    ('lucuma', 'lucuma', 6),
    ('luffa', 'luffa', 6),
    ('luo han guo', 'luohanguo', 6),
    ('lys asiatique comestible', 'lysasiatiquecomestible', 6),
    ('macadamia integrifolia', 'macadamiaintegrifolia', 6),
    ('maceron', 'maceron', 6),
    ('malpighia glabra', 'malpighiaglabra', 6),
    ('malus communis', 'maluscommunis', 6),
    ('mamey', 'mamey', 6),
    ('mandarine', 'mandarine', 6),
    ('mandarine satsuma', 'mandarinesatsuma', 6),
    ('mandarine satsuma ‘okitsu’', 'mandarinesatsuma‘okitsu’', 6),
    ('mandarine satsuma ‘owari’', 'mandarinesatsuma‘owari’', 6),
    ('mangifera indica', 'mangiferaindica', 6),
    ('mangoustan', 'mangoustan', 6),
    ('mangue', 'mangue', 6),
    ('mangue verte', 'mangueverte', 6),
    ('maniguette', 'maniguette', 6),
    ('manioc', 'manioc', 6),
    ('maracudja', 'maracudja', 6),
    ('marang', 'marang', 6),
    ('margose', 'margose', 6),
    ('marie-gougeat', 'marie-gougeat', 6),
    ('maritambour', 'maritambour', 6),
    ('marjolaine', 'marjolaine', 6),
    ('marron', 'marron', 6),
    ('mauve', 'mauve', 6),
    ('maypop', 'maypop', 6),
    ('maïs', 'mais', 6),
    ('maïs doux', 'maisdoux', 6),
    ('melon', 'melon', 6),
    ('melon (quelques variétés)', 'melon(quelquesvarietes)', 6),
    ('melon à corne', 'melonacorne', 6),
    ('menthe', 'menthe', 6),
    ('merise', 'merise', 6),
    ('merise pays', 'merisepays', 6),
    ('mesle', 'mesle', 6),
    ('mespilus germanica', 'mespilusgermanica', 6),
    ('mineola', 'mineola', 6),
    ('mirabelle', 'mirabelle', 6),
    ('mizuna', 'mizuna', 6),
    ('moboplum', 'moboplum', 6),
    ('mombin', 'mombin', 6),
    ('momordique', 'momordique', 6),
    ('monstera deliciosa', 'monsteradeliciosa', 6),
    ('morus alba', 'morusalba', 6),
    ('morus kagayamae', 'moruskagayamae', 6),
    ('murtilla', 'murtilla', 6),
    ('musa acuminata ‘dwarf cavendish’', 'musaacuminata‘dwarfcavendish’', 6),
    ('myrobolan', 'myrobolan', 6),
    ('myrte', 'myrte', 6),
    ('myrte commun', 'myrtecommun', 6),
    ('myrtille', 'myrtille', 6),
    ('myrtille arbustive', 'myrtillearbustive', 6),
    ('myrtille géante', 'myrtillegeante', 6),
    ('myrtus communis', 'myrtuscommunis', 6),
    ('mâche', 'mache', 6),
    ('mâcre bicorne', 'macrebicorne', 6),
    ('mâcre nageante', 'macrenageante', 6),
    ('métulon', 'metulon', 6),
    ('mûre', 'mure', 6),
    ('mûre blanche', 'mureblanche', 6),
    ('mûre du mûrier-platane', 'muredumurier-platane', 6),
    ('mûroise', 'muroise', 6),
    ('mûron', 'muron', 6),
    ('nashi', 'nashi', 6),
    ('navet', 'navet', 6),
    ('nectarine', 'nectarine', 6),
    ('nephelium lappaceum', 'nepheliumlappaceum', 6),
    ('niébé', 'niebe', 6),
    ('noisette', 'noisette', 6),
    ('noisette commune', 'noisettecommune', 6),
    ('noix', 'noix', 6),
    ('noix commune', 'noixcommune', 6),
    ('noix de cajou', 'noixdecajou', 6),
    ('noix de coco', 'noixdecoco', 6),
    ('noix de coco du chili', 'noixdecocoduchili', 6),
    ('noix de ginkgo biloba', 'noixdeginkgobiloba', 6),
    ('noix de macadam', 'noixdemacadam', 6),
    ('noix de macadamia', 'noixdemacadamia', 6),
    ('noix de muscade', 'noixdemuscade', 6),
    ('noix de pécan', 'noixdepecan', 6),
    ('noix du queensland', 'noixduqueensland', 6),
    ('noix royale', 'noixroyale', 6),
    ('nombril de vénus', 'nombrildevenus', 6),
    ('nopal', 'nopal', 6),
    ('nèfle', 'nefle', 6),
    ('nèfle commune', 'neflecommune', 6),
    ('nèfle du japon', 'nefledujapon', 6),
    ('néflier des indes', 'neflierdesindes', 6),
    ('oca du pérou', 'ocaduperou', 6),
    ('oeil de dragon', 'oeildedragon', 6),
    ('oignon', 'oignon', 6),
    ('oignon de chine', 'oignondechine', 6),
    ('okra', 'okra', 6),
    ('olea europaea', 'oleaeuropaea', 6),
    ('olive', 'olive', 6),
    ('olive de sibérie', 'olivedesiberie', 6),
    ('olive d’automne', 'olived’automne', 6),
    ('onagre', 'onagre', 6),
    ('oponce', 'oponce', 6),
    ('opuntia ficus-indica', 'opuntiaficus-indica', 6),
    ('orange', 'orange', 6),
    ('orange amère', 'orangeamere', 6),
    ('orange amère à feuilles de myrte', 'orangeamereafeuillesdemyrte', 6),
    ('orange amère ‘bouquetier de fleur’', 'orangeamere‘bouquetierdefleur’', 6),
    ('orange amère ‘bouquetier de nice’', 'orangeamere‘bouquetierdenice’', 6),
    ('orange d’appartement', 'oranged’appartement', 6),
    ('orange sanguine', 'orangesanguine', 6),
    ('orangine', 'orangine', 6),
    ('origan', 'origan', 6),
    ('ortie', 'ortie', 6),
    ('oseille', 'oseille', 6),
    ('pain de singe', 'paindesinge', 6),
    ('pak choï', 'pakchoi', 6),
    ('pamplemousse', 'pamplemousse', 6),
    ('panais', 'panais', 6),
    ('papaye', 'papaye', 6),
    ('papaye des montagnes', 'papayedesmontagnes', 6),
    ('parépou', 'parepou', 6),
    ('passiflora actinia', 'passifloraactinia', 6),
    ('passiflora alata', 'passifloraalata', 6),
    ('passiflora antioquiensis', 'passifloraantioquiensis', 6),
    ('passiflora caerulea', 'passifloracaerulea', 6),
    ('passiflora edulis', 'passifloraedulis', 6),
    ('passiflora edulis var. flavicarpa', 'passifloraedulisvar.flavicarpa', 6),
    ('passiflora edulis ‘black knight’', 'passifloraedulis‘blackknight’', 6),
    ('passiflora foetida', 'passiflorafoetida', 6),
    ('passiflora incarnata', 'passifloraincarnata', 6),
    ('passiflora laurifolia', 'passifloralaurifolia', 6),
    ('passiflora ligularis', 'passifloraligularis', 6),
    ('passiflora mollissima', 'passifloramollissima', 6),
    ('passiflora quadrangularis', 'passifloraquadrangularis', 6),
    ('passiflora tarminiana', 'passifloratarminiana', 6),
    ('passiflore poc-poc', 'passiflorepoc-poc', 6),
    ('pastèque', 'pasteque', 6),
    ('patate', 'patate', 6),
    ('patate douce', 'patatedouce', 6),
    ('pavie', 'pavie', 6),
    ('pe-tsaï', 'pe-tsai', 6),
    ('pepino', 'pepino', 6),
    ('persea americana', 'perseaamericana', 6),
    ('persil', 'persil', 6),
    ('petit oignon blanc', 'petitoignonblanc', 6),
    ('petit pois', 'petitpois', 6),
    ('petits pois', 'petitspois', 6),
    ('phoenix dactylifera', 'phoenixdactylifera', 6),
    ('phyllanthus acidus', 'phyllanthusacidus', 6),
    ('physalis', 'physalis', 6),
    ('physalis peruviana', 'physalisperuviana', 6),
    ('pignon de pin', 'pignondepin', 6),
    ('piment', 'piment', 6),
    ('piment rouge de savina', 'pimentrougedesavina', 6),
    ('pissenlit', 'pissenlit', 6),
    ('pistache', 'pistache', 6),
    ('pistacia vera', 'pistaciavera', 6),
    ('pitahaya', 'pitahaya', 6),
    ('pitaya', 'pitaya', 6),
    ('plaquebière', 'plaquebiere', 6),
    ('plaquemine d’europe', 'plaquemined’europe', 6),
    ('poire', 'poire', 6),
    ('poire commune', 'poirecommune', 6),
    ('poire de table', 'poiredetable', 6),
    ('poire de terre', 'poiredeterre', 6),
    ('poire-melon', 'poire-melon', 6),
    ('poireau', 'poireau', 6),
    ('poirée', 'poiree', 6),
    ('pois carré', 'poiscarre', 6),
    ('pois chiche', 'poischiche', 6),
    ('pois doux', 'poisdoux', 6),
    ('pois d’angole', 'poisd’angole', 6),
    ('pois mange-tout', 'poismange-tout', 6),
    ('pois sabre', 'poissabre', 6),
    ('pois sec', 'poissec', 6),
    ('poivron', 'poivron', 6),
    ('pomme', 'pomme', 6),
    ('pomme cajou', 'pommecajou', 6),
    ('pomme cannelle', 'pommecannelle', 6),
    ('pomme de cajou', 'pommedecajou', 6),
    ('pomme de cydon', 'pommedecydon', 6),
    ('pomme de cythère', 'pommedecythere', 6),
    ('pomme de jacque', 'pommedejacque', 6),
    ('pomme de lait', 'pommedelait', 6),
    ('pomme de mai', 'pommedemai', 6),
    ('pomme de noix de coco', 'pommedenoixdecoco', 6),
    ('pomme de terre', 'pommedeterre', 6),
    ('pomme d’eau', 'pommed’eau', 6),
    ('pomme d’or', 'pommed’or', 6),
    ('pomme d’émeu', 'pommed’emeu', 6),
    ('pomme liane', 'pommeliane', 6),
    ('pomme mexicaine', 'pommemexicaine', 6),
    ('pomme rosée', 'pommerosee', 6),
    ('pomme visqueuse', 'pommevisqueuse', 6),
    ('pomme-kangourou de tasmanie', 'pomme-kangouroudetasmanie', 6),
    ('pomme-surette', 'pomme-surette', 6),
    ('pomélos', 'pomelos', 6),
    ('potimarron', 'potimarron', 6),
    ('potiron', 'potiron', 6),
    ('pourpier', 'pourpier', 6),
    ('pousse douce', 'poussedouce', 6),
    ('prune', 'prune', 6),
    ('prune citron', 'prunecitron', 6),
    ('prune coton', 'prunecoton', 6),
    ('prune de cythère', 'prunedecythere', 6),
    ('prune de sucre (sugar plum)', 'prunedesucre(sugarplum)', 6),
    ('prune du natal', 'prunedunatal', 6),
    ('prune d’inde', 'pruned’inde', 6),
    ('pruneau', 'pruneau', 6),
    ('prunelle', 'prunelle', 6),
    ('prunes', 'prunes', 6),
    ('prunes de davidsonia', 'prunesdedavidsonia', 6),
    ('prunus armeniaca', 'prunusarmeniaca', 6),
    ('prunus avium', 'prunusavium', 6),
    ('prunus domestica', 'prunusdomestica', 6),
    ('prunus dulcis', 'prunusdulcis', 6),
    ('prunus persica', 'prunuspersica', 6),
    ('prunus spinosa', 'prunusspinosa', 6),
    ('psidium cattleianum', 'psidiumcattleianum', 6),
    ('psidium guajava', 'psidiumguajava', 6),
    ('punica granatum', 'punicagranatum', 6),
    ('pyrus communis', 'pyruscommunis', 6),
    ('pâte de graines de lotus', 'patedegrainesdelotus', 6),
    ('pâtisson', 'patisson', 6),
    ('périlla', 'perilla', 6),
    ('pêche', 'peche', 6),
    ('quenette', 'quenette', 6),
    ('quetsche', 'quetsche', 6),
    ('racines de sassafras', 'racinesdesassafras', 6),
    ('radicchio', 'radicchio', 6),
    ('radis', 'radis', 6),
    ('radis du japon', 'radisdujapon', 6),
    ('radis long', 'radislong', 6),
    ('radis noir', 'radisnoir', 6),
    ('radis rouge', 'radisrouge', 6),
    ('radis serpent', 'radisserpent', 6),
    ('raifort', 'raifort', 6),
    ('raisin', 'raisin', 6),
    ('raisin bord-de-mer', 'raisinbord-de-mer', 6),
    ('raisin marine', 'raisinmarine', 6),
    ('ramboutan', 'ramboutan', 6),
    ('reine-claude', 'reine-claude', 6),
    ('rhubarbe', 'rhubarbe', 6),
    ('ribes rubrum', 'ribesrubrum', 6),
    ('ribes uva-crispa', 'ribesuva-crispa', 6),
    ('romarin', 'romarin', 6),
    ('roquette', 'roquette', 6),
    ('rubus fruticosus', 'rubusfruticosus', 6),
    ('rubus idaeus', 'rubusidaeus', 6),
    ('rutabaga', 'rutabaga', 6),
    ('safou', 'safou', 6),
    ('sahlep', 'sahlep', 6),
    ('salacca', 'salacca', 6),
    ('salade', 'salade', 6),
    ('salades', 'salades', 6),
    ('salak', 'salak', 6),
    ('salak ou fruit serpent', 'salakoufruitserpent', 6),
    ('salicorne', 'salicorne', 6),
    ('salsifi', 'salsifi', 6),
    ('salsifis', 'salsifis', 6),
    ('salsifis topinambour', 'salsifistopinambour', 6),
    ('sapote', 'sapote', 6),
    ('sapote blanche', 'sapoteblanche', 6),
    ('sapotille', 'sapotille', 6),
    ('sauge', 'sauge', 6),
    ('scarole (chicorée)', 'scarole(chicoree)', 6),
    ('scorsonère', 'scorsonere', 6),
    ('serpent gourde', 'serpentgourde', 6),
    ('serpent végétal', 'serpentvegetal', 6),
    ('shaddock', 'shaddock', 6),
    ('shiso', 'shiso', 6),
    ('soja', 'soja', 6),
    ('solanum laciniatum', 'solanumlaciniatum', 6),
    ('solanum muricatum', 'solanummuricatum', 6),
    ('sorbus domestica', 'sorbusdomestica', 6),
    ('souchet comestible', 'souchetcomestible', 6),
    ('souris végétale', 'sourisvegetale', 6),
    ('spondias dulcis', 'spondiasdulcis', 6),
    ('strobidu gnetum gnemon', 'strobidugnetumgnemon', 6),
    ('sudachi', 'sudachi', 6),
    ('sureau noir', 'sureaunoir', 6),
    ('surelle', 'surelle', 6),
    ('syzygium malaccense', 'syzygiummalaccense', 6),
    ('tacso', 'tacso', 6),
    ('tacso de castilla', 'tacsodecastilla', 6),
    ('tamarillo', 'tamarillo', 6),
    ('tamarin', 'tamarin', 6),
    ('tamarin des indes', 'tamarindesindes', 6),
    ('tamarin d’inde', 'tamarind’inde', 6),
    ('tamarindus indica', 'tamarindusindica', 6),
    ('tangelo', 'tangelo', 6),
    ('tangerine', 'tangerine', 6),
    ('tangor', 'tangor', 6),
    ('tarap', 'tarap', 6),
    ('taro', 'taro', 6),
    ('taxo', 'taxo', 6),
    ('terminalia catappa', 'terminaliacatappa', 6),
    ('theobroma cacao', 'theobromacacao', 6),
    ('thym', 'thym', 6),
    ('tinda', 'tinda', 6),
    ('tomate', 'tomate', 6),
    ('tomate en arbre', 'tomateenarbre', 6),
    ('tomatille', 'tomatille', 6),
    ('tomatillo', 'tomatillo', 6),
    ('topinambour', 'topinambour', 6),
    ('triphasia trifoliata', 'triphasiatrifoliata', 6),
    ('tétragone', 'tetragone', 6),
    ('tétragone cornue', 'tetragonecornue', 6),
    ('têtes de violon', 'tetesdeviolon', 6),
    ('udo', 'udo', 6),
    ('ugli', 'ugli', 6),
    ('ugni', 'ugni', 6),
    ('ugni molinae', 'ugnimolinae', 6),
    ('vaccinium corymbosum', 'vacciniumcorymbosum', 6),
    ('vaccinium macrocarpum', 'vacciniummacrocarpum', 6),
    ('vaccinium vitis-idaea', 'vacciniumvitis-idaea', 6),
    ('vangueria madagascariensis', 'vangueriamadagascariensis', 6),
    ('vanille', 'vanille', 6),
    ('vavandrika', 'vavandrika', 6),
    ('vavangue', 'vavangue', 6),
    ('vigne', 'vigne', 6),
    ('vitelotte', 'vitelotte', 6),
    ('vitis vinifera', 'vitisvinifera', 6),
    ('wakame', 'wakame', 6),
    ('wasabi', 'wasabi', 6),
    ('ximenia', 'ximenia', 6),
    ('yacón', 'yacon', 6),
    ('yin tsoï', 'yintsoi', 6),
    ('yucca filifera', 'yuccafilifera', 6),
    ('yuzu', 'yuzu', 6),
    ('zatte', 'zatte', 6),
    ('ziziphus jujuba', 'ziziphusjujuba', 6),
    ('ziziphus mauritiana', 'ziziphusmauritiana', 6),
    ('échalote', 'echalote', 6),
    ('épinard', 'epinard', 6),
    ('épinard de malabar', 'epinarddemalabar', 6),
    ('épine-vinette', 'epine-vinette', 6)
ON CONFLICT (mot_normalized, categorie_id) DO NOTHING;
