INSERT INTO mots (mot, mot_normalized, categorie_id) VALUES
    ('Abeille', 'abeille', 4),
    ('Abeille charpentière', 'abeille charpentiere', 4),
    ('Abeille découpeuse', 'abeille decoupeuse', 4),
    ('Abeille tueuse', 'abeille tueuse', 4),
    ('Abeille à miel', 'abeille a miel', 4),
    ('Able de Heckel', 'able de heckel', 4),
    ('Ablette', 'ablette', 4),
    ('Abyssin', 'abyssin', 4),
    ('Acarien', 'acarien', 4),
    ('Acarien rouge', 'acarien rouge', 4),
    ('Accenteur alpin', 'accenteur alpin', 4),
    ('Accenteur mouchet', 'accenteur mouchet', 4),
    ('Achigan à grande bouche', 'achigan a grande bouche', 4),
    ('Acouchi', 'acouchi', 4),
    ('Addax', 'addax', 4),
    ('Agame Barbu', 'agame barbu', 4),
    ('Agame des colons', 'agame des colons', 4),
    ('Agneau', 'agneau', 4),
    ('Agouti', 'agouti', 4),
    ('Agouti doré', 'agouti dore', 4),
    ('Agouti ponctué', 'agouti ponctue', 4),
    ('Agrion jouvencelle', 'agrion jouvencelle', 4),
    ('Agrion élégant', 'agrion elegant', 4),
    ('Aigle', 'aigle', 4),
    ('Aigle royal', 'aigle royal', 4),
    ('Aiglefin', 'aiglefin', 4),
    ('Aigrette', 'aigrette', 4),
    ('Aigrette garzette', 'aigrette garzette', 4),
    ('Aiguillat', 'aiguillat', 4),
    ('Aiguillat noir', 'aiguillat noir', 4),
    ('Ailurops', 'ailurops', 4),
    ('Akhal téké doré', 'akhal teke dore', 4),
    ('Akita Inu', 'akita inu', 4),
    ('Akita americain', 'akita americain', 4),
    ('Albatros', 'albatros', 4),
    ('Albatros hurleur', 'albatros hurleur', 4),
    ('Alligator', 'alligator', 4),
    ('Alligator américain', 'alligator americain', 4),
    ('Alligator d’Amérique', 'alligator damerique', 4),
    ('Allocèbe', 'allocebe', 4),
    ('Alose', 'alose', 4),
    ('Alouate', 'alouate', 4),
    ('Alouette', 'alouette', 4),
    ('Alouette des champs', 'alouette des champs', 4),
    ('Alpaga', 'alpaga', 4),
    ('Amazone impériale', 'amazone imperiale', 4),
    ('American curl', 'american curl', 4),
    ('American staff', 'american staff', 4),
    ('Amie', 'amie', 4),
    ('Ammophile des sables', 'ammophile des sables', 4),
    ('Amour blanc', 'amour blanc', 4),
    ('Anaconda', 'anaconda', 4),
    ('Anaconda géant', 'anaconda geant', 4),
    ('Anaconda vert', 'anaconda vert', 4),
    ('Anax empereur', 'anax empereur', 4),
    ('Anchois', 'anchois', 4),
    ('Ane de Provence', 'ane de provence', 4),
    ('Ane grand noir du Berry', 'ane grand noir du berry', 4),
    ('Ane sauvage de Somalie', 'ane sauvage de somalie', 4),
    ('Ane sauvage d’Asie', 'ane sauvage dasie', 4),
    ('Angora Turc', 'angora turc', 4),
    ('Anguille', 'anguille', 4),
    ('Angwantibo', 'angwantibo', 4),
    ('Anhinga', 'anhinga', 4),
    ('Anhinga d’Amérique', 'anhinga damerique', 4),
    ('Anoa', 'anoa', 4),
    ('Anoa des plaines', 'anoa des plaines', 4),
    ('Anolis vert', 'anolis vert', 4),
    ('Anomalure', 'anomalure', 4),
    ('Anophèle', 'anophele', 4),
    ('Anoures', 'anoures', 4),
    ('Antilope', 'antilope', 4),
    ('Antilope Cervicapre', 'antilope cervicapre', 4),
    ('Antilope Nilgaut', 'antilope nilgaut', 4),
    ('Antilope Rouanne', 'antilope rouanne', 4),
    ('Antilope Saiga', 'antilope saiga', 4),
    ('Antilope de Clarke', 'antilope de clarke', 4),
    ('Antilope du Tibet', 'antilope du tibet', 4),
    ('Anémone de mer', 'anemone de mer', 4),
    ('Apelle', 'apelle', 4),
    ('Aplysie', 'aplysie', 4),
    ('Apogon', 'apogon', 4),
    ('Appaloosa', 'appaloosa', 4),
    ('Apron du rhône', 'apron du rhone', 4),
    ('Ara', 'ara', 4),
    ('Ara bleu', 'ara bleu', 4),
    ('Ara de Spix', 'ara de spix', 4),
    ('Ara hyacinthe', 'ara hyacinthe', 4),
    ('Ara jaune et Bleu', 'ara jaune et bleu', 4),
    ('Ara rouge', 'ara rouge', 4),
    ('Araignée', 'araignee', 4),
    ('Araignée banane', 'araignee banane', 4),
    ('Araignée crabe', 'araignee crabe', 4),
    ('Araignée de mer', 'araignee de mer', 4),
    ('Araignée des fissures', 'araignee des fissures', 4),
    ('Araignée loups', 'araignee loups', 4),
    ('Araignée patineuse', 'araignee patineuse', 4),
    ('Araignée sauteuse', 'araignee sauteuse', 4),
    ('Araneidae', 'araneidae', 4),
    ('Araneus', 'araneus', 4),
    ('Araniella', 'araniella', 4),
    ('Araçari d’Azara', 'aracari dazara', 4),
    ('Ardennais', 'ardennais', 4),
    ('Argali', 'argali', 4),
    ('Argiope frelon', 'argiope frelon', 4),
    ('Argus bleu', 'argus bleu', 4),
    ('Arlequin plongeur', 'arlequin plongeur', 4),
    ('Ascalaphe soufré', 'ascalaphe soufre', 4),
    ('Aspe', 'aspe', 4),
    ('Athérure', 'atherure', 4),
    ('Atlas', 'atlas', 4),
    ('Atèle', 'atele', 4),
    ('Atèle noir de Colombie', 'atele noir de colombie', 4),
    ('Aubrac', 'aubrac', 4),
    ('Aulacode', 'aulacode', 4),
    ('Autour', 'autour', 4),
    ('Autour des palombes', 'autour des palombes', 4),
    ('Autruche', 'autruche', 4),
    ('Autruche d’Afrique', 'autruche dafrique', 4),
    ('Avahi', 'avahi', 4),
    ('Avocette d’Amérique', 'avocette damerique', 4),
    ('Avocette élégante', 'avocette elegante', 4),
    ('Axolotl', 'axolotl', 4),
    ('Aye aye', 'aye aye', 4),
    ('Babakoto', 'babakoto', 4),
    ('Babiroussa', 'babiroussa', 4),
    ('Babouin', 'babouin', 4),
    ('Babouin Chacma', 'babouin chacma', 4),
    ('Babouin Hamadryas', 'babouin hamadryas', 4),
    ('Babouin de Guinée', 'babouin de guinee', 4),
    ('Babouin jaune', 'babouin jaune', 4),
    ('Babouin olive', 'babouin olive', 4),
    ('Babouk', 'babouk', 4),
    ('Balanin des noisettes', 'balanin des noisettes', 4),
    ('Balbuzard pêcheur', 'balbuzard pecheur', 4),
    ('Baleine', 'baleine', 4),
    ('Baleine bleue', 'baleine bleue', 4),
    ('Baleine bleue (Rorqual bleu)', 'baleine bleue (rorqual bleu)', 4),
    ('Baleine grise', 'baleine grise', 4),
    ('Baleine à bosse', 'baleine a bosse', 4),
    ('Balinais', 'balinais', 4),
    ('Baliste', 'baliste', 4),
    ('Bandar', 'bandar', 4),
    ('Bandicoot lapin', 'bandicoot lapin', 4),
    ('Banteng', 'banteng', 4),
    ('Bar', 'bar', 4),
    ('Barba', 'barba', 4),
    ('Barbeau', 'barbeau', 4),
    ('Barbican à tête rouge', 'barbican a tete rouge', 4),
    ('Barbotte', 'barbotte', 4),
    ('Barbue de rivière', 'barbue de riviere', 4),
    ('Bardot', 'bardot', 4),
    ('Barge hudsonnienne', 'barge hudsonnienne', 4),
    ('Barge marbrée', 'barge marbree', 4),
    ('Barge rousse', 'barge rousse', 4),
    ('Barge à queue noire', 'barge a queue noire', 4),
    ('Baribal', 'baribal', 4),
    ('Barracuda', 'barracuda', 4),
    ('Barzoï', 'barzoi', 4),
    ('Basenji', 'basenji', 4),
    ('Basilic vert', 'basilic vert', 4),
    ('Basset Hound', 'basset hound', 4),
    ('Bateleur des savanes', 'bateleur des savanes', 4),
    ('Baudet du Poitou', 'baudet du poitou', 4),
    ('Baudroie', 'baudroie', 4),
    ('Bavarelle', 'bavarelle', 4),
    ('Beagle', 'beagle', 4),
    ('Beauceron', 'beauceron', 4),
    ('Beaux yeux', 'beaux yeux', 4),
    ('Bec en sabot', 'bec en sabot', 4),
    ('Bec-croisé bifascié', 'bec-croise bifascie', 4),
    ('Bec-croisé des sapins', 'bec-croise des sapins', 4),
    ('Beira', 'beira', 4),
    ('Belette', 'belette', 4),
    ('Belette d’Europe', 'belette deurope', 4),
    ('Belle-Dame', 'belle-dame', 4),
    ('Bengal', 'bengal', 4),
    ('Berger Allemand', 'berger allemand', 4),
    ('Berger Australien', 'berger australien', 4),
    ('Berger blanc Suisse', 'berger blanc suisse', 4),
    ('Berger de Beauce', 'berger de beauce', 4),
    ('Berger de Brie', 'berger de brie', 4),
    ('Berger d’Anatolie', 'berger danatolie', 4),
    ('Berger d’Ecosse', 'berger decosse', 4),
    ('Berger d’Islande', 'berger dislande', 4),
    ('Bergeronnette grise', 'bergeronnette grise', 4),
    ('Bernache cravant', 'bernache cravant', 4),
    ('Bernache de Hutchins', 'bernache de hutchins', 4),
    ('Bernache du Canada', 'bernache du canada', 4),
    ('Bernache nonnette', 'bernache nonnette', 4),
    ('Bernard l’hermite', 'bernard lhermite', 4),
    ('Bibe', 'bibe', 4),
    ('Biche', 'biche', 4),
    ('Bichon Maltais', 'bichon maltais', 4),
    ('Bigorneau', 'bigorneau', 4),
    ('Bihoreau gris', 'bihoreau gris', 4),
    ('Bihoreau violacé', 'bihoreau violace', 4),
    ('Billard', 'billard', 4),
    ('Binturong', 'binturong', 4),
    ('Bison', 'bison', 4),
    ('Bison d’Amérique du Nord', 'bison damerique du nord', 4),
    ('Bison d’Europe', 'bison deurope', 4),
    ('Black-Bass', 'black-bass', 4),
    ('Blade', 'blade', 4),
    ('Blageon', 'blageon', 4),
    ('Blaireau', 'blaireau', 4),
    ('Blaireau d’Amérique', 'blaireau damerique', 4),
    ('Blaireau d’Europe', 'blaireau deurope', 4),
    ('Blaireau européen', 'blaireau europeen', 4),
    ('Blanchet', 'blanchet', 4),
    ('Blastophage', 'blastophage', 4),
    ('Blatte', 'blatte', 4),
    ('Blennie', 'blennie', 4),
    ('Blesbok', 'blesbok', 4),
    ('Blesbok (Damalisque)', 'blesbok (damalisque)', 4),
    ('Bleu russe', 'bleu russe', 4),
    ('Blobfish', 'blobfish', 4),
    ('Blongios nain', 'blongios nain', 4),
    ('Boa', 'boa', 4),
    ('Boa constricteur', 'boa constricteur', 4),
    ('Bobcat', 'bobcat', 4),
    ('Bobtail', 'bobtail', 4),
    ('Boeuf', 'boeuf', 4),
    ('Boeuf musqué', 'boeuf musque', 4),
    ('Bogue', 'bogue', 4),
    ('Bombyle', 'bombyle', 4),
    ('Bombyx du mûrier', 'bombyx du murier', 4),
    ('Bondrée apivore', 'bondree apivore', 4),
    ('Bongare', 'bongare', 4),
    ('Bongo', 'bongo', 4),
    ('Bonite', 'bonite', 4),
    ('Bonobo', 'bonobo', 4),
    ('Boomslang', 'boomslang', 4),
    ('Border-collie', 'border-collie', 4),
    ('Bostryche typographe', 'bostryche typographe', 4),
    ('Boto', 'boto', 4),
    ('Bouledogue Anglais', 'bouledogue anglais', 4),
    ('Bouledogue Français', 'bouledogue francais', 4),
    ('Bouquetin', 'bouquetin', 4),
    ('Bouquetin de Nubie', 'bouquetin de nubie', 4),
    ('Bouquetin de Sibérie (Yanghir)', 'bouquetin de siberie (yanghir)', 4),
    ('Bouquetin des Alpes', 'bouquetin des alpes', 4),
    ('Bouquetin d’Abyssinie', 'bouquetin dabyssinie', 4),
    ('Bourdon', 'bourdon', 4),
    ('Bourdon terrestre', 'bourdon terrestre', 4),
    ('Bousier', 'bousier', 4),
    ('Bouvier Bernois', 'bouvier bernois', 4),
    ('Bouvière', 'bouviere', 4),
    ('Bouvreuil pivoine', 'bouvreuil pivoine', 4),
    ('Boxer', 'boxer', 4),
    ('Braque Allemand', 'braque allemand', 4),
    ('Brebis', 'brebis', 4),
    ('Briard', 'briard', 4),
    ('British shorthair', 'british shorthair', 4),
    ('Brochet', 'brochet', 4),
    ('Brosme', 'brosme', 4),
    ('Bruant', 'bruant', 4),
    ('Bruant jaune', 'bruant jaune', 4),
    ('Bruant ortolan', 'bruant ortolan', 4),
    ('Brumby', 'brumby', 4),
    ('Brème', 'breme', 4),
    ('Brûlot', 'brulot', 4),
    ('Bubale de Coke', 'bubale de coke', 4),
    ('Bubale roux', 'bubale roux', 4),
    ('Buffle', 'buffle', 4),
    ('Buffle d’Afrique', 'buffle dafrique', 4),
    ('Buffle d’Asie', 'buffle dasie', 4),
    ('Buffle d’eau', 'buffle deau', 4),
    ('Bulldog Anglais', 'bulldog anglais', 4),
    ('Bulot', 'bulot', 4),
    ('Bungare', 'bungare', 4),
    ('Burmese', 'burmese', 4),
    ('Busard', 'busard', 4),
    ('Busard Saint-Martin', 'busard saint-martin', 4),
    ('Buse', 'buse', 4),
    ('Buse variable', 'buse variable', 4),
    ('Buse à épaulettes', 'buse a epaulettes', 4),
    ('Butor', 'butor', 4),
    ('Butor d’Amérique', 'butor damerique', 4),
    ('Butor étoilé', 'butor etoile', 4),
    ('Bécasse', 'becasse', 4),
    ('Bécasseau de Baird', 'becasseau de baird', 4),
    ('Bécasseau maubèche', 'becasseau maubeche', 4),
    ('Bécasseau minuscule', 'becasseau minuscule', 4),
    ('Bécasseau roussâtre', 'becasseau roussatre', 4),
    ('Bécasseau sanderling', 'becasseau sanderling', 4),
    ('Bécasseau semipalmé', 'becasseau semipalme', 4),
    ('Bécasseau variable', 'becasseau variable', 4),
    ('Bécasseau à croupion blanc', 'becasseau a croupion blanc', 4),
    ('Bécasseau à poitrine cendrée', 'becasseau a poitrine cendree', 4),
    ('Bécasseau à échasse', 'becasseau a echasse', 4),
    ('Bécassin roux', 'becassin roux', 4),
    ('Bécassin à long bec', 'becassin a long bec', 4),
    ('Bécassine', 'becassine', 4),
    ('Bécassine de Wilson', 'becassine de wilson', 4),
    ('Béluga', 'beluga', 4),
    ('Bénitier', 'benitier', 4),
    ('Cabiaï', 'cabiai', 4),
    ('Cabillaud', 'cabillaud', 4),
    ('Cacatoès', 'cacatoes', 4),
    ('Cacatoès funèbre', 'cacatoes funebre', 4),
    ('Cacatoès noir', 'cacatoes noir', 4),
    ('Cacatoès rosalbin', 'cacatoes rosalbin', 4),
    ('Cacatoès à huppe jaune', 'cacatoes a huppe jaune', 4),
    ('Cachalot', 'cachalot', 4),
    ('Cafard', 'cafard', 4),
    ('Caille', 'caille', 4),
    ('Caille des blés', 'caille des bles', 4),
    ('Calamar', 'calamar', 4),
    ('Calandre', 'calandre', 4),
    ('Calao', 'calao', 4),
    ('Calao bicorne', 'calao bicorne', 4),
    ('Calao leucomèle', 'calao leucomele', 4),
    ('Calao terrestre', 'calao terrestre', 4),
    ('Calao à cimier', 'calao a cimier', 4),
    ('Calliphoridé', 'calliphoride', 4),
    ('Calliste septicolore', 'calliste septicolore', 4),
    ('Calmar', 'calmar', 4),
    ('Calopsitte élégante', 'calopsitte elegante', 4),
    ('Caloptéryx vierge', 'calopteryx vierge', 4),
    ('Calotriton', 'calotriton', 4),
    ('Calyptostomatidae', 'calyptostomatidae', 4),
    ('Camargue', 'camargue', 4),
    ('Campagnol', 'campagnol', 4),
    ('Campagnol des champs', 'campagnol des champs', 4),
    ('Campagnol roussâtre', 'campagnol roussatre', 4),
    ('Caméléon', 'cameleon', 4),
    ('Caméléon panthère', 'cameleon panthere', 4),
    ('Canard', 'canard', 4),
    ('Canard branchu', 'canard branchu', 4),
    ('Canard chipeau', 'canard chipeau', 4),
    ('Canard colvert', 'canard colvert', 4),
    ('Canard mandarin', 'canard mandarin', 4),
    ('Canard noir', 'canard noir', 4),
    ('Canard pilet', 'canard pilet', 4),
    ('Canard siffleur', 'canard siffleur', 4),
    ('Canard souchet', 'canard souchet', 4),
    ('Canaris', 'canaris', 4),
    ('Cane corso', 'cane corso', 4),
    ('Capelan', 'capelan', 4),
    ('Capret', 'capret', 4),
    ('Capricorne des cactus', 'capricorne des cactus', 4),
    ('Capricorne des maisons', 'capricorne des maisons', 4),
    ('Capricorne du chêne', 'capricorne du chene', 4),
    ('Capucin', 'capucin', 4),
    ('Capucin brun', 'capucin brun', 4),
    ('Capybara', 'capybara', 4),
    ('Carabe doré', 'carabe dore', 4),
    ('Carabe violet', 'carabe violet', 4),
    ('Caracal', 'caracal', 4),
    ('Caracara', 'caracara', 4),
    ('Caracara huppé', 'caracara huppe', 4),
    ('Carassin', 'carassin', 4),
    ('Carassin doré', 'carassin dore', 4),
    ('Carcajou', 'carcajou', 4),
    ('Cardinal rouge', 'cardinal rouge', 4),
    ('Cardinal à poitrine rose', 'cardinal a poitrine rose', 4),
    ('Cardine franche', 'cardine franche', 4),
    ('Cariacou', 'cariacou', 4),
    ('Caribou', 'caribou', 4),
    ('Carlin', 'carlin', 4),
    ('Carouge à tête jaune', 'carouge a tete jaune', 4),
    ('Carouge à épaulettes', 'carouge a epaulettes', 4),
    ('Carpe', 'carpe', 4),
    ('Carpet Soleil', 'carpet soleil', 4),
    ('Carrelet', 'carrelet', 4),
    ('Casoar', 'casoar', 4),
    ('Casoar à casque', 'casoar a casque', 4),
    ('Castagnole', 'castagnole', 4),
    ('Castor', 'castor', 4),
    ('Castor de montagne', 'castor de montagne', 4),
    ('Castor du Canada', 'castor du canada', 4),
    ('Castor d’Europe', 'castor deurope', 4),
    ('Cavalier King Charles', 'cavalier king charles', 4),
    ('Caïman', 'caiman', 4),
    ('Caïman noir', 'caiman noir', 4),
    ('Caïman à lunettes', 'caiman a lunettes', 4),
    ('Cercocèbe', 'cercocebe', 4),
    ('Cercope', 'cercope', 4),
    ('Cercopithèque', 'cercopitheque', 4),
    ('Cercopithèque de Brazza', 'cercopitheque de brazza', 4),
    ('Cercopithèque de Wolf', 'cercopitheque de wolf', 4),
    ('Cerf', 'cerf', 4),
    ('Cerf Axis', 'cerf axis', 4),
    ('Cerf cochon', 'cerf cochon', 4),
    ('Cerf de Virginie', 'cerf de virginie', 4),
    ('Cerf elaphe', 'cerf elaphe', 4),
    ('Cerf élaphe', 'cerf elaphe', 4),
    ('Cerf-souris', 'cerf-souris', 4),
    ('Cernier', 'cernier', 4),
    ('Chabot', 'chabot', 4),
    ('Chacal', 'chacal', 4),
    ('Chacal doré (chacal commun)', 'chacal dore (chacal commun)', 4),
    ('Chacal à chabraque', 'chacal a chabraque', 4),
    ('Chacal à dos noir', 'chacal a dos noir', 4),
    ('Chacal à flancs rayés', 'chacal a flancs rayes', 4),
    ('Chacma', 'chacma', 4),
    ('Chameau', 'chameau', 4),
    ('Chameau de bactriane', 'chameau de bactriane', 4),
    ('Chameau domestique', 'chameau domestique', 4),
    ('Chameau sauvage de Tartarie', 'chameau sauvage de tartarie', 4),
    ('Chamois', 'chamois', 4),
    ('Chapon', 'chapon', 4),
    ('Charançon du blé', 'charancon du ble', 4),
    ('Charançon rouge des palmiers', 'charancon rouge des palmiers', 4),
    ('Chardonneret jaune', 'chardonneret jaune', 4),
    ('Chardonneret élégant', 'chardonneret elegant', 4),
    ('Charolaise', 'charolaise', 4),
    ('Chartreux', 'chartreux', 4),
    ('Chat', 'chat', 4),
    ('Chat de Geoffroy', 'chat de geoffroy', 4),
    ('Chat de Pallas', 'chat de pallas', 4),
    ('Chat de Temmick', 'chat de temmick', 4),
    ('Chat de temminck', 'chat de temminck', 4),
    ('Chat des Andes', 'chat des andes', 4),
    ('Chat des forêts', 'chat des forets', 4),
    ('Chat des marais', 'chat des marais', 4),
    ('Chat des sables', 'chat des sables', 4),
    ('Chat d’Iriomote', 'chat diriomote', 4),
    ('Chat loutre', 'chat loutre', 4),
    ('Chat marsupial', 'chat marsupial', 4),
    ('Chat pêcheur', 'chat pecheur', 4),
    ('Chat sauvage', 'chat sauvage', 4),
    ('Chat viverrin', 'chat viverrin', 4),
    ('Chat à pieds noirs', 'chat a pieds noirs', 4),
    ('Chat-huant', 'chat-huant', 4),
    ('Chat-pêcheur', 'chat-pecheur', 4),
    ('Chaus', 'chaus', 4),
    ('Chauve souris géante', 'chauve souris geante', 4),
    ('Chauve-souris', 'chauve-souris', 4),
    ('Chauve-souris pipistrelle commune', 'chauve-souris pipistrelle commune', 4),
    ('Chenille', 'chenille', 4),
    ('Cheval', 'cheval', 4),
    ('Chevalier', 'chevalier', 4),
    ('Chevalier grivelé', 'chevalier grivele', 4),
    ('Chevalier solitaire', 'chevalier solitaire', 4),
    ('Chevesne', 'chevesne', 4),
    ('Chevreuil', 'chevreuil', 4),
    ('Chevrotin de Balabac', 'chevrotin de balabac', 4),
    ('Chevêche des terrier', 'cheveche des terrier', 4),
    ('Chevêche d’Athéna', 'cheveche dathena', 4),
    ('Chien', 'chien', 4),
    ('Chien chanteur de Nouvelle Guinée', 'chien chanteur de nouvelle guinee', 4),
    ('Chien chinois à crête', 'chien chinois a crete', 4),
    ('Chien de prairie', 'chien de prairie', 4),
    ('Chien des buissons', 'chien des buissons', 4),
    ('Chien du Groenland', 'chien du groenland', 4),
    ('Chien viverrin', 'chien viverrin', 4),
    ('Chien-loup Tchécoslovaque', 'chien-loup tchecoslovaque', 4),
    ('Chihuahua', 'chihuahua', 4),
    ('Chimpanzé', 'chimpanze', 4),
    ('Chimpanzé commun', 'chimpanze commun', 4),
    ('Chinchilla', 'chinchilla', 4),
    ('Chirogale', 'chirogale', 4),
    ('Chironome', 'chironome', 4),
    ('Chiru', 'chiru', 4),
    ('Chirurgien bleu', 'chirurgien bleu', 4),
    ('Chital', 'chital', 4),
    ('Choucas des tours', 'choucas des tours', 4),
    ('Chouette', 'chouette', 4),
    ('Chouette chevêche d’Athéna', 'chouette cheveche dathena', 4),
    ('Chouette effraie', 'chouette effraie', 4),
    ('Chouette effraie des clochers', 'chouette effraie des clochers', 4),
    ('Chouette hulotte', 'chouette hulotte', 4),
    ('Chouette lapone', 'chouette lapone', 4),
    ('Chow-Chow', 'chow-chow', 4),
    ('Chozchoz', 'chozchoz', 4),
    ('Chrysope', 'chrysope', 4),
    ('Chrysope nacrée', 'chrysope nacree', 4),
    ('Chrysope verte', 'chrysope verte', 4),
    ('Chèvre', 'chevre', 4),
    ('Chèvre des montagnes rocheuses', 'chevre des montagnes rocheuses', 4),
    ('Chèvre du Caucase Occidental', 'chevre du caucase occidental', 4),
    ('Chèvre naine', 'chevre naine', 4),
    ('Cicadelle blanche', 'cicadelle blanche', 4),
    ('Cicindèle', 'cicindele', 4),
    ('Cigale', 'cigale', 4),
    ('Cigale bossue', 'cigale bossue', 4),
    ('Cigale commune', 'cigale commune', 4),
    ('Cigale de mer', 'cigale de mer', 4),
    ('Cigale grise', 'cigale grise', 4),
    ('Cigale plébéienne', 'cigale plebeienne', 4),
    ('Cigogne', 'cigogne', 4),
    ('Cigogne blanche', 'cigogne blanche', 4),
    ('Cigogne noire', 'cigogne noire', 4),
    ('Cincle plongeur', 'cincle plongeur', 4),
    ('Cinglard', 'cinglard', 4),
    ('Circaète Jean Leblanc', 'circaete jean leblanc', 4),
    ('Circaète Jean-le-Blanc', 'circaete jean-le-blanc', 4),
    ('Cistude d’Europe', 'cistude deurope', 4),
    ('Citron de Provence', 'citron de provence', 4),
    ('Civette', 'civette', 4),
    ('Civette africaine', 'civette africaine', 4),
    ('Civette de Malaisie', 'civette de malaisie', 4),
    ('Clairon des abeilles', 'clairon des abeilles', 4),
    ('Clairon des ruches', 'clairon des ruches', 4),
    ('Claresse', 'claresse', 4),
    ('Cloporte', 'cloporte', 4),
    ('Clydesdale', 'clydesdale', 4),
    ('Coati', 'coati', 4),
    ('Coati commun', 'coati commun', 4),
    ('Coati à nez blanc', 'coati a nez blanc', 4),
    ('Coati à queue annelée', 'coati a queue annelee', 4),
    ('Cob irlandais', 'cob irlandais', 4),
    ('Cobaye', 'cobaye', 4),
    ('Cobe de Buffon', 'cobe de buffon', 4),
    ('Cobe de Lechwe', 'cobe de lechwe', 4),
    ('Cobe de Mrs Gray', 'cobe de mrs gray', 4),
    ('Cobe à croissant', 'cobe a croissant', 4),
    ('Cobra', 'cobra', 4),
    ('Cobra royal', 'cobra royal', 4),
    ('Coccinelle', 'coccinelle', 4),
    ('Coccinelle à 7 points', 'coccinelle a 7 points', 4),
    ('Coccinelle à deux points', 'coccinelle a deux points', 4),
    ('Coccinelle à quatorze points', 'coccinelle a quatorze points', 4),
    ('Coccinelle à sept points', 'coccinelle a sept points', 4),
    ('Coccinelle à vingt-deux points', 'coccinelle a vingt-deux points', 4),
    ('Cochevis huppé', 'cochevis huppe', 4),
    ('Cochon', 'cochon', 4),
    ('Cochon d’Inde', 'cochon dinde', 4),
    ('Cockatiel', 'cockatiel', 4),
    ('Cocker Anglais', 'cocker anglais', 4),
    ('Colibri circé', 'colibri circe', 4),
    ('Colibri d’Anna', 'colibri danna', 4),
    ('Colibri porte-épée', 'colibri porte-epee', 4),
    ('Colibri à gorge rubis', 'colibri a gorge rubis', 4),
    ('Colibris', 'colibris', 4),
    ('Colin', 'colin', 4),
    ('Colin de Californie', 'colin de californie', 4),
    ('Colley à poil long', 'colley a poil long', 4),
    ('Colobe', 'colobe', 4),
    ('Colobe d’Angola', 'colobe dangola', 4),
    ('Colocolo', 'colocolo', 4),
    ('Colombe à queue noire', 'colombe a queue noire', 4),
    ('Combattant varié', 'combattant varie', 4),
    ('Comtois', 'comtois', 4),
    ('Concombre de mer', 'concombre de mer', 4),
    ('Condor des Andes', 'condor des andes', 4),
    ('Condors', 'condors', 4),
    ('Condylure à nez étoilé', 'condylure a nez etoile', 4),
    ('Congre', 'congre', 4),
    ('Connemara', 'connemara', 4),
    ('Coq', 'coq', 4),
    ('Coq de roche', 'coq de roche', 4),
    ('Coquille Saint-Jacques', 'coquille saint-jacques', 4),
    ('Coracine casquée', 'coracine casquee', 4),
    ('Corail', 'corail', 4),
    ('Corb', 'corb', 4),
    ('Corbeau', 'corbeau', 4),
    ('Corbeau freux', 'corbeau freux', 4),
    ('Cormoran', 'cormoran', 4),
    ('Cormoran pie', 'cormoran pie', 4),
    ('Cormoran à aigrettes', 'cormoran a aigrettes', 4),
    ('Corneille', 'corneille', 4),
    ('Corneille noire', 'corneille noire', 4),
    ('Cornish rex', 'cornish rex', 4),
    ('Coronelle', 'coronelle', 4),
    ('Coruro', 'coruro', 4),
    ('Coryphène', 'coryphene', 4),
    ('Corégone', 'coregone', 4),
    ('Cotinga de Cayenne', 'cotinga de cayenne', 4),
    ('Coton de Tuléar', 'coton de tulear', 4),
    ('Coucou', 'coucou', 4),
    ('Coucou geai', 'coucou geai', 4),
    ('Coucou gris', 'coucou gris', 4),
    ('Couguar', 'couguar', 4),
    ('Couleuvre', 'couleuvre', 4),
    ('Couleuvre Rayée', 'couleuvre rayee', 4),
    ('Couleuvre verte et jaune', 'couleuvre verte et jaune', 4),
    ('Couleuvre à collier', 'couleuvre a collier', 4),
    ('Coulicou à bec noir', 'coulicou a bec noir', 4),
    ('Courbine', 'courbine', 4),
    ('Couresse à ventre rouge', 'couresse a ventre rouge', 4),
    ('Courlan brun', 'courlan brun', 4),
    ('Courlis corlieu', 'courlis corlieu', 4),
    ('Courtilière', 'courtiliere', 4),
    ('Couscous', 'couscous', 4),
    ('Couscous tacheté', 'couscous tachete', 4),
    ('Coyote', 'coyote', 4),
    ('Crabe', 'crabe', 4),
    ('Crabe des cocotiers', 'crabe des cocotiers', 4),
    ('Crabe royal', 'crabe royal', 4),
    ('Crabier chevelu', 'crabier chevelu', 4),
    ('Crapaud', 'crapaud', 4),
    ('Crapaud d’Amérique', 'crapaud damerique', 4),
    ('Crapaud vert', 'crapaud vert', 4),
    ('Crave à bec rouge', 'crave a bec rouge', 4),
    ('Crevette', 'crevette', 4),
    ('Crevette grise', 'crevette grise', 4),
    ('Crevette rose', 'crevette rose', 4),
    ('Crevette tropicale', 'crevette tropicale', 4),
    ('Crevette-mante', 'crevette-mante', 4),
    ('Criocère du lis', 'criocere du lis', 4),
    ('Criquet', 'criquet', 4),
    ('Crocodile', 'crocodile', 4),
    ('Crocodile américain', 'crocodile americain', 4),
    ('Crocodile du Nil', 'crocodile du nil', 4),
    ('Crocodile marin', 'crocodile marin', 4),
    ('Crotale', 'crotale', 4),
    ('Crotale cascabelle', 'crotale cascabelle', 4),
    ('Crécerelle', 'crecerelle', 4),
    ('Crénilabre', 'crenilabre', 4),
    ('Cténize corse', 'ctenize corse', 4),
    ('Cygne', 'cygne', 4),
    ('Cygne chanteur', 'cygne chanteur', 4),
    ('Cygne noir', 'cygne noir', 4),
    ('Cygne siffleur', 'cygne siffleur', 4),
    ('Cygne trompette', 'cygne trompette', 4),
    ('Cygne tuberculé', 'cygne tubercule', 4),
    ('Cygne à cou noir', 'cygne a cou noir', 4),
    ('Cyprinodonte', 'cyprinodonte', 4),
    ('Céphalophe bleu', 'cephalophe bleu', 4),
    ('Céphalophe de Natal', 'cephalophe de natal', 4),
    ('Céphalophe de Peter', 'cephalophe de peter', 4),
    ('Céphalophe d’Ader', 'cephalophe dader', 4),
    ('Céphalophe noir', 'cephalophe noir', 4),
    ('Céphalophe zèbre', 'cephalophe zebre', 4),
    ('Céphalophe zébré', 'cephalophe zebre', 4),
    ('Céphalophe à dos jaune', 'cephalophe a dos jaune', 4),
    ('Céphalophe à flancs roux', 'cephalophe a flancs roux', 4),
    ('Céphalophe à front noir', 'cephalophe a front noir', 4),
    ('Céphalophe à ventre blanc', 'cephalophe a ventre blanc', 4),
    ('Céraste', 'ceraste', 4),
    ('Cétoine', 'cetoine', 4),
    ('Cétoine dorée', 'cetoine doree', 4),
    ('Cétoine grise', 'cetoine grise', 4),
    ('Cétoine marginée', 'cetoine marginee', 4),
    ('Daim', 'daim', 4),
    ('Dalmatien', 'dalmatien', 4),
    ('Damalisque', 'damalisque', 4),
    ('Daman du Cap', 'daman du cap', 4),
    ('Dasyure', 'dasyure', 4),
    ('Daubenet', 'daubenet', 4),
    ('Dauphin', 'dauphin', 4),
    ('Dauphin commun à bec court', 'dauphin commun a bec court', 4),
    ('Dauphin pilote', 'dauphin pilote', 4),
    ('Dauphin rose d’Amazonie', 'dauphin rose damazonie', 4),
    ('Dauphin souffleur', 'dauphin souffleur', 4),
    ('Deerhound', 'deerhound', 4),
    ('Demi diable', 'demi diable', 4),
    ('Dendrobate bleue', 'dendrobate bleue', 4),
    ('Dendrobate fraise', 'dendrobate fraise', 4),
    ('Dendrocygne à ventre noir', 'dendrocygne a ventre noir', 4),
    ('Dendrolague', 'dendrolague', 4),
    ('Denti', 'denti', 4),
    ('Desman', 'desman', 4),
    ('Dhole', 'dhole', 4),
    ('Diable cornu', 'diable cornu', 4),
    ('Diable de Tasmanie', 'diable de tasmanie', 4),
    ('Diamant', 'diamant', 4),
    ('Dickcissel d’Amérique', 'dickcissel damerique', 4),
    ('Dictynidé', 'dictynide', 4),
    ('Dik dik', 'dik dik', 4),
    ('Dik-dik argenté', 'dik-dik argente', 4),
    ('Dik-dik de Gunther', 'dik-dik de gunther', 4),
    ('Dik-dik de Kirk', 'dik-dik de kirk', 4),
    ('Dik-dik de Salt', 'dik-dik de salt', 4),
    ('Dinde', 'dinde', 4),
    ('Dindon', 'dindon', 4),
    ('Dingo', 'dingo', 4),
    ('Doberman', 'doberman', 4),
    ('Dodo', 'dodo', 4),
    ('Dogue Allemand', 'dogue allemand', 4),
    ('Dogue de Bordeaux', 'dogue de bordeaux', 4),
    ('Dogue du Tibet', 'dogue du tibet', 4),
    ('Dolomède des marais', 'dolomede des marais', 4),
    ('Dorade', 'dorade', 4),
    ('Dorade rose', 'dorade rose', 4),
    ('Dormelle', 'dormelle', 4),
    ('Doryphore', 'doryphore', 4),
    ('Doryphore de la pomme de terre', 'doryphore de la pomme de terre', 4),
    ('Dorée jaune', 'doree jaune', 4),
    ('Douc', 'douc', 4),
    ('Douroucouli', 'douroucouli', 4),
    ('Draco volans', 'draco volans', 4),
    ('Dragon de Komodo', 'dragon de komodo', 4),
    ('Dragon d’Australie', 'dragon daustralie', 4),
    ('Dragon d’eau', 'dragon deau', 4),
    ('Dragonnet', 'dragonnet', 4),
    ('Drill', 'drill', 4),
    ('Dromadaire', 'dromadaire', 4),
    ('Drosophile', 'drosophile', 4),
    ('Dugong', 'dugong', 4),
    ('Durbec des sapins', 'durbec des sapins', 4),
    ('Dynaste Hercule', 'dynaste hercule', 4),
    ('Dysdère armée', 'dysdere armee', 4),
    ('Dègue', 'degue', 4),
    ('Déesse précieuse', 'deesse precieuse', 4),
    ('Echidné à nez court', 'echidne a nez court', 4),
    ('Ecureuil Géant d’Inde', 'ecureuil geant dinde', 4),
    ('Ecureuil de Barbarie', 'ecureuil de barbarie', 4),
    ('Ecureuil de Prévost', 'ecureuil de prevost', 4),
    ('Ecureuil du Yucatan', 'ecureuil du yucatan', 4),
    ('Ecureuil fouisseur du Cap', 'ecureuil fouisseur du cap', 4),
    ('Ecureuil gris', 'ecureuil gris', 4),
    ('Ecureuil roux', 'ecureuil roux', 4),
    ('Effraie', 'effraie', 4),
    ('Eider à duvet', 'eider a duvet', 4),
    ('Eider à lunettes', 'eider a lunettes', 4),
    ('Eider à tête grise', 'eider a tete grise', 4),
    ('Elan', 'elan', 4),
    ('Elan d’Eurasie', 'elan deurasie', 4),
    ('Eland de Derby', 'eland de derby', 4),
    ('Eland du Cap', 'eland du cap', 4),
    ('Elbot', 'elbot', 4),
    ('Elephant de mer', 'elephant de mer', 4),
    ('Elephant d’Afrique', 'elephant dafrique', 4),
    ('Elephant d’Asie', 'elephant dasie', 4),
    ('Eléphant de mer du Sud', 'elephant de mer du sud', 4),
    ('Eléphant d’Afrique', 'elephant dafrique', 4),
    ('Eléphant d’Asie', 'elephant dasie', 4),
    ('Emeu d’Australie', 'emeu daustralie', 4),
    ('Engoulevent', 'engoulevent', 4),
    ('Engoulevent de Caroline', 'engoulevent de caroline', 4),
    ('Engoulevent d’Europe', 'engoulevent deurope', 4),
    ('Entelle', 'entelle', 4),
    ('Entelle doré', 'entelle dore', 4),
    ('Entelle d’Hanuman', 'entelle dhanuman', 4),
    ('Epervier d’Europe', 'epervier deurope', 4),
    ('Erigoninae', 'erigoninae', 4),
    ('Escargot', 'escargot', 4),
    ('Escargot de mer', 'escargot de mer', 4),
    ('Escolier', 'escolier', 4),
    ('Espadon', 'espadon', 4),
    ('Esturgeon', 'esturgeon', 4),
    ('Etourneau améthyste', 'etourneau amethyste', 4),
    ('Etourneau sansonnet', 'etourneau sansonnet', 4),
    ('Euglossine', 'euglossine', 4),
    ('Eurasier', 'eurasier', 4),
    ('Eurylaime de Gould', 'eurylaime de gould', 4),
    ('Eyra', 'eyra', 4),
    ('Faisan', 'faisan', 4),
    ('Faisan de Colchide', 'faisan de colchide', 4),
    ('Faon', 'faon', 4),
    ('Faucheur', 'faucheur', 4),
    ('Faucheuse', 'faucheuse', 4),
    ('Faucheux', 'faucheux', 4),
    ('Faucon crécerelle', 'faucon crecerelle', 4),
    ('Faucon gerfaut', 'faucon gerfaut', 4),
    ('Faucon pèlerin', 'faucon pelerin', 4),
    ('Faucon pélerin', 'faucon pelerin', 4),
    ('Faucon émerillon', 'faucon emerillon', 4),
    ('Fausse tarentule', 'fausse tarentule', 4),
    ('Fauvette', 'fauvette', 4),
    ('Fauvette mélanocéphale', 'fauvette melanocephale', 4),
    ('Fauvette à tête noire', 'fauvette a tete noire', 4),
    ('Faux-corail de Sinaloa', 'faux-corail de sinaloa', 4),
    ('Faux-gavial d’Afrique', 'faux-gavial dafrique', 4),
    ('Fell', 'fell', 4),
    ('Fennec', 'fennec', 4),
    ('Fer de lance', 'fer de lance', 4),
    ('Fjord', 'fjord', 4),
    ('Flamant nain', 'flamant nain', 4),
    ('Flamant rose', 'flamant rose', 4),
    ('Flétan', 'fletan', 4),
    ('Fossa', 'fossa', 4),
    ('Fou de Bassan', 'fou de bassan', 4),
    ('Fou à pieds bleus', 'fou a pieds bleus', 4),
    ('Fouine', 'fouine', 4),
    ('Foulque', 'foulque', 4),
    ('Foulque d’Amérique', 'foulque damerique', 4),
    ('Foulque macroule', 'foulque macroule', 4),
    ('Fourmi', 'fourmi', 4),
    ('Fourmi balle de fusil', 'fourmi balle de fusil', 4),
    ('Fourmi de feu', 'fourmi de feu', 4),
    ('Fourmi ensanglantée', 'fourmi ensanglantee', 4),
    ('Fourmilier', 'fourmilier', 4),
    ('Fourmilier (tamanoir)', 'fourmilier (tamanoir)', 4),
    ('Fourmilion', 'fourmilion', 4),
    ('Frelon asiatique', 'frelon asiatique', 4),
    ('Frelon européen', 'frelon europeen', 4),
    ('Frelon géant japonais', 'frelon geant japonais', 4),
    ('Frison', 'frison', 4),
    ('Frégate', 'fregate', 4),
    ('Frégate superbe', 'fregate superbe', 4),
    ('Fuligule milouinan', 'fuligule milouinan', 4),
    ('Fuligule morillon', 'fuligule morillon', 4),
    ('Fuligule à collier', 'fuligule a collier', 4),
    ('Fuligule à dos blanc', 'fuligule a dos blanc', 4),
    ('Fuligule à tête rouge', 'fuligule a tete rouge', 4),
    ('Fulmar boréal', 'fulmar boreal', 4),
    ('Furet', 'furet', 4),
    ('Galago du Sénégal', 'galago du senegal', 4),
    ('Galinette', 'galinette', 4),
    ('Gallinule poule-d’eau', 'gallinule poule-deau', 4),
    ('Galogo', 'galogo', 4),
    ('Gambas', 'gambas', 4),
    ('Gardon', 'gardon', 4),
    ('Garrot d’Islande', 'garrot dislande', 4),
    ('Garrot à oeil d’or', 'garrot a oeil dor', 4),
    ('Gaufre', 'gaufre', 4),
    ('Gaur', 'gaur', 4),
    ('Gaur (Gayal)', 'gaur (gayal)', 4),
    ('Gavial', 'gavial', 4),
    ('Gayal', 'gayal', 4),
    ('Gazelle', 'gazelle', 4),
    ('Gazelle Dama', 'gazelle dama', 4),
    ('Gazelle Dorcas', 'gazelle dorcas', 4),
    ('Gazelle de Cuvier', 'gazelle de cuvier', 4),
    ('Gazelle de Grant', 'gazelle de grant', 4),
    ('Gazelle de Rhim', 'gazelle de rhim', 4),
    ('Gazelle de Sommering', 'gazelle de sommering', 4),
    ('Gazelle de Speke', 'gazelle de speke', 4),
    ('Gazelle de Thomson', 'gazelle de thomson', 4),
    ('Gazelle de Waller', 'gazelle de waller', 4),
    ('Gazelle de montagne', 'gazelle de montagne', 4),
    ('Gazelle indienne', 'gazelle indienne', 4),
    ('Gazelle à goître', 'gazelle a goitre', 4),
    ('Geai bleu', 'geai bleu', 4),
    ('Geai des chênes', 'geai des chenes', 4),
    ('Gecko', 'gecko', 4),
    ('Gecko du midi', 'gecko du midi', 4),
    ('Gecko géant de Madagascar', 'gecko geant de madagascar', 4),
    ('Gelada', 'gelada', 4),
    ('Gendarme', 'gendarme', 4),
    ('Genette', 'genette', 4),
    ('Genette commune', 'genette commune', 4),
    ('Gerbille', 'gerbille', 4),
    ('Gerboise', 'gerboise', 4),
    ('Gerenuk', 'gerenuk', 4),
    ('Gerris', 'gerris', 4),
    ('Gibbon', 'gibbon', 4),
    ('Gibbon Hoolock Occidental', 'gibbon hoolock occidental', 4),
    ('Gibbon agile', 'gibbon agile', 4),
    ('Gibbon cendré', 'gibbon cendre', 4),
    ('Gibbon de Hainan', 'gibbon de hainan', 4),
    ('Gibbon de Muller', 'gibbon de muller', 4),
    ('Gibbon lar', 'gibbon lar', 4),
    ('Gibbon noir', 'gibbon noir', 4),
    ('Gibbon à bonnet', 'gibbon a bonnet', 4),
    ('Gibbon à favoris blancs du Nord', 'gibbon a favoris blancs du nord', 4),
    ('Gibbon à joues jaunes', 'gibbon a joues jaunes', 4),
    ('Gibbon à mains blanches', 'gibbon a mains blanches', 4),
    ('Girafe', 'girafe', 4),
    ('Girelle', 'girelle', 4),
    ('Globicéphale noir', 'globicephale noir', 4),
    ('Glouton', 'glouton', 4),
    ('Gnou', 'gnou', 4),
    ('Gnou bleu', 'gnou bleu', 4),
    ('Gnou noir', 'gnou noir', 4),
    ('Gobe-mouche', 'gobe-mouche', 4),
    ('Gobemoucherons gris-bleu', 'gobemoucherons gris-bleu', 4),
    ('Goberge', 'goberge', 4),
    ('Gobie', 'gobie', 4),
    ('Goglu des prés', 'goglu des pres', 4),
    ('Golden retriever', 'golden retriever', 4),
    ('Goral de l’Himalaya', 'goral de lhimalaya', 4),
    ('Goral roux', 'goral roux', 4),
    ('Goral à longue queue', 'goral a longue queue', 4),
    ('Goret', 'goret', 4),
    ('Gorette', 'gorette', 4),
    ('Gorfou sauteur', 'gorfou sauteur', 4),
    ('Gorge bleue à miroir', 'gorge bleue a miroir', 4),
    ('Gorge-bleue à miroir', 'gorge-bleue a miroir', 4),
    ('Gorille', 'gorille', 4),
    ('Gorille de l’Est', 'gorille de lest', 4),
    ('Gorille de l’Ouest', 'gorille de louest', 4),
    ('Goujon', 'goujon', 4),
    ('Goundi', 'goundi', 4),
    ('Goundi de l’Atlas', 'goundi de latlas', 4),
    ('Goura couronné', 'goura couronne', 4),
    ('Goéland', 'goeland', 4),
    ('Goéland argenté', 'goeland argente', 4),
    ('Grage grands carreaux', 'grage grands carreaux', 4),
    ('Grand Danois', 'grand danois', 4),
    ('Grand Labbe', 'grand labbe', 4),
    ('Grand anaconda', 'grand anaconda', 4),
    ('Grand bharal', 'grand bharal', 4),
    ('Grand cachalot', 'grand cachalot', 4),
    ('Grand chevalier', 'grand chevalier', 4),
    ('Grand corbeau', 'grand corbeau', 4),
    ('Grand cormoran', 'grand cormoran', 4),
    ('Grand diable', 'grand diable', 4),
    ('Grand duc bruyant', 'grand duc bruyant', 4),
    ('Grand duc d’Amérique', 'grand duc damerique', 4),
    ('Grand duc indien', 'grand duc indien', 4),
    ('Grand harle', 'grand harle', 4),
    ('Grand koudou', 'grand koudou', 4),
    ('Grand pic', 'grand pic', 4),
    ('Grand requin blanc', 'grand requin blanc', 4),
    ('Grand requin marteau', 'grand requin marteau', 4),
    ('Grand tétras', 'grand tetras', 4),
    ('Grandala bleu', 'grandala bleu', 4),
    ('Grande aigrette', 'grande aigrette', 4),
    ('Grande aigrette (héron blanc)', 'grande aigrette (heron blanc)', 4),
    ('Grande sauterelle verte', 'grande sauterelle verte', 4),
    ('Grande vive', 'grande vive', 4),
    ('Grande-gueule', 'grande-gueule', 4),
    ('Grands carreaux', 'grands carreaux', 4),
    ('Graphosome d’Italie', 'graphosome ditalie', 4),
    ('Grenadier', 'grenadier', 4),
    ('Grenouille', 'grenouille', 4),
    ('Grenouille de Graf', 'grenouille de graf', 4),
    ('Grenouille des bois', 'grenouille des bois', 4),
    ('Grenouille des fraises', 'grenouille des fraises', 4),
    ('Grenouille fraise', 'grenouille fraise', 4),
    ('Grenouille léopard', 'grenouille leopard', 4),
    ('Grenouille rieuse', 'grenouille rieuse', 4),
    ('Grenouille rousse', 'grenouille rousse', 4),
    ('Grenouille taureau', 'grenouille taureau', 4),
    ('Grenouille verte', 'grenouille verte', 4),
    ('Grillon', 'grillon', 4),
    ('Grillon champêtre', 'grillon champetre', 4),
    ('Grimpereau brun', 'grimpereau brun', 4),
    ('Grimpereau des jardins', 'grimpereau des jardins', 4),
    ('Gris du Gabon', 'gris du gabon', 4),
    ('Gris d’Afrique', 'gris dafrique', 4),
    ('Grison', 'grison', 4),
    ('Grive', 'grive', 4),
    ('Grive musicienne', 'grive musicienne', 4),
    ('Grizzly', 'grizzly', 4),
    ('Groenendael', 'groenendael', 4),
    ('Groenlandais', 'groenlandais', 4),
    ('Grondin', 'grondin', 4),
    ('Gros-bec casse-noyaux', 'gros-bec casse-noyaux', 4),
    ('Grosbec casse-noyaux', 'grosbec casse-noyaux', 4),
    ('Grue', 'grue', 4),
    ('Grue Antigone', 'grue antigone', 4),
    ('Grue Caronculée', 'grue caronculee', 4),
    ('Grue Couronnée', 'grue couronnee', 4),
    ('Grue cendrée', 'grue cendree', 4),
    ('Grue du Japon', 'grue du japon', 4),
    ('Grèbe', 'grebe', 4),
    ('Grèbe huppé', 'grebe huppe', 4),
    ('Grémille', 'gremille', 4),
    ('Guanaco', 'guanaco', 4),
    ('Guib harnaché', 'guib harnache', 4),
    ('Guifette noire', 'guifette noire', 4),
    ('Guigna', 'guigna', 4),
    ('Guillemot', 'guillemot', 4),
    ('Guira cantara', 'guira cantara', 4),
    ('Guiraca bleu', 'guiraca bleu', 4),
    ('Guppy', 'guppy', 4),
    ('Guépard', 'guepard', 4),
    ('Guépard d’Afrique', 'guepard dafrique', 4),
    ('Guépard d’Asie', 'guepard dasie', 4),
    ('Guéréza', 'guereza', 4),
    ('Guêpe', 'guepe', 4),
    ('Guêpe commune', 'guepe commune', 4),
    ('Guêpe germanique', 'guepe germanique', 4),
    ('Guêpier d’Europe', 'guepier deurope', 4),
    ('Gymnote', 'gymnote', 4),
    ('Gypaète barbu', 'gypaete barbu', 4),
    ('Géant des Flandres', 'geant des flandres', 4),
    ('Gélinotte', 'gelinotte', 4),
    ('Habu', 'habu', 4),
    ('Haflinger', 'haflinger', 4),
    ('Hamadryas', 'hamadryas', 4),
    ('Hamster', 'hamster', 4),
    ('Hamster d’Europe', 'hamster deurope', 4),
    ('Hanneton', 'hanneton', 4),
    ('Harelde kakawi', 'harelde kakawi', 4),
    ('Hareng', 'hareng', 4),
    ('Harfang des neiges', 'harfang des neiges', 4),
    ('Harle couronné', 'harle couronne', 4),
    ('Harle huppé', 'harle huppe', 4),
    ('Harpie', 'harpie', 4),
    ('Harpie féroce', 'harpie feroce', 4),
    ('Henson', 'henson', 4),
    ('Hercule', 'hercule', 4),
    ('Hermine', 'hermine', 4),
    ('Hibou', 'hibou', 4),
    ('Hibou Grand-duc d’Europe', 'hibou grand-duc deurope', 4),
    ('Hibou grand-duc', 'hibou grand-duc', 4),
    ('Hibou moyen-duc', 'hibou moyen-duc', 4),
    ('Hippocampe', 'hippocampe', 4),
    ('Hippopotame', 'hippopotame', 4),
    ('Hippopotame commun', 'hippopotame commun', 4),
    ('Hippotrague noir', 'hippotrague noir', 4),
    ('Hirondelle', 'hirondelle', 4),
    ('Hirondelle bicolore', 'hirondelle bicolore', 4),
    ('Hirondelle rustique', 'hirondelle rustique', 4),
    ('Hoazin hupée', 'hoazin hupee', 4),
    ('Hocco nocturne', 'hocco nocturne', 4),
    ('Hocheur', 'hocheur', 4),
    ('Hogna rayée', 'hogna rayee', 4),
    ('Homard', 'homard', 4),
    ('Hotu', 'hotu', 4),
    ('Houlock', 'houlock', 4),
    ('Huchon', 'huchon', 4),
    ('Huitre', 'huitre', 4),
    ('Hulotte', 'hulotte', 4),
    ('Hupolaïs polyglotte', 'hupolais polyglotte', 4),
    ('Huppe', 'huppe', 4),
    ('Huppe fasciée', 'huppe fasciee', 4),
    ('Husky', 'husky', 4),
    ('Hutia', 'hutia', 4),
    ('Huîtrier-pie', 'huitrier-pie', 4),
    ('Hydrochère', 'hydrochere', 4),
    ('Hydropote', 'hydropote', 4),
    ('Hylochère', 'hylochere', 4),
    ('Hypolaïs fasciée', 'hypolais fasciee', 4),
    ('Hypsosinga', 'hypsosinga', 4),
    ('Hyène', 'hyene', 4),
    ('Hyène brune', 'hyene brune', 4),
    ('Hyène rayée', 'hyene rayee', 4),
    ('Hyène tachetée', 'hyene tachetee', 4),
    ('Hyène tâchetée', 'hyene tachetee', 4),
    ('Hémione', 'hemione', 4),
    ('Hérisson', 'herisson', 4),
    ('Hérisson commun', 'herisson commun', 4),
    ('Héron', 'heron', 4),
    ('Héron cendré', 'heron cendre', 4),
    ('Héron garde-boeufs', 'heron garde-boeufs', 4),
    ('Héron vert', 'heron vert', 4),
    ('Ibijau gris', 'ibijau gris', 4),
    ('Ibis', 'ibis', 4),
    ('Ibis blanc', 'ibis blanc', 4),
    ('Ibis falcinelle', 'ibis falcinelle', 4),
    ('Ibis rouge', 'ibis rouge', 4),
    ('Ibis sacré', 'ibis sacre', 4),
    ('Ide mélanote', 'ide melanote', 4),
    ('Iguane', 'iguane', 4),
    ('Iguane marin', 'iguane marin', 4),
    ('Iguane rhinocéros', 'iguane rhinoceros', 4),
    ('Iguane rose', 'iguane rose', 4),
    ('Iguane vert', 'iguane vert', 4),
    ('Ili pika', 'ili pika', 4),
    ('Impala', 'impala', 4),
    ('Indri', 'indri', 4),
    ('Inséparable', 'inseparable', 4),
    ('Isard', 'isard', 4),
    ('Isatis', 'isatis', 4),
    ('Isopode', 'isopode', 4),
    ('Jabiru d’Afrique', 'jabiru dafrique', 4),
    ('Jabiru d’Amérique', 'jabiru damerique', 4),
    ('Jacamar à queue rousse', 'jacamar a queue rousse', 4),
    ('Jacara', 'jacara', 4),
    ('Jack Russell Terrier', 'jack russell terrier', 4),
    ('Jaguar', 'jaguar', 4),
    ('Jaguarondi', 'jaguarondi', 4),
    ('Jararaca', 'jararaca', 4),
    ('Jaseur boréal', 'jaseur boreal', 4),
    ('Jaseur d’Amérique', 'jaseur damerique', 4),
    ('Julienne', 'julienne', 4),
    ('Junco ardoisé', 'junco ardoise', 4),
    ('Jutia', 'jutia', 4),
    ('Kakapo', 'kakapo', 4),
    ('Kangourou', 'kangourou', 4),
    ('Kangourou arboricole', 'kangourou arboricole', 4),
    ('Kangourou roux', 'kangourou roux', 4),
    ('Katuali', 'katuali', 4),
    ('Kiwi', 'kiwi', 4),
    ('Kiwi austral', 'kiwi austral', 4),
    ('Koala', 'koala', 4),
    ('Kodiak', 'kodiak', 4),
    ('Kodkod', 'kodkod', 4),
    ('Kokoï de Colombie', 'kokoi de colombie', 4),
    ('Komondor', 'komondor', 4),
    ('Konik polski', 'konik polski', 4),
    ('Kookaburra', 'kookaburra', 4),
    ('Kookaburra à ailes bleues', 'kookaburra a ailes bleues', 4),
    ('Koudou', 'koudou', 4),
    ('Kravat', 'kravat', 4),
    ('Labbe parasite', 'labbe parasite', 4),
    ('Labbe à longue queue', 'labbe a longue queue', 4),
    ('Labrador retriever', 'labrador retriever', 4),
    ('Labre', 'labre', 4),
    ('Laekenois', 'laekenois', 4),
    ('Lagopède', 'lagopede', 4),
    ('Lagopède alpin', 'lagopede alpin', 4),
    ('Lagotriche', 'lagotriche', 4),
    ('Lama', 'lama', 4),
    ('Lamantin', 'lamantin', 4),
    ('Lamantin des Caraïbes', 'lamantin des caraibes', 4),
    ('Lamproie', 'lamproie', 4),
    ('Langouste', 'langouste', 4),
    ('Langoustine', 'langoustine', 4),
    ('Langur', 'langur', 4),
    ('Langur de Delacour', 'langur de delacour', 4),
    ('Langur de Java', 'langur de java', 4),
    ('Langur sacré', 'langur sacre', 4),
    ('Langur à capuchon', 'langur a capuchon', 4),
    ('Lançon', 'lancon', 4),
    ('Lapin', 'lapin', 4),
    ('Lapin de garenne', 'lapin de garenne', 4),
    ('Larinioides', 'larinioides', 4),
    ('Lemming', 'lemming', 4),
    ('Lemming commun', 'lemming commun', 4),
    ('Leonberg', 'leonberg', 4),
    ('Leptophye ponctuée', 'leptophye ponctuee', 4),
    ('Lepture cordigère', 'lepture cordigere', 4),
    ('Leste fiancé', 'leste fiance', 4),
    ('Libellule', 'libellule', 4),
    ('Libellule dépressive', 'libellule depressive', 4),
    ('Liche', 'liche', 4),
    ('Lieu', 'lieu', 4),
    ('Lieu jaune', 'lieu jaune', 4),
    ('Lieu noir', 'lieu noir', 4),
    ('Limace', 'limace', 4),
    ('Limace de mer', 'limace de mer', 4),
    ('Limande', 'limande', 4),
    ('Lingue', 'lingue', 4),
    ('Linotte', 'linotte', 4),
    ('Linotte mélodieuse', 'linotte melodieuse', 4),
    ('Lion', 'lion', 4),
    ('Lion blanc', 'lion blanc', 4),
    ('Lion de mer de Californie', 'lion de mer de californie', 4),
    ('Lion d’Afrique', 'lion dafrique', 4),
    ('Lion d’Asie', 'lion dasie', 4),
    ('Lipizzan', 'lipizzan', 4),
    ('Lièvre', 'lievre', 4),
    ('Lièvre de Patagonie', 'lievre de patagonie', 4),
    ('Lièvre de mer', 'lievre de mer', 4),
    ('Lièvre d’Europe', 'lievre deurope', 4),
    ('Lièvre sauteur', 'lievre sauteur', 4),
    ('Loche', 'loche', 4),
    ('Locustelle tachetée', 'locustelle tachetee', 4),
    ('Loir', 'loir', 4),
    ('Loir gris', 'loir gris', 4),
    ('Lompe', 'lompe', 4),
    ('Lophophore', 'lophophore', 4),
    ('Lorette', 'lorette', 4),
    ('Lori', 'lori', 4),
    ('Loriot', 'loriot', 4),
    ('Loriot d’Europe', 'loriot deurope', 4),
    ('Loriquet à tête bleu', 'loriquet a tete bleu', 4),
    ('Loris', 'loris', 4),
    ('Lotte', 'lotte', 4),
    ('Loubine', 'loubine', 4),
    ('Loup', 'loup', 4),
    ('Loup Ibérique', 'loup iberique', 4),
    ('Loup arctique', 'loup arctique', 4),
    ('Loup de Mongolie', 'loup de mongolie', 4),
    ('Loup de Sibérie', 'loup de siberie', 4),
    ('Loup de l’Est', 'loup de lest', 4),
    ('Loup de mer', 'loup de mer', 4),
    ('Loup des Indes', 'loup des indes', 4),
    ('Loup du Mexique', 'loup du mexique', 4),
    ('Loup d’Abyssinie', 'loup dabyssinie', 4),
    ('Loup gris', 'loup gris', 4),
    ('Loup gris commun', 'loup gris commun', 4),
    ('Loup rouge', 'loup rouge', 4),
    ('Loup à crinière', 'loup a criniere', 4),
    ('Loutre', 'loutre', 4),
    ('Loutre de mer', 'loutre de mer', 4),
    ('Loutre d’Europe', 'loutre deurope', 4),
    ('Lucane cerf-volant', 'lucane cerf-volant', 4),
    ('Lucilie bouchère', 'lucilie bouchere', 4),
    ('Lucilie bufonivore', 'lucilie bufonivore', 4),
    ('Luciole', 'luciole', 4),
    ('Lusciniolle à moustache', 'lusciniolle a moustache', 4),
    ('Lycaon', 'lycaon', 4),
    ('Lycaons', 'lycaons', 4),
    ('Lycose', 'lycose', 4),
    ('Lyctus', 'lyctus', 4),
    ('Lynx', 'lynx', 4),
    ('Lynx boréal', 'lynx boreal', 4),
    ('Lynx du désert', 'lynx du desert', 4),
    ('Lynx roux', 'lynx roux', 4),
    ('Lémur couronné', 'lemur couronne', 4),
    ('Lémurien', 'lemurien', 4),
    ('Léopard', 'leopard', 4),
    ('Léopard des mers', 'leopard des mers', 4),
    ('Léopard des neiges', 'leopard des neiges', 4),
    ('Léopard d’Afrique', 'leopard dafrique', 4),
    ('Lépilémur', 'lepilemur', 4),
    ('Lérot', 'lerot', 4),
    ('Lérotin', 'lerotin', 4),
    ('Léthocère d’Amérique', 'lethocere damerique', 4),
    ('Lévrier Afghan', 'levrier afghan', 4),
    ('Lévrier Persan', 'levrier persan', 4),
    ('Lévrier Russe', 'levrier russe', 4),
    ('Lézard', 'lezard', 4),
    ('Lézard Jésus', 'lezard jesus', 4),
    ('Lézard à collerette', 'lezard a collerette', 4),
    ('Lézard à collier', 'lezard a collier', 4),
    ('Macagua', 'macagua', 4),
    ('Macaque', 'macaque', 4),
    ('Macaque berbère', 'macaque berbere', 4),
    ('Macaque commun', 'macaque commun', 4),
    ('Macaque de barbarie', 'macaque de barbarie', 4),
    ('Macaque à queue de lion', 'macaque a queue de lion', 4),
    ('Macareux', 'macareux', 4),
    ('Macareux moine', 'macareux moine', 4),
    ('Machaon', 'machaon', 4),
    ('Macreuse brune', 'macreuse brune', 4),
    ('Macreuse noire', 'macreuse noire', 4),
    ('Magicienne dentelée', 'magicienne dentelee', 4),
    ('Magot', 'magot', 4),
    ('Maigre', 'maigre', 4),
    ('Main Coon', 'main coon', 4),
    ('Mainate', 'mainate', 4),
    ('Makaire', 'makaire', 4),
    ('Maki catta', 'maki catta', 4),
    ('Maki vari noir et blanc', 'maki vari noir et blanc', 4),
    ('Maki vari roux', 'maki vari roux', 4),
    ('Malachigan', 'malachigan', 4),
    ('Malamute', 'malamute', 4),
    ('Malinois', 'malinois', 4),
    ('Mamba noir', 'mamba noir', 4),
    ('Mamba vert', 'mamba vert', 4),
    ('Mammouth', 'mammouth', 4),
    ('Mammouth laineux', 'mammouth laineux', 4),
    ('Manakin de Bokermann', 'manakin de bokermann', 4),
    ('Manchot', 'manchot', 4),
    ('Manchot empereur', 'manchot empereur', 4),
    ('Mandarin', 'mandarin', 4),
    ('Mandole', 'mandole', 4),
    ('Mandrill', 'mandrill', 4),
    ('Mangabey', 'mangabey', 4),
    ('Mangabey couronné', 'mangabey couronne', 4),
    ('Mangabey noir', 'mangabey noir', 4),
    ('Mangore petite-bouteille', 'mangore petite-bouteille', 4),
    ('Mangouste', 'mangouste', 4),
    ('Mangouste ichneumon', 'mangouste ichneumon', 4),
    ('Mangouste jaune', 'mangouste jaune', 4),
    ('Mangouste rouge', 'mangouste rouge', 4),
    ('Mangouste à queue blanche', 'mangouste a queue blanche', 4),
    ('Mante orchidée', 'mante orchidee', 4),
    ('Mante religieuse', 'mante religieuse', 4),
    ('Manul', 'manul', 4),
    ('Mapanare', 'mapanare', 4),
    ('Maquereau', 'maquereau', 4),
    ('Mara', 'mara', 4),
    ('Mara de Patagonie', 'mara de patagonie', 4),
    ('Marabout', 'marabout', 4),
    ('Marabout d’Afrique', 'marabout dafrique', 4),
    ('Maraîche', 'maraiche', 4),
    ('Marbré', 'marbre', 4),
    ('Margay', 'margay', 4),
    ('Margouillat', 'margouillat', 4),
    ('Marigane noire', 'marigane noire', 4),
    ('Maringouin', 'maringouin', 4),
    ('Markhor', 'markhor', 4),
    ('Marlin', 'marlin', 4),
    ('Marmotte', 'marmotte', 4),
    ('Marmotte des Alpes', 'marmotte des alpes', 4),
    ('Marmousset', 'marmousset', 4),
    ('Marouette de Caroline', 'marouette de caroline', 4),
    ('Marsouin', 'marsouin', 4),
    ('Marsouin commun', 'marsouin commun', 4),
    ('Martin chasseur à ailes bleues', 'martin chasseur a ailes bleues', 4),
    ('Martin chasseur à collier blanc', 'martin chasseur a collier blanc', 4),
    ('Martin pêcheur', 'martin pecheur', 4),
    ('Martin pêcheur d’Europe', 'martin pecheur deurope', 4),
    ('Martin pêcheur vert', 'martin pecheur vert', 4),
    ('Martinet', 'martinet', 4),
    ('Martinet noir', 'martinet noir', 4),
    ('Martinet à ventre blanc', 'martinet a ventre blanc', 4),
    ('Martre', 'martre', 4),
    ('Martre des pins', 'martre des pins', 4),
    ('Martre à gorge jaune', 'martre a gorge jaune', 4),
    ('Mau egyptien', 'mau egyptien', 4),
    ('Maubèche des champs', 'maubeche des champs', 4),
    ('Maître de la brousse', 'maitre de la brousse', 4),
    ('Merlan', 'merlan', 4),
    ('Merle', 'merle', 4),
    ('Merle d’Amérique', 'merle damerique', 4),
    ('Merle noir', 'merle noir', 4),
    ('Merle à plastron', 'merle a plastron', 4),
    ('Merlebleu azuré', 'merlebleu azure', 4),
    ('Merlebleu de l’Est', 'merlebleu de lest', 4),
    ('Merlu', 'merlu', 4),
    ('Merluche', 'merluche', 4),
    ('Messager sagittaire', 'messager sagittaire', 4),
    ('Meunier', 'meunier', 4),
    ('Microcèbe', 'microcebe', 4),
    ('Milan', 'milan', 4),
    ('Milan noir', 'milan noir', 4),
    ('Milan royal', 'milan royal', 4),
    ('Miopithèque', 'miopitheque', 4),
    ('Mirandelle', 'mirandelle', 4),
    ('Miro incarnat', 'miro incarnat', 4),
    ('Mite', 'mite', 4),
    ('Mocassin d’eau', 'mocassin deau', 4),
    ('Moineau', 'moineau', 4),
    ('Moineau domestique', 'moineau domestique', 4),
    ('Moloch', 'moloch', 4),
    ('Monarque', 'monarque', 4),
    ('Montagne des Pyrénées', 'montagne des pyrenees', 4),
    ('Moqueur chat', 'moqueur chat', 4),
    ('Moqueur polyglotte', 'moqueur polyglotte', 4),
    ('Moqueur roux', 'moqueur roux', 4),
    ('Mora', 'mora', 4),
    ('Moro sphinx', 'moro sphinx', 4),
    ('Morse', 'morse', 4),
    ('Morue', 'morue', 4),
    ('Motelle', 'motelle', 4),
    ('Motmot', 'motmot', 4),
    ('Mouche', 'mouche', 4),
    ('Mouche du vinaigre', 'mouche du vinaigre', 4),
    ('Mouche tsé-tsé', 'mouche tse-tse', 4),
    ('Mouche verte', 'mouche verte', 4),
    ('Mouche à damier', 'mouche a damier', 4),
    ('Moucherolle phébi', 'moucherolle phebi', 4),
    ('Moucherolle royal', 'moucherolle royal', 4),
    ('Moucherolle à ventre Jaune', 'moucherolle a ventre jaune', 4),
    ('Moucheron', 'moucheron', 4),
    ('Mouette', 'mouette', 4),
    ('Moufette', 'moufette', 4),
    ('Mouffette rayée', 'mouffette rayee', 4),
    ('Mouffette tachetée', 'mouffette tachetee', 4),
    ('Mouflon', 'mouflon', 4),
    ('Moule', 'moule', 4),
    ('Moustac', 'moustac', 4),
    ('Moustique', 'moustique', 4),
    ('Moustique tigre', 'moustique tigre', 4),
    ('Mouton', 'mouton', 4),
    ('Mouton cheviot', 'mouton cheviot', 4),
    ('Moyen-Duc', 'moyen-duc', 4),
    ('Muge', 'muge', 4),
    ('Mule', 'mule', 4),
    ('Mulet', 'mulet', 4),
    ('Mulot', 'mulot', 4),
    ('Mulot sylvestre', 'mulot sylvestre', 4),
    ('Munchkin', 'munchkin', 4),
    ('Muntjac de Reeves', 'muntjac de reeves', 4),
    ('Murène', 'murene', 4),
    ('Musaraigne', 'musaraigne', 4),
    ('Musaraigne carrelet (commune)', 'musaraigne carrelet (commune)', 4),
    ('Muscardin', 'muscardin', 4),
    ('Mustang', 'mustang', 4),
    ('Mygale', 'mygale', 4),
    ('Mygale de Leblond', 'mygale de leblond', 4),
    ('Mygale naine tigrée', 'mygale naine tigree', 4),
    ('Myrmidon', 'myrmidon', 4),
    ('Mâchoiron', 'machoiron', 4),
    ('Mâtin de Naples', 'matin de naples', 4),
    ('Méduse', 'meduse', 4),
    ('Mélipone', 'melipone', 4),
    ('Ménomini rond', 'menomini rond', 4),
    ('Mérou', 'merou', 4),
    ('Mésange', 'mesange', 4),
    ('Mésange bleue', 'mesange bleue', 4),
    ('Mésange charbonnière', 'mesange charbonniere', 4),
    ('Mésange huppée', 'mesange huppee', 4),
    ('Mésange hupée', 'mesange hupee', 4),
    ('Mésange noire', 'mesange noire', 4),
    ('Mésange nonnette', 'mesange nonnette', 4),
    ('Mésange à longue queue', 'mesange a longue queue', 4),
    ('Môle', 'mole', 4),
    ('Nandinie', 'nandinie', 4),
    ('Nandou', 'nandou', 4),
    ('Nandou de Darwin', 'nandou de darwin', 4),
    ('Napoléon', 'napoleon', 4),
    ('Narval', 'narval', 4),
    ('Nasique', 'nasique', 4),
    ('Nasique des îles de Pagai', 'nasique des iles de pagai', 4),
    ('Nason', 'nason', 4),
    ('Nautile', 'nautile', 4),
    ('Nebelung', 'nebelung', 4),
    ('Nestor kéa', 'nestor kea', 4),
    ('Nette rousse', 'nette rousse', 4),
    ('Neuroptère', 'neuroptere', 4),
    ('Nicator à gorge grise', 'nicator a gorge grise', 4),
    ('Nicobar à camail', 'nicobar a camail', 4),
    ('Nilgaut', 'nilgaut', 4),
    ('Niverolle alpine', 'niverolle alpine', 4),
    ('Noctuelle potagère', 'noctuelle potagere', 4),
    ('Noctule', 'noctule', 4),
    ('Noctule commune', 'noctule commune', 4),
    ('Noddi brun', 'noddi brun', 4),
    ('Norvégien', 'norvegien', 4),
    ('Nothocrax nocturne', 'nothocrax nocturne', 4),
    ('Notou', 'notou', 4),
    ('Numbat', 'numbat', 4),
    ('Nyala', 'nyala', 4),
    ('Nyala de montagne', 'nyala de montagne', 4),
    ('Nyctale de Tengmalm', 'nyctale de tengmalm', 4),
    ('Nèpe', 'nepe', 4),
    ('Néphile dorée', 'nephile doree', 4),
    ('Oblade', 'oblade', 4),
    ('Ocelot', 'ocelot', 4),
    ('Octodon', 'octodon', 4),
    ('Octopode', 'octopode', 4),
    ('Oie', 'oie', 4),
    ('Oie blanche', 'oie blanche', 4),
    ('Oie cendrée', 'oie cendree', 4),
    ('Oie de Ross', 'oie de ross', 4),
    ('Oie rieuse', 'oie rieuse', 4),
    ('Oie à bec court', 'oie a bec court', 4),
    ('Okapi', 'okapi', 4),
    ('Olinguito', 'olinguito', 4),
    ('Olm', 'olm', 4),
    ('Omble chevalier', 'omble chevalier', 4),
    ('Ombre', 'ombre', 4),
    ('Ombrette africaine', 'ombrette africaine', 4),
    ('Onagre', 'onagre', 4),
    ('Once', 'once', 4),
    ('Ondatra', 'ondatra', 4),
    ('Opah', 'opah', 4),
    ('Opossum', 'opossum', 4),
    ('Orang outan', 'orang outan', 4),
    ('Orang-outan de Bornéo', 'orang-outan de borneo', 4),
    ('Orang-outan de Sumatra', 'orang-outan de sumatra', 4),
    ('Orignal', 'orignal', 4),
    ('Oriole de Baltimore', 'oriole de baltimore', 4),
    ('Ornithorynque', 'ornithorynque', 4),
    ('Orque', 'orque', 4),
    ('Orvet commun (fragile)', 'orvet commun (fragile)', 4),
    ('Orvet de Vérone', 'orvet de verone', 4),
    ('Orvet fragile', 'orvet fragile', 4),
    ('Oryctérope', 'orycterope', 4),
    ('Oryctérope du Cap', 'orycterope du cap', 4),
    ('Oryx', 'oryx', 4),
    ('Oryx Beisa (d’Afrique de l’Est)', 'oryx beisa (dafrique de lest)', 4),
    ('Oryx algazelle', 'oryx algazelle', 4),
    ('Oryx algazelle (blanc)', 'oryx algazelle (blanc)', 4),
    ('Oryx d’Arabie', 'oryx darabie', 4),
    ('Oryx gazelle', 'oryx gazelle', 4),
    ('Osmie cornue', 'osmie cornue', 4),
    ('Otarie', 'otarie', 4),
    ('Otarie de Californie', 'otarie de californie', 4),
    ('Otarie de Kerguelen', 'otarie de kerguelen', 4),
    ('Otarie des Galapagos', 'otarie des galapagos', 4),
    ('Otocyon', 'otocyon', 4),
    ('Ouakari', 'ouakari', 4),
    ('Ouakari chauve', 'ouakari chauve', 4),
    ('Ouananiche', 'ouananiche', 4),
    ('Ouandérou', 'ouanderou', 4),
    ('Ouaouaron', 'ouaouaron', 4),
    ('Ouistiti', 'ouistiti', 4),
    ('Ouistiti argenté', 'ouistiti argente', 4),
    ('Ouistiti pygmée', 'ouistiti pygmee', 4),
    ('Ouistiti à toupets blancs', 'ouistiti a toupets blancs', 4),
    ('Ours', 'ours', 4),
    ('Ours brun', 'ours brun', 4),
    ('Ours esprit', 'ours esprit', 4),
    ('Ours kodiak', 'ours kodiak', 4),
    ('Ours lippu', 'ours lippu', 4),
    ('Ours malais', 'ours malais', 4),
    ('Ours noir', 'ours noir', 4),
    ('Ours polaire', 'ours polaire', 4),
    ('Ours à collier', 'ours a collier', 4),
    ('Ours à lunettes', 'ours a lunettes', 4),
    ('Oursin', 'oursin', 4),
    ('Ourébi', 'ourebi', 4),
    ('Outarde canepetière', 'outarde canepetiere', 4),
    ('Paca', 'paca', 4),
    ('Pacarana', 'pacarana', 4),
    ('Pageot', 'pageot', 4),
    ('Pagre', 'pagre', 4),
    ('Palombe', 'palombe', 4),
    ('Palourde', 'palourde', 4),
    ('Panda', 'panda', 4),
    ('Panda géant', 'panda geant', 4),
    ('Panda roux', 'panda roux', 4),
    ('Panga', 'panga', 4),
    ('Pangolin', 'pangolin', 4),
    ('Pangolin Géant', 'pangolin geant', 4),
    ('Pangolin de Chine', 'pangolin de chine', 4),
    ('Pangolin géant', 'pangolin geant', 4),
    ('Panthere de Ceylan', 'panthere de ceylan', 4),
    ('Panthère', 'panthere', 4),
    ('Panthère de l’Amour', 'panthere de lamour', 4),
    ('Panthère longibande', 'panthere longibande', 4),
    ('Panthère nébuleuse', 'panthere nebuleuse', 4),
    ('Panure à moustaches', 'panure a moustaches', 4),
    ('Paon', 'paon', 4),
    ('Paon bleu', 'paon bleu', 4),
    ('Paon du jour', 'paon du jour', 4),
    ('Papillon', 'papillon', 4),
    ('Papillon chouette', 'papillon chouette', 4),
    ('Papillon du palmier', 'papillon du palmier', 4),
    ('Paresseux', 'paresseux', 4),
    ('Paresseux à 2 doigts (unau)', 'paresseux a 2 doigts (unau)', 4),
    ('Paresseux à deux doigts', 'paresseux a deux doigts', 4),
    ('Paresseux à gorge brune', 'paresseux a gorge brune', 4),
    ('Paruline', 'paruline', 4),
    ('Paruline jaune', 'paruline jaune', 4),
    ('Passerin indigo', 'passerin indigo', 4),
    ('Passerin nonpareil', 'passerin nonpareil', 4),
    ('Pataclet', 'pataclet', 4),
    ('Patas', 'patas', 4),
    ('Patelle', 'patelle', 4),
    ('Perce oreille', 'perce oreille', 4),
    ('Perchaude', 'perchaude', 4),
    ('Perche', 'perche', 4),
    ('Perche du Nil', 'perche du nil', 4),
    ('Percheron', 'percheron', 4),
    ('Perdrix', 'perdrix', 4),
    ('Perdrix grise', 'perdrix grise', 4),
    ('Perdrix rouge', 'perdrix rouge', 4),
    ('Perle', 'perle', 4),
    ('Perruche', 'perruche', 4),
    ('Perruche ondulée', 'perruche ondulee', 4),
    ('Perruche à collier', 'perruche a collier', 4),
    ('Persan', 'persan', 4),
    ('Petit Bharal', 'petit bharal', 4),
    ('Petit Koudou', 'petit koudou', 4),
    ('Petit blongios', 'petit blongios', 4),
    ('Petit capricorne', 'petit capricorne', 4),
    ('Petit chevalier', 'petit chevalier', 4),
    ('Petit diable', 'petit diable', 4),
    ('Petit duc maculé', 'petit duc macule', 4),
    ('Petit fuligule', 'petit fuligule', 4),
    ('Petit garrot', 'petit garrot', 4),
    ('Petit-duc scops (Hibou petit-duc)', 'petit-duc scops (hibou petit-duc)', 4),
    ('Petite buse', 'petite buse', 4),
    ('Petite nyctale', 'petite nyctale', 4),
    ('Petite vive', 'petite vive', 4),
    ('Petrogale', 'petrogale', 4),
    ('Phacochère', 'phacochere', 4),
    ('Phacochère commun', 'phacochere commun', 4),
    ('Phalarope de Wilson', 'phalarope de wilson', 4),
    ('Phalarope à bec étroit', 'phalarope a bec etroit', 4),
    ('Phaner', 'phaner', 4),
    ('Phasme', 'phasme', 4),
    ('Phasme bâton', 'phasme baton', 4),
    ('Phasme scorpion', 'phasme scorpion', 4),
    ('Phidippus', 'phidippus', 4),
    ('Pholque', 'pholque', 4),
    ('Pholque phalangide', 'pholque phalangide', 4),
    ('Phoque', 'phoque', 4),
    ('Phoque veau marin', 'phoque veau marin', 4),
    ('Phoque à capuchon', 'phoque a capuchon', 4),
    ('Phrygane', 'phrygane', 4),
    ('Phrynorhombe', 'phrynorhombe', 4),
    ('Phyllie', 'phyllie', 4),
    ('Pic', 'pic', 4),
    ('Pic chevelu', 'pic chevelu', 4),
    ('Pic flamboyant', 'pic flamboyant', 4),
    ('Pic maculé', 'pic macule', 4),
    ('Pic mineur', 'pic mineur', 4),
    ('Pic vert', 'pic vert', 4),
    ('Pic à dos noir', 'pic a dos noir', 4),
    ('Pic à tête rouge', 'pic a tete rouge', 4),
    ('Pic à ventre roux', 'pic a ventre roux', 4),
    ('Pic épeiche', 'pic epeiche', 4),
    ('Pie bavarde', 'pie bavarde', 4),
    ('Pie d’Amérique', 'pie damerique', 4),
    ('Pie grièche', 'pie grieche', 4),
    ('Pie grièche migratrice', 'pie grieche migratrice', 4),
    ('Pie-grièche grise', 'pie-grieche grise', 4),
    ('Pieuvre', 'pieuvre', 4),
    ('Pigeon', 'pigeon', 4),
    ('Pigeon ramier', 'pigeon ramier', 4),
    ('Pika', 'pika', 4),
    ('Pilandok', 'pilandok', 4),
    ('Pinché', 'pinche', 4),
    ('Pinché à crête blanche', 'pinche a crete blanche', 4),
    ('Pingouin', 'pingouin', 4),
    ('Pingouin torda', 'pingouin torda', 4),
    ('Pinson des arbres', 'pinson des arbres', 4),
    ('Pintade', 'pintade', 4),
    ('Pintade vulturine', 'pintade vulturine', 4),
    ('Pioui de l’Est', 'pioui de lest', 4),
    ('Pipistrelle', 'pipistrelle', 4),
    ('Pipit d’Amérique', 'pipit damerique', 4),
    ('Piranga vermillon', 'piranga vermillon', 4),
    ('Piranga à tête rouge', 'piranga a tete rouge', 4),
    ('Piranga écarlate', 'piranga ecarlate', 4),
    ('Piranha', 'piranha', 4),
    ('Pirolle de TaÏwan', 'pirolle de taiwan', 4),
    ('Pirolle verte', 'pirolle verte', 4),
    ('Pisaure admirable', 'pisaure admirable', 4),
    ('Pièride du chou', 'pieride du chou', 4),
    ('Plature', 'plature', 4),
    ('Plectrophane des neiges', 'plectrophane des neiges', 4),
    ('Plectrophane lapon', 'plectrophane lapon', 4),
    ('Plie', 'plie', 4),
    ('Plongeon catmarin', 'plongeon catmarin', 4),
    ('Plongeon huard', 'plongeon huard', 4),
    ('Pluvier', 'pluvier', 4),
    ('Podarge de Ceylan', 'podarge de ceylan', 4),
    ('Pogona', 'pogona', 4),
    ('Poisson', 'poisson', 4),
    ('Poisson clown', 'poisson clown', 4),
    ('Poisson d’argent', 'poisson dargent', 4),
    ('Poisson lanterne', 'poisson lanterne', 4),
    ('Poisson-chat', 'poisson-chat', 4),
    ('Poisson-chien', 'poisson-chien', 4),
    ('Poisson-clown', 'poisson-clown', 4),
    ('Poisson-coffre', 'poisson-coffre', 4),
    ('Poisson-licorne', 'poisson-licorne', 4),
    ('Poisson-lune', 'poisson-lune', 4),
    ('Poisson-pilote', 'poisson-pilote', 4),
    ('Poisson-rouge', 'poisson-rouge', 4),
    ('Poisson-scie', 'poisson-scie', 4),
    ('Poisson-zèbre', 'poisson-zebre', 4),
    ('Polatouche', 'polatouche', 4),
    ('Polatouche de Sibérie', 'polatouche de siberie', 4),
    ('Poliste', 'poliste', 4),
    ('Poliste géant', 'poliste geant', 4),
    ('Polyphème', 'polypheme', 4),
    ('Poney', 'poney', 4),
    ('Poney shetland', 'poney shetland', 4),
    ('Porc', 'porc', 4),
    ('Porc Epic du Cap', 'porc epic du cap', 4),
    ('Porc Epic d’Amérique', 'porc epic damerique', 4),
    ('Porc pie noir', 'porc pie noir', 4),
    ('Porc-épic', 'porc-epic', 4),
    ('Porc-épic à crête', 'porc-epic a crete', 4),
    ('Portée anguillard', 'portee anguillard', 4),
    ('Potamochère', 'potamochere', 4),
    ('Potamochère du Cap', 'potamochere du cap', 4),
    ('Potoo', 'potoo', 4),
    ('Pottok', 'pottok', 4),
    ('Pottos', 'pottos', 4),
    ('Pou', 'pou', 4),
    ('Pou du pubis', 'pou du pubis', 4),
    ('Pouillot de Bonelli', 'pouillot de bonelli', 4),
    ('Pouillot fitis', 'pouillot fitis', 4),
    ('Pouillot siffleur', 'pouillot siffleur', 4),
    ('Poule', 'poule', 4),
    ('Poule Araucana', 'poule araucana', 4),
    ('Poule Wyandotte', 'poule wyandotte', 4),
    ('Poule du Sussex', 'poule du sussex', 4),
    ('Poule d’eau', 'poule deau', 4),
    ('Poule soie blanche', 'poule soie blanche', 4),
    ('Poulpe', 'poulpe', 4),
    ('Praire', 'praire', 4),
    ('Processionnaire du pin', 'processionnaire du pin', 4),
    ('Prométhée', 'promethee', 4),
    ('Pronghorn', 'pronghorn', 4),
    ('Propithèque à couronne dorée', 'propitheque a couronne doree', 4),
    ('Protèle', 'protele', 4),
    ('Puce', 'puce', 4),
    ('Puceron', 'puceron', 4),
    ('Pudu des Andes', 'pudu des andes', 4),
    ('Pug', 'pug', 4),
    ('Puku', 'puku', 4),
    ('Puma', 'puma', 4),
    ('Punaise', 'punaise', 4),
    ('Punaise de feu', 'punaise de feu', 4),
    ('Punaise de la Morelle', 'punaise de la morelle', 4),
    ('Punaise de lit', 'punaise de lit', 4),
    ('Punaise d’eau géante', 'punaise deau geante', 4),
    ('Punaise ornée', 'punaise ornee', 4),
    ('Punaise-épine', 'punaise-epine', 4),
    ('Putois', 'putois', 4),
    ('Putois d’Europe', 'putois deurope', 4),
    ('Putois à pieds noirs', 'putois a pieds noirs', 4),
    ('Pygargue à tête blanche', 'pygargue a tete blanche', 4),
    ('Python', 'python', 4),
    ('Python de Seba', 'python de seba', 4),
    ('Python royal', 'python royal', 4),
    ('Python réticulé', 'python reticule', 4),
    ('Python vert', 'python vert', 4),
    ('Pécari à collier', 'pecari a collier', 4),
    ('Pécaris', 'pecaris', 4),
    ('Pékan', 'pekan', 4),
    ('Pélamide', 'pelamide', 4),
    ('Pélican', 'pelican', 4),
    ('Pélican blanc', 'pelican blanc', 4),
    ('Pélican brun', 'pelican brun', 4),
    ('Pélican frisé', 'pelican frise', 4),
    ('Pélobate brun', 'pelobate brun', 4),
    ('Pétauriste', 'petauriste', 4),
    ('Pétoncle', 'petoncle', 4),
    ('Pétrel', 'petrel', 4),
    ('Quarter-Horse', 'quarter-horse', 4),
    ('Quetzal', 'quetzal', 4),
    ('Quinnat', 'quinnat', 4),
    ('Quiscale', 'quiscale', 4),
    ('Quiscale bronzé', 'quiscale bronze', 4),
    ('Quiscale des marais', 'quiscale des marais', 4),
    ('Quiscale rouilleux', 'quiscale rouilleux', 4),
    ('Quokka', 'quokka', 4),
    ('Quoll', 'quoll', 4),
    ('Quéléa à bec rouge', 'quelea a bec rouge', 4),
    ('Ragondin', 'ragondin', 4),
    ('Raie', 'raie', 4),
    ('Raie Manta', 'raie manta', 4),
    ('Rainette', 'rainette', 4),
    ('Rainette aux yeux rouges', 'rainette aux yeux rouges', 4),
    ('Rainette ibérique', 'rainette iberique', 4),
    ('Rainette sarde', 'rainette sarde', 4),
    ('Rainette verte', 'rainette verte', 4),
    ('Raphicère (Steenbok)', 'raphicere (steenbok)', 4),
    ('Rascasse', 'rascasse', 4),
    ('Rascasse volante', 'rascasse volante', 4),
    ('Rason', 'rason', 4),
    ('Rat', 'rat', 4),
    ('Rat chinchilla', 'rat chinchilla', 4),
    ('Rat des rochers', 'rat des rochers', 4),
    ('Rat musqué', 'rat musque', 4),
    ('Rat palmiste', 'rat palmiste', 4),
    ('Rat à crinière', 'rat a criniere', 4),
    ('Rat épineux', 'rat epineux', 4),
    ('Rat-taupe', 'rat-taupe', 4),
    ('Rat-taupe nu', 'rat-taupe nu', 4),
    ('Ratel', 'ratel', 4),
    ('Ratel (Zorille du Cap)', 'ratel (zorille du cap)', 4),
    ('Raton laveur', 'raton laveur', 4),
    ('Raton laveur commun', 'raton laveur commun', 4),
    ('Ratufa indica', 'ratufa indica', 4),
    ('Renard', 'renard', 4),
    ('Renard corsac', 'renard corsac', 4),
    ('Renard crabier', 'renard crabier', 4),
    ('Renard des sables', 'renard des sables', 4),
    ('Renard des savanes', 'renard des savanes', 4),
    ('Renard gris', 'renard gris', 4),
    ('Renard polaire', 'renard polaire', 4),
    ('Renard roux', 'renard roux', 4),
    ('Renne', 'renne', 4),
    ('Requin', 'requin', 4),
    ('Requin baleine', 'requin baleine', 4),
    ('Requin blanc', 'requin blanc', 4),
    ('Requin bouledogue', 'requin bouledogue', 4),
    ('Requin gris', 'requin gris', 4),
    ('Requin mako', 'requin mako', 4),
    ('Requin marteau', 'requin marteau', 4),
    ('Requin marteau (grand)', 'requin marteau (grand)', 4),
    ('Requin pèlerin', 'requin pelerin', 4),
    ('Requin tigre', 'requin tigre', 4),
    ('Requin à pointes noires', 'requin a pointes noires', 4),
    ('Requin-baleine', 'requin-baleine', 4),
    ('Requin-nourrice', 'requin-nourrice', 4),
    ('Requin-taupe', 'requin-taupe', 4),
    ('Requin-taureau', 'requin-taureau', 4),
    ('Requin-tigre', 'requin-tigre', 4),
    ('Rhinocéros', 'rhinoceros', 4),
    ('Rhinocéros blanc', 'rhinoceros blanc', 4),
    ('Rhinocéros de Sumatra', 'rhinoceros de sumatra', 4),
    ('Rhinocéros indien', 'rhinoceros indien', 4),
    ('Rhinocéros noir', 'rhinoceros noir', 4),
    ('Rhinopithèque', 'rhinopitheque', 4),
    ('Rhinopithèque de Stryker', 'rhinopitheque de stryker', 4),
    ('Rhésus', 'rhesus', 4),
    ('Ringhal', 'ringhal', 4),
    ('Roitelet', 'roitelet', 4),
    ('Roitelet huppé', 'roitelet huppe', 4),
    ('Rollier Indien', 'rollier indien', 4),
    ('Rollier d’Europe', 'rollier deurope', 4),
    ('Rollier à longs brins', 'rollier a longs brins', 4),
    ('Rondin', 'rondin', 4),
    ('Rorqual bleu', 'rorqual bleu', 4),
    ('Rorqual commun', 'rorqual commun', 4),
    ('Rorqual à bosse', 'rorqual a bosse', 4),
    ('Rosalie alpine', 'rosalie alpine', 4),
    ('Roselin familier', 'roselin familier', 4),
    ('Roselin pourpré', 'roselin pourpre', 4),
    ('Rossignol', 'rossignol', 4),
    ('Rossignol philomèle', 'rossignol philomele', 4),
    ('Rotengle', 'rotengle', 4),
    ('Roucaou', 'roucaou', 4),
    ('Rouge gorge', 'rouge gorge', 4),
    ('Rouge-gorge', 'rouge-gorge', 4),
    ('Rouge-gorge familier', 'rouge-gorge familier', 4),
    ('Rouge-queue noir', 'rouge-queue noir', 4),
    ('Rouge-queue à front Blanc', 'rouge-queue a front blanc', 4),
    ('Rougequeue noir', 'rougequeue noir', 4),
    ('Rouget', 'rouget', 4),
    ('Rousserolle effarvatte', 'rousserolle effarvatte', 4),
    ('Roussette', 'roussette', 4),
    ('Râle de Virginie', 'rale de virginie', 4),
    ('Râle gris', 'rale gris', 4),
    ('Rémora', 'remora', 4),
    ('Sacré de Birmanie', 'sacre de birmanie', 4),
    ('Sagouin', 'sagouin', 4),
    ('Saint-Bernard', 'saint-bernard', 4),
    ('Saint-pierre', 'saint-pierre', 4),
    ('Sajou', 'sajou', 4),
    ('Saki', 'saki', 4),
    ('Saki à face blanche', 'saki a face blanche', 4),
    ('Salamandre', 'salamandre', 4),
    ('Salamandre Tachetée', 'salamandre tachetee', 4),
    ('Salamandre blanche', 'salamandre blanche', 4),
    ('Salamandre foncée', 'salamandre foncee', 4),
    ('Salamandre tachetée', 'salamandre tachetee', 4),
    ('Salers', 'salers', 4),
    ('Saltique chevronnée', 'saltique chevronnee', 4),
    ('Saluki', 'saluki', 4),
    ('Sambar', 'sambar', 4),
    ('Samoyède', 'samoyede', 4),
    ('Sandre', 'sandre', 4),
    ('Sanglier', 'sanglier', 4),
    ('Sanglier commun', 'sanglier commun', 4),
    ('Saola', 'saola', 4),
    ('Sapajou', 'sapajou', 4),
    ('Sapajou apelle', 'sapajou apelle', 4),
    ('Sar', 'sar', 4),
    ('Sarcelle d’hiver', 'sarcelle dhiver', 4),
    ('Sarcelle à ailes bleues', 'sarcelle a ailes bleues', 4),
    ('Sardine', 'sardine', 4),
    ('Sassabi', 'sassabi', 4),
    ('Saturnie Cécropia', 'saturnie cecropia', 4),
    ('Saumon', 'saumon', 4),
    ('Saumon royal', 'saumon royal', 4),
    ('Saupe', 'saupe', 4),
    ('Sauterelle', 'sauterelle', 4),
    ('Sauterelle de Bosc', 'sauterelle de bosc', 4),
    ('Sauterelle verte (grande)', 'sauterelle verte (grande)', 4),
    ('Saïga', 'saiga', 4),
    ('Saïmiri', 'saimiri', 4),
    ('Saïmiri à tête noire', 'saimiri a tete noire', 4),
    ('Scarabée du désert', 'scarabee du desert', 4),
    ('Scarabée rhinocéros européen', 'scarabee rhinoceros europeen', 4),
    ('Scarabée rhinocéros japonais', 'scarabee rhinoceros japonais', 4),
    ('Schnauzer', 'schnauzer', 4),
    ('Scinque à flancs rouges', 'scinque a flancs rouges', 4),
    ('Scolie des jardins', 'scolie des jardins', 4),
    ('Sconce', 'sconce', 4),
    ('Scorpion', 'scorpion', 4),
    ('Scottish Terrier', 'scottish terrier', 4),
    ('Seiche', 'seiche', 4),
    ('Selkirk rex', 'selkirk rex', 4),
    ('Selle français', 'selle francais', 4),
    ('Semnopithèque de Thomas', 'semnopitheque de thomas', 4),
    ('Seps strié', 'seps strie', 4),
    ('Serin cini', 'serin cini', 4),
    ('Serpent', 'serpent', 4),
    ('Serpent corail', 'serpent corail', 4),
    ('Serpent des blés', 'serpent des bles', 4),
    ('Serpent laitier', 'serpent laitier', 4),
    ('Serpent marin', 'serpent marin', 4),
    ('Serpent volant', 'serpent volant', 4),
    ('Serpent à colier rouge', 'serpent a colier rouge', 4),
    ('Serpent à lunettes', 'serpent a lunettes', 4),
    ('Serpent à sonnette', 'serpent a sonnette', 4),
    ('Serpent à tentacules', 'serpent a tentacules', 4),
    ('Serpent-minute', 'serpent-minute', 4),
    ('Serpent-roi', 'serpent-roi', 4),
    ('Serpent-tigre', 'serpent-tigre', 4),
    ('Serpentaire bacha', 'serpentaire bacha', 4),
    ('Serpentaires', 'serpentaires', 4),
    ('Serran', 'serran', 4),
    ('Serval', 'serval', 4),
    ('Setter Irlandais', 'setter irlandais', 4),
    ('Shar Peï', 'shar pei', 4),
    ('Shetland (poney)', 'shetland (poney)', 4),
    ('Shiba-inu', 'shiba-inu', 4),
    ('Siamang', 'siamang', 4),
    ('Siamang de Kloss', 'siamang de kloss', 4),
    ('Siamois', 'siamois', 4),
    ('Siberian husky', 'siberian husky', 4),
    ('Siciste', 'siciste', 4),
    ('Sifaka', 'sifaka', 4),
    ('Sigan Corail', 'sigan corail', 4),
    ('Silure', 'silure', 4),
    ('Silure glane', 'silure glane', 4),
    ('Silène', 'silene', 4),
    ('Singe', 'singe', 4),
    ('Singe araignée', 'singe araignee', 4),
    ('Singe araignée aux mains noires', 'singe araignee aux mains noires', 4),
    ('Singe araignée commun', 'singe araignee commun', 4),
    ('Singe araignée à tête brune', 'singe araignee a tete brune', 4),
    ('Singe hurleur', 'singe hurleur', 4),
    ('Singe hurleur du Guatémala', 'singe hurleur du guatemala', 4),
    ('Singe hurleur noir', 'singe hurleur noir', 4),
    ('Singe hurleur roux', 'singe hurleur roux', 4),
    ('Singe hurleur à manteau', 'singe hurleur a manteau', 4),
    ('Singe laineux', 'singe laineux', 4),
    ('Singe vert', 'singe vert', 4),
    ('Singe écureuil', 'singe ecureuil', 4),
    ('Sitatunga', 'sitatunga', 4),
    ('Sittelle', 'sittelle', 4),
    ('Sittelle torchepot', 'sittelle torchepot', 4),
    ('Sittelle à poitrine blanche', 'sittelle a poitrine blanche', 4),
    ('Sizerin blanchâtre', 'sizerin blanchatre', 4),
    ('Sizerin flammé', 'sizerin flamme', 4),
    ('Smilodon', 'smilodon', 4),
    ('Sole', 'sole', 4),
    ('Solitaire de Townsend', 'solitaire de townsend', 4),
    ('Somali', 'somali', 4),
    ('Sonneur à ventre jaune', 'sonneur a ventre jaune', 4),
    ('Sorcière blanche', 'sorciere blanche', 4),
    ('Sorraïa', 'sorraia', 4),
    ('Souris', 'souris', 4),
    ('Souris pygmée', 'souris pygmee', 4),
    ('Souris rayée d’Afrique', 'souris rayee dafrique', 4),
    ('Souslik', 'souslik', 4),
    ('Spatule blanche', 'spatule blanche', 4),
    ('Spatule rose', 'spatule rose', 4),
    ('Spermophile', 'spermophile', 4),
    ('Spermophile rayé', 'spermophile raye', 4),
    ('Sphinx de Morgan', 'sphinx de morgan', 4),
    ('Sphinx de Wallace', 'sphinx de wallace', 4),
    ('Sphinx du tilleul', 'sphinx du tilleul', 4),
    ('Sphynx', 'sphynx', 4),
    ('Spilogale', 'spilogale', 4),
    ('Spirule', 'spirule', 4),
    ('Spitz nain', 'spitz nain', 4),
    ('Spizaète orné', 'spizaete orne', 4),
    ('Sprat', 'sprat', 4),
    ('Springbok', 'springbok', 4),
    ('Spélerpès', 'spelerpes', 4),
    ('Squille', 'squille', 4),
    ('Steenbok', 'steenbok', 4),
    ('Sterne', 'sterne', 4),
    ('Sturnelle des prés', 'sturnelle des pres', 4),
    ('Suricate', 'suricate', 4),
    ('Surucucu', 'surucucu', 4),
    ('Sébaste', 'sebaste', 4),
    ('Ségestrie florentine', 'segestrie florentine', 4),
    ('Sériole', 'seriole', 4),
    ('Sévereau', 'severeau', 4),
    ('Tacaud', 'tacaud', 4),
    ('Tadorne casarca', 'tadorne casarca', 4),
    ('Tadorne de belon', 'tadorne de belon', 4),
    ('Takin', 'takin', 4),
    ('Talapoin', 'talapoin', 4),
    ('Talève violacée', 'taleve violacee', 4),
    ('Tamandua', 'tamandua', 4),
    ('Tamandua du Mexique', 'tamandua du mexique', 4),
    ('Tamanoir', 'tamanoir', 4),
    ('Tamanoir (fourmilier)', 'tamanoir (fourmilier)', 4),
    ('Tamarin', 'tamarin', 4),
    ('Tamarin empereur', 'tamarin empereur', 4),
    ('Tamarin lion doré', 'tamarin lion dore', 4),
    ('Tamarin à mains dorées', 'tamarin a mains dorees', 4),
    ('Tamarin-lion doré', 'tamarin-lion dore', 4),
    ('Tamia', 'tamia', 4),
    ('Tamia rayé', 'tamia raye', 4),
    ('Tanche', 'tanche', 4),
    ('Tanche-tautogue', 'tanche-tautogue', 4),
    ('Tangara émeraude', 'tangara emeraude', 4),
    ('Tangara évêque', 'tangara eveque', 4),
    ('Tantale d’Amérique', 'tantale damerique', 4),
    ('Tantale ibis', 'tantale ibis', 4),
    ('Tanude', 'tanude', 4),
    ('Taon', 'taon', 4),
    ('Tapir', 'tapir', 4),
    ('Tapir de Malaisie', 'tapir de malaisie', 4),
    ('Tapir du Brésil', 'tapir du bresil', 4),
    ('Tapir malais', 'tapir malais', 4),
    ('Tarentaise', 'tarentaise', 4),
    ('Tarente du midi', 'tarente du midi', 4),
    ('Tarentule', 'tarentule', 4),
    ('Targeur', 'targeur', 4),
    ('Tarier pâtre', 'tarier patre', 4),
    ('Tarin des aulnes', 'tarin des aulnes', 4),
    ('Tarin des pins', 'tarin des pins', 4),
    ('Tarine', 'tarine', 4),
    ('Tarsier', 'tarsier', 4),
    ('Tarsier des Philippines', 'tarsier des philippines', 4),
    ('Tassergal', 'tassergal', 4),
    ('Tatou', 'tatou', 4),
    ('Tatou géant', 'tatou geant', 4),
    ('Tatou à neuf bandes', 'tatou a neuf bandes', 4),
    ('Taupe d’Europe', 'taupe deurope', 4),
    ('Taupe à nez étoilé', 'taupe a nez etoile', 4),
    ('Taureau', 'taureau', 4),
    ('Tautogue noir', 'tautogue noir', 4),
    ('Taïpan du désert', 'taipan du desert', 4),
    ('Tchitrec de paradis', 'tchitrec de paradis', 4),
    ('Teckel à poils longs', 'teckel a poils longs', 4),
    ('Tenrec zébré', 'tenrec zebre', 4),
    ('Termite', 'termite', 4),
    ('Tervueren', 'tervueren', 4),
    ('Thazard', 'thazard', 4),
    ('Thomise enflée', 'thomise enflee', 4),
    ('Thon', 'thon', 4),
    ('Thon albacore', 'thon albacore', 4),
    ('Thon blanc', 'thon blanc', 4),
    ('Thon listao', 'thon listao', 4),
    ('Thon rouge', 'thon rouge', 4),
    ('Tichodrome échelette', 'tichodrome echelette', 4),
    ('Tigre', 'tigre', 4),
    ('Tigre blanc royal', 'tigre blanc royal', 4),
    ('Tigre de Sibérie', 'tigre de siberie', 4),
    ('Tigre de Sumatra', 'tigre de sumatra', 4),
    ('Tigre de Tasmanie', 'tigre de tasmanie', 4),
    ('Tigre doré', 'tigre dore', 4),
    ('Tigre du Bengal', 'tigre du bengal', 4),
    ('Tigre du Bengale', 'tigre du bengale', 4),
    ('Tigre à dents de sabre', 'tigre a dents de sabre', 4),
    ('Tilapia', 'tilapia', 4),
    ('Tilapia du Nil', 'tilapia du nil', 4),
    ('Tipule', 'tipule', 4),
    ('Tique', 'tique', 4),
    ('Tisserin gendarme', 'tisserin gendarme', 4),
    ('Titan', 'titan', 4),
    ('Titi roux', 'titi roux', 4),
    ('Titiwai', 'titiwai', 4),
    ('Tjictjac', 'tjictjac', 4),
    ('Tohi tacheté', 'tohi tachete', 4),
    ('Tohi à flancs roux', 'tohi a flancs roux', 4),
    ('Topi', 'topi', 4),
    ('Torcol fourmilier', 'torcol fourmilier', 4),
    ('Tortue', 'tortue', 4),
    ('Tortue d’Hermann', 'tortue dhermann', 4),
    ('Tortue grecque', 'tortue grecque', 4),
    ('Tortue géante', 'tortue geante', 4),
    ('Tortue géante des Galapagos', 'tortue geante des galapagos', 4),
    ('Tortue luth', 'tortue luth', 4),
    ('Tortue molle', 'tortue molle', 4),
    ('Tortue serpentine', 'tortue serpentine', 4),
    ('Tortue verte', 'tortue verte', 4),
    ('Toucan', 'toucan', 4),
    ('Toucan toco', 'toucan toco', 4),
    ('Toucan à carène', 'toucan a carene', 4),
    ('Touladi', 'touladi', 4),
    ('Touraco vert', 'touraco vert', 4),
    ('Tournepierre à collier', 'tournepierre a collier', 4),
    ('Tourteau', 'tourteau', 4),
    ('Tourterelle', 'tourterelle', 4),
    ('Tourterelle des bois', 'tourterelle des bois', 4),
    ('Tourterelle turque', 'tourterelle turque', 4),
    ('Traquet motteux', 'traquet motteux', 4),
    ('Travailleur à bec rouge', 'travailleur a bec rouge', 4),
    ('Tricot rayé', 'tricot raye', 4),
    ('Trigonocéphale', 'trigonocephale', 4),
    ('Triton', 'triton', 4),
    ('Triton alpestre', 'triton alpestre', 4),
    ('Troglodyte de Caroline', 'troglodyte de caroline', 4),
    ('Troglodyte des forets', 'troglodyte des forets', 4),
    ('Troglodyte des marais', 'troglodyte des marais', 4),
    ('Troglodyte familier', 'troglodyte familier', 4),
    ('Troglodyte mignon', 'troglodyte mignon', 4),
    ('Troglodyte à bec court', 'troglodyte a bec court', 4),
    ('Trogon de Cuba', 'trogon de cuba', 4),
    ('Tropidacris cristata', 'tropidacris cristata', 4),
    ('Truire brune', 'truire brune', 4),
    ('Truite', 'truite', 4),
    ('Truite arc-en-ciel', 'truite arc-en-ciel', 4),
    ('Truite de mer', 'truite de mer', 4),
    ('Truite fario', 'truite fario', 4),
    ('Tuco-tuco', 'tuco-tuco', 4),
    ('Turbot', 'turbot', 4),
    ('Turquoise', 'turquoise', 4),
    ('Tyran', 'tyran', 4),
    ('Tyrannosaure', 'tyrannosaure', 4),
    ('Tégénaire géante', 'tegenaire geante', 4),
    ('Tégénaire noire', 'tegenaire noire', 4),
    ('Ténébrion meunier', 'tenebrion meunier', 4),
    ('Tétraodon', 'tetraodon', 4),
    ('Tétras des prairies', 'tetras des prairies', 4),
    ('Tétras du Canada', 'tetras du canada', 4),
    ('Tétras lyre', 'tetras lyre', 4),
    ('Têtards', 'tetards', 4),
    ('Unau (paresseux à 2 doigts)', 'unau (paresseux a 2 doigts)', 4),
    ('Uranoscope', 'uranoscope', 4),
    ('Urial', 'urial', 4),
    ('Urodèles', 'urodeles', 4),
    ('Urubu noir', 'urubu noir', 4),
    ('Urubu à tête rouge', 'urubu a tete rouge', 4),
    ('Urutu', 'urutu', 4),
    ('Vache', 'vache', 4),
    ('Vacher à tête brune', 'vacher a tete brune', 4),
    ('Vairon', 'vairon', 4),
    ('Vampire d’Azara', 'vampire dazara', 4),
    ('Vandoise', 'vandoise', 4),
    ('Vanneau huppé', 'vanneau huppe', 4),
    ('Vanneau éperonné', 'vanneau eperonne', 4),
    ('Varan', 'varan', 4),
    ('Varan bigarré', 'varan bigarre', 4),
    ('Varan de Gould', 'varan de gould', 4),
    ('Varan du Nil', 'varan du nil', 4),
    ('Vautour', 'vautour', 4),
    ('Vautour africain', 'vautour africain', 4),
    ('Vautour fauve', 'vautour fauve', 4),
    ('Vautour pape', 'vautour pape', 4),
    ('Vautour percnoptère', 'vautour percnoptere', 4),
    ('Veau', 'veau', 4),
    ('Venturon montagnard', 'venturon montagnard', 4),
    ('Ver de bancoule', 'ver de bancoule', 4),
    ('Ver luisant', 'ver luisant', 4),
    ('Verdier d’Europe', 'verdier deurope', 4),
    ('Verrat', 'verrat', 4),
    ('Vervet', 'vervet', 4),
    ('Veuve du paradis', 'veuve du paradis', 4),
    ('Veuve noire', 'veuve noire', 4),
    ('Vibora de la cruz', 'vibora de la cruz', 4),
    ('Vieille', 'vieille', 4),
    ('Vigogne', 'vigogne', 4),
    ('Vipère', 'vipere', 4),
    ('Vipère aspic', 'vipere aspic', 4),
    ('Vipère des cent pas', 'vipere des cent pas', 4),
    ('Vipère à cornes', 'vipere a cornes', 4),
    ('Viréo', 'vireo', 4),
    ('Viscache', 'viscache', 4),
    ('Viscache des plaines', 'viscache des plaines', 4),
    ('Vison', 'vison', 4),
    ('Vison d’Europe', 'vison deurope', 4),
    ('Vivaneau', 'vivaneau', 4),
    ('Vive', 'vive', 4),
    ('Vive araignée', 'vive araignee', 4),
    ('Vive rayée', 'vive rayee', 4),
    ('Vrillette', 'vrillette', 4),
    ('Vrillette du pain', 'vrillette du pain', 4),
    ('Vulcain', 'vulcain', 4),
    ('Wallaby', 'wallaby', 4),
    ('Wallaby de Bennett (à cou rouge)', 'wallaby de bennett (a cou rouge)', 4),
    ('Wallaby des rochers', 'wallaby des rochers', 4),
    ('Wapiti', 'wapiti', 4),
    ('Waterbuck', 'waterbuck', 4),
    ('Watussi', 'watussi', 4),
    ('Welsh corgi', 'welsh corgi', 4),
    ('West highland terrier', 'west highland terrier', 4),
    ('Weta', 'weta', 4),
    ('Weta des arbres', 'weta des arbres', 4),
    ('Weta des cavernes', 'weta des cavernes', 4),
    ('Weta géant', 'weta geant', 4),
    ('Woma', 'woma', 4),
    ('Wombat', 'wombat', 4),
    ('Wombat commun', 'wombat commun', 4),
    ('Xantusie du désert', 'xantusie du desert', 4),
    ('Xipho', 'xipho', 4),
    ('Xylocope violacé', 'xylocope violace', 4),
    ('Xylocope violet', 'xylocope violet', 4),
    ('Xénope', 'xenope', 4),
    ('Xérus', 'xerus', 4),
    ('Yack', 'yack', 4),
    ('Yak sauvage', 'yak sauvage', 4),
    ('Yapock', 'yapock', 4),
    ('Yarará chica', 'yarara chica', 4),
    ('York Chocolat', 'york chocolat', 4),
    ('Yorkshire terrier', 'yorkshire terrier', 4),
    ('Zabre des céréales', 'zabre des cereales', 4),
    ('Zapode', 'zapode', 4),
    ('Zibeline', 'zibeline', 4),
    ('Zokor', 'zokor', 4),
    ('Zorille', 'zorille', 4),
    ('Zorille du Cap', 'zorille du cap', 4),
    ('Zorille du Cap (Ratel)', 'zorille du cap (ratel)', 4),
    ('Zygène', 'zygene', 4),
    ('Zyzomys', 'zyzomys', 4),
    ('Zèbre', 'zebre', 4),
    ('Zèbre de Burchell', 'zebre de burchell', 4),
    ('Zèbre de Grevy', 'zebre de grevy', 4),
    ('Zèbre de Grévy', 'zebre de grevy', 4),
    ('Zèbre de montagne', 'zebre de montagne', 4),
    ('Zébrule', 'zebrule', 4),
    ('Zébu', 'zebu', 4),
    ('resplendissant', 'resplendissant', 4),
    ('Âne', 'ane', 4),
    ('Échasse blanche', 'echasse blanche', 4),
    ('Échide', 'echide', 4),
    ('Échidné', 'echidne', 4),
    ('Écrevisse', 'ecrevisse', 4),
    ('Écureuil', 'ecureuil', 4),
    ('Écureuil antilope', 'ecureuil antilope', 4),
    ('Écureuil roux', 'ecureuil roux', 4),
    ('Écureuil volant', 'ecureuil volant', 4),
    ('Églefin', 'eglefin', 4),
    ('Élan', 'elan', 4),
    ('Éland', 'eland', 4),
    ('Élanion blanc', 'elanion blanc', 4),
    ('Éléphant', 'elephant', 4),
    ('Émeu', 'emeu', 4),
    ('Épaulard', 'epaulard', 4),
    ('Épeire', 'epeire', 4),
    ('Éperlan', 'eperlan', 4),
    ('Épervier', 'epervier', 4),
    ('Éphémère', 'ephemere', 4),
    ('Épinoche', 'epinoche', 4),
    ('Épinochette', 'epinochette', 4),
    ('Équille', 'equille', 4),
    ('Érismature rousse', 'erismature rousse', 4),
    ('Étoile de mer', 'etoile de mer', 4),
    ('Étourneau', 'etourneau', 4),
    ('Étrille', 'etrille', 4)
ON CONFLICT (mot_normalized, categorie_id) DO NOTHING;
