INSERT INTO mots (mot, mot_normalized, categorie_id) VALUES
    ('AES', 'aes', 5),
    ('ASVP', 'asvp', 5),
    ('ATSEM', 'atsem', 5),
    ('Accessoiriste', 'accessoiriste', 5),
    ('Accompagnant d’élève en situation de handicap', 'accompagnantd’eleveensituationdehandicap', 5),
    ('Accompagnateur de voyage', 'accompagnateurdevoyage', 5),
    ('Accordeur', 'accordeur', 5),
    ('Accordeur de piano', 'accordeurdepiano', 5),
    ('Account manager', 'accountmanager', 5),
    ('Acheteur', 'acheteur', 5),
    ('Acheteur dans la mode', 'acheteurdanslamode', 5),
    ('Acheteur d’art', 'acheteurd’art', 5),
    ('Acheteur industriel', 'acheteurindustriel', 5),
    ('Acousticien', 'acousticien', 5),
    ('Acrobate', 'acrobate', 5),
    ('Acteur', 'acteur', 5),
    ('Actuaire', 'actuaire', 5),
    ('Acupuncteur', 'acupuncteur', 5),
    ('Adjoint administratif', 'adjointadministratif', 5),
    ('Adjoint de Sécurité', 'adjointdesecurite', 5),
    ('Adjoint de direction', 'adjointdedirection', 5),
    ('Adjoint d’animation', 'adjointd’animation', 5),
    ('Administrateur Réseau', 'administrateurreseau', 5),
    ('Administrateur civil', 'administrateurcivil', 5),
    ('Administrateur de base de données', 'administrateurdebasededonnees', 5),
    ('Administrateur de bases de données', 'administrateurdebasesdedonnees', 5),
    ('Administrateur de biens', 'administrateurdebiens', 5),
    ('Administrateur de spectacle', 'administrateurdespectacle', 5),
    ('Administrateur des ventes', 'administrateurdesventes', 5),
    ('Administrateur du Sénat', 'administrateurdusenat', 5),
    ('Administrateur judiciaire', 'administrateurjudiciaire', 5),
    ('Administrateur réseaux', 'administrateurreseaux', 5),
    ('Administrateur système', 'administrateursysteme', 5),
    ('Administrateur systèmes', 'administrateursystemes', 5),
    ('Administrateur territorial', 'administrateurterritorial', 5),
    ('Affréteur', 'affreteur', 5),
    ('Agent', 'agent', 5),
    ('Agent artistique', 'agentartistique', 5),
    ('Agent commercial du transport', 'agentcommercialdutransport', 5),
    ('Agent de change', 'agentdechange', 5),
    ('Agent de distribution', 'agentdedistribution', 5),
    ('Agent de développement local', 'agentdedeveloppementlocal', 5),
    ('Agent de gestion comptable', 'agentdegestioncomptable', 5),
    ('Agent de joueur sportif', 'agentdejoueursportif', 5),
    ('Agent de location', 'agentdelocation', 5),
    ('Agent de maintenance', 'agentdemaintenance', 5),
    ('Agent de manutention', 'agentdemanutention', 5),
    ('Agent de police', 'agentdepolice', 5),
    ('Agent de presse', 'agentdepresse', 5),
    ('Agent de recouvrement du trésor', 'agentderecouvrementdutresor', 5),
    ('Agent de routage', 'agentderoutage', 5),
    ('Agent de réservation', 'agentdereservation', 5),
    ('Agent de service hospitalier', 'agentdeservicehospitalier', 5),
    ('Agent de surveillance de la voie publique (ASVP)', 'agentdesurveillancedelavoiepublique(asvp)', 5),
    ('Agent de sécurité', 'agentdesecurite', 5),
    ('Agent de sûreté', 'agentdesurete', 5),
    ('Agent de sûreté aéroportuaire', 'agentdesureteaeroportuaire', 5),
    ('Agent de transit', 'agentdetransit', 5),
    ('Agent de vente', 'agentdevente', 5),
    ('Agent de voyages', 'agentdevoyages', 5),
    ('Agent des finances publiques', 'agentdesfinancespubliques', 5),
    ('Agent du service commercial trains', 'agentduservicecommercialtrains', 5),
    ('Agent d’accueil', 'agentd’accueil', 5),
    ('Agent d’accueil en agence bancaire', 'agentd’accueilenagencebancaire', 5),
    ('Agent d’accueil touristique', 'agentd’accueiltouristique', 5),
    ('Agent d’assurance', 'agentd’assurance', 5),
    ('Agent d’entretien', 'agentd’entretien', 5),
    ('Agent d’escale', 'agentd’escale', 5),
    ('Agent d’escale aéroportuaire', 'agentd’escaleaeroportuaire', 5),
    ('Agent funéraire', 'agentfuneraire', 5),
    ('Agent général d’assurances', 'agentgenerald’assurances', 5),
    ('Agent immobilier', 'agentimmobilier', 5),
    ('Agent logisticien', 'agentlogisticien', 5),
    ('Agent ou auxiliaire de crèche', 'agentouauxiliairedecreche', 5),
    ('Agent secret', 'agentsecret', 5),
    ('Agent technique forestier', 'agenttechniqueforestier', 5),
    ('Agent territorial spécialisé des écoles maternelles', 'agentterritorialspecialisedesecolesmaternelles', 5),
    ('Agent thermal', 'agentthermal', 5),
    ('Agriculteur', 'agriculteur', 5),
    ('Agronome', 'agronome', 5),
    ('Aide auxiliaire de puériculture', 'aideauxiliairedepuericulture', 5),
    ('Aide médico-psychologique', 'aidemedico-psychologique', 5),
    ('Aide soignante', 'aidesoignante', 5),
    ('Aide à domicile', 'aideadomicile', 5),
    ('Aide-caissier', 'aide-caissier', 5),
    ('Aide-documentaliste', 'aide-documentaliste', 5),
    ('Aide-soignant', 'aide-soignant', 5),
    ('Aide-éducateur', 'aide-educateur', 5),
    ('Aiguilleur', 'aiguilleur', 5),
    ('Aiguilleur du ciel', 'aiguilleurduciel', 5),
    ('Aiguilleur du rail', 'aiguilleurdurail', 5),
    ('Ajusteur', 'ajusteur', 5),
    ('Ajusteur-monteur', 'ajusteur-monteur', 5),
    ('Ambulancier', 'ambulancier', 5),
    ('Aménageur d’espace intérieur', 'amenageurd’espaceinterieur', 5),
    ('Aménageur foncier', 'amenageurfoncier', 5),
    ('Aménageur lotisseur', 'amenageurlotisseur', 5),
    ('Analyste', 'analyste', 5),
    ('Analyste SOC', 'analystesoc', 5),
    ('Analyste Web', 'analysteweb', 5),
    ('Analyste crédit', 'analystecredit', 5),
    ('Analyste financier', 'analystefinancier', 5),
    ('Analyste fonctionnel', 'analystefonctionnel', 5),
    ('Analyste gouvernance', 'analystegouvernance', 5),
    ('Analyste juridique', 'analystejuridique', 5),
    ('Analyste marketing', 'analystemarketing', 5),
    ('Analyste programmeur', 'analysteprogrammeur', 5),
    ('Analyste sensoriel', 'analystesensoriel', 5),
    ('Analyste test et validation', 'analystetestetvalidation', 5),
    ('Anesthésiste', 'anesthesiste', 5),
    ('Animalier en laboratoire', 'animalierenlaboratoire', 5),
    ('Animateur', 'animateur', 5),
    ('Animateur 2D', 'animateur2d', 5),
    ('Animateur 3D', 'animateur3d', 5),
    ('Animateur Petite Enfance', 'animateurpetiteenfance', 5),
    ('Animateur commerciale', 'animateurcommerciale', 5),
    ('Animateur de club de vacances', 'animateurdeclubdevacances', 5),
    ('Animateur de spectacle', 'animateurdespectacle', 5),
    ('Animateur de tourisme local', 'animateurdetourismelocal', 5),
    ('Animateur de télévision', 'animateurdetelevision', 5),
    ('Animateur de vacances', 'animateurdevacances', 5),
    ('Animateur des ventes', 'animateurdesventes', 5),
    ('Animateur du patrimoine', 'animateurdupatrimoine', 5),
    ('Animateur logistique', 'animateurlogistique', 5),
    ('Animateur nature', 'animateurnature', 5),
    ('Animateur radio', 'animateurradio', 5),
    ('Animateur socio-culturel', 'animateursocio-culturel', 5),
    ('Animateur socioculturel', 'animateursocioculturel', 5),
    ('Animateur touristique', 'animateurtouristique', 5),
    ('Animateur économique', 'animateureconomique', 5),
    ('Anthropologue', 'anthropologue', 5),
    ('Antiquaire', 'antiquaire', 5),
    ('Apiculteur', 'apiculteur', 5),
    ('Approvisionneur', 'approvisionneur', 5),
    ('Apprêteur', 'appreteur', 5),
    ('Aquaculteur', 'aquaculteur', 5),
    ('Arbitre', 'arbitre', 5),
    ('Arboriculteur', 'arboriculteur', 5),
    ('Archetier', 'archetier', 5),
    ('Architecte', 'architecte', 5),
    ('Architecte Big Data', 'architectebigdata', 5),
    ('Architecte de réseaux', 'architectedereseaux', 5),
    ('Architecte du patrimoine', 'architectedupatrimoine', 5),
    ('Architecte d’information', 'architected’information', 5),
    ('Architecte d’intérieur', 'architected’interieur', 5),
    ('Architecte en système d’information', 'architecteensystemed’information', 5),
    ('Architecte fonctionnel SI', 'architectefonctionnelsi', 5),
    ('Architecte paysagiste', 'architectepaysagiste', 5),
    ('Architecte système', 'architectesysteme', 5),
    ('Architecte web', 'architecteweb', 5),
    ('Architecte-paysagiste', 'architecte-paysagiste', 5),
    ('Archiviste', 'archiviste', 5),
    ('Archéologue', 'archeologue', 5),
    ('Ardoisier', 'ardoisier', 5),
    ('Argenteur', 'argenteur', 5),
    ('Armateur', 'armateur', 5),
    ('Armurier', 'armurier', 5),
    ('Aromathérapeute', 'aromatherapeute', 5),
    ('Aromaticien', 'aromaticien', 5),
    ('Aromaticien parfumeur', 'aromaticienparfumeur', 5),
    ('Artificier', 'artificier', 5),
    ('Artisan fromager', 'artisanfromager', 5),
    ('Artiste de cirque', 'artistedecirque', 5),
    ('Artiste peintre', 'artistepeintre', 5),
    ('Ascensoriste', 'ascensoriste', 5),
    ('Asset manager', 'assetmanager', 5),
    ('Assistant', 'assistant', 5),
    ('Assistant RH', 'assistantrh', 5),
    ('Assistant blibliothécaire', 'assistantblibliothecaire', 5),
    ('Assistant chef de chantier', 'assistantchefdechantier', 5),
    ('Assistant chef de projet', 'assistantchefdeprojet', 5),
    ('Assistant commercial', 'assistantcommercial', 5),
    ('Assistant comptable', 'assistantcomptable', 5),
    ('Assistant de Justice', 'assistantdejustice', 5),
    ('Assistant de Régulation Médicale', 'assistantderegulationmedicale', 5),
    ('Assistant de communication', 'assistantdecommunication', 5),
    ('Assistant de direction', 'assistantdedirection', 5),
    ('Assistant de gestion PME-PMI', 'assistantdegestionpme-pmi', 5),
    ('Assistant de production', 'assistantdeproduction', 5),
    ('Assistant de service social', 'assistantdeservicesocial', 5),
    ('Assistant de sénateur', 'assistantdesenateur', 5),
    ('Assistant dentaire', 'assistantdentaire', 5),
    ('Assistant d’éducation', 'assistantd’education', 5),
    ('Assistant en recrutement', 'assistantenrecrutement', 5),
    ('Assistant familial', 'assistantfamilial', 5),
    ('Assistant juridique', 'assistantjuridique', 5),
    ('Assistant marketing', 'assistantmarketing', 5),
    ('Assistant maternel', 'assistantmaternel', 5),
    ('Assistant médical', 'assistantmedical', 5),
    ('Assistant opérateur', 'assistantoperateur', 5),
    ('Assistant paie et administration', 'assistantpaieetadministration', 5),
    ('Assistant parlementaire', 'assistantparlementaire', 5),
    ('Assistant réalisateur', 'assistantrealisateur', 5),
    ('Assistant son', 'assistantson', 5),
    ('Assistant vétérinaire', 'assistantveterinaire', 5),
    ('Assistant à maîtrise d’ouvrage', 'assistantamaitrised’ouvrage', 5),
    ('Assistant(e) commercial(e)', 'assistant(e)commercial(e)', 5),
    ('Assistant(e) dentaire', 'assistant(e)dentaire', 5),
    ('Assistante de direction', 'assistantededirection', 5),
    ('Assistante de gestion PME/PMI', 'assistantedegestionpme/pmi', 5),
    ('Assistante juridique', 'assistantejuridique', 5),
    ('Assistante maternelle', 'assistantematernelle', 5),
    ('Assistante sociale', 'assistantesociale', 5),
    ('Assitant administratif et financier', 'assitantadministratifetfinancier', 5),
    ('Assureur', 'assureur', 5),
    ('Astronaute', 'astronaute', 5),
    ('Astronaute (ou cosmonaute, spationaute)', 'astronaute(oucosmonaute,spationaute)', 5),
    ('Astronome', 'astronome', 5),
    ('Astrophysicien', 'astrophysicien', 5),
    ('Athlète', 'athlete', 5),
    ('Attaché analyste-informaticien', 'attacheanalyste-informaticien', 5),
    ('Attaché commercial', 'attachecommercial', 5),
    ('Attaché commercial sédentaire', 'attachecommercialsedentaire', 5),
    ('Attaché culturel', 'attacheculturel', 5),
    ('Attaché de police', 'attachedepolice', 5),
    ('Attaché de presse', 'attachedepresse', 5),
    ('Attaché de préfecture', 'attachedeprefecture', 5),
    ('Attaché parlementaire', 'attacheparlementaire', 5),
    ('Attaché territorial', 'attacheterritorial', 5),
    ('Audioprothésiste', 'audioprothesiste', 5),
    ('Auditeur', 'auditeur', 5),
    ('Auditeur externe', 'auditeurexterne', 5),
    ('Auditeur financier', 'auditeurfinancier', 5),
    ('Auditeur interne', 'auditeurinterne', 5),
    ('Auditeur social', 'auditeursocial', 5),
    ('Auteur', 'auteur', 5),
    ('Automaticien', 'automaticien', 5),
    ('Auxiliaire de Vie Scolaire', 'auxiliairedeviescolaire', 5),
    ('Auxiliaire de Vie Sociale', 'auxiliairedeviesociale', 5),
    ('Auxiliaire de puériculture', 'auxiliairedepuericulture', 5),
    ('Auxiliaire de santé animale', 'auxiliairedesanteanimale', 5),
    ('Auxiliaire de vie', 'auxiliairedevie', 5),
    ('Auxiliaire parentale', 'auxiliaireparentale', 5),
    ('Auxiliaire vétérinaire', 'auxiliaireveterinaire', 5),
    ('Aviateur', 'aviateur', 5),
    ('Avocat', 'avocat', 5),
    ('Avocat au Conseil d’État', 'avocatauconseild’etat', 5),
    ('Avocat du droit des personnes', 'avocatdudroitdespersonnes', 5),
    ('Avocat d’affaires', 'avocatd’affaires', 5),
    ('Avocat pénaliste', 'avocatpenaliste', 5),
    ('Avocat à la cour de cassation', 'avocatalacourdecassation', 5),
    ('Avoué', 'avoue', 5),
    ('BIM Manager', 'bimmanager', 5),
    ('Balayeur', 'balayeur', 5),
    ('Banquier', 'banquier', 5),
    ('Barbier', 'barbier', 5),
    ('Barman', 'barman', 5),
    ('Barman/barmaid', 'barman/barmaid', 5),
    ('Batelier', 'batelier', 5),
    ('Batteur d’or', 'batteurd’or', 5),
    ('Berger', 'berger', 5),
    ('Bibliothécaire', 'bibliothecaire', 5),
    ('Bibliothécaire adjoint', 'bibliothecaireadjoint', 5),
    ('Bid Manager', 'bidmanager', 5),
    ('Bijoutier', 'bijoutier', 5),
    ('Bijoutier-horloger', 'bijoutier-horloger', 5),
    ('Bijoutier-joaillier', 'bijoutier-joaillier', 5),
    ('Billettiste', 'billettiste', 5),
    ('Bio-informaticien', 'bio-informaticien', 5),
    ('Biochimiste', 'biochimiste', 5),
    ('Biographe', 'biographe', 5),
    ('Biologiste', 'biologiste', 5),
    ('Biologiste médical', 'biologistemedical', 5),
    ('Biomathématicien', 'biomathematicien', 5),
    ('Bionaute', 'bionaute', 5),
    ('Biophysicien', 'biophysicien', 5),
    ('Biotechnologue', 'biotechnologue', 5),
    ('Blanchisseur d’argent', 'blanchisseurd’argent', 5),
    ('Botaniste', 'botaniste', 5),
    ('Boucher', 'boucher', 5),
    ('Boucher-charcutier', 'boucher-charcutier', 5),
    ('Boulanger', 'boulanger', 5),
    ('Boulanger-pâtissier', 'boulanger-patissier', 5),
    ('Bourreau', 'bourreau', 5),
    ('Boutonnier', 'boutonnier', 5),
    ('Brancardier', 'brancardier', 5),
    ('Brasseur', 'brasseur', 5),
    ('Brasseur malteur', 'brasseurmalteur', 5),
    ('Briquetier', 'briquetier', 5),
    ('Brodeur', 'brodeur', 5),
    ('Bronzier', 'bronzier', 5),
    ('Bruiteur', 'bruiteur', 5),
    ('Buraliste', 'buraliste', 5),
    ('Business Developer', 'businessdeveloper', 5),
    ('Butler', 'butler', 5),
    ('Bétonneur / Bétonnier', 'betonneur/betonnier', 5),
    ('Bûcheron', 'bucheron', 5),
    ('Cadet de la République', 'cadetdelarepublique', 5),
    ('Cadre d’écurie', 'cadred’ecurie', 5),
    ('Cadreur', 'cadreur', 5),
    ('Caissier', 'caissier', 5),
    ('Caissier/caissière', 'caissier/caissiere', 5),
    ('Calligraphe', 'calligraphe', 5),
    ('Calorifugeur', 'calorifugeur', 5),
    ('Cambiste', 'cambiste', 5),
    ('Cambrioleur', 'cambrioleur', 5),
    ('Camionneur', 'camionneur', 5),
    ('Campaniste', 'campaniste', 5),
    ('Campus-manager', 'campus-manager', 5),
    ('Caméraman', 'cameraman', 5),
    ('Cancérologue', 'cancerologue', 5),
    ('Canneur-rempailleur', 'canneur-rempailleur', 5),
    ('Capitaine', 'capitaine', 5),
    ('Capitaine de navire', 'capitainedenavire', 5),
    ('Capitaine de sapeur-pompier', 'capitainedesapeur-pompier', 5),
    ('Cardiologue', 'cardiologue', 5),
    ('Cariste', 'cariste', 5),
    ('Carreleur', 'carreleur', 5),
    ('Carrossier', 'carrossier', 5),
    ('Carrossier réparateur', 'carrossierreparateur', 5),
    ('Carrossier-peintre', 'carrossier-peintre', 5),
    ('Cartographe', 'cartographe', 5),
    ('Cartonnier', 'cartonnier', 5),
    ('Cascadeur', 'cascadeur', 5),
    ('Caster', 'caster', 5),
    ('Category manager', 'categorymanager', 5),
    ('Caviste', 'caviste', 5),
    ('Chanteur', 'chanteur', 5),
    ('Chapelier', 'chapelier', 5),
    ('Chapelier / Chapelière', 'chapelier/chapeliere', 5),
    ('Character designer', 'characterdesigner', 5),
    ('Charcutier', 'charcutier', 5),
    ('Chargeur', 'chargeur', 5),
    ('Chargé (ou chef) de projet en informatique', 'charge(ouchef)deprojeteninformatique', 5),
    ('Chargé de clientèle', 'chargedeclientele', 5),
    ('Chargé de clientèle particuliers', 'chargedeclienteleparticuliers', 5),
    ('Chargé de clientèle professionnels', 'chargedeclienteleprofessionnels', 5),
    ('Chargé de communication', 'chargedecommunication', 5),
    ('Chargé de conformité', 'chargedeconformite', 5),
    ('Chargé de formation', 'chargedeformation', 5),
    ('Chargé de mission', 'chargedemission', 5),
    ('Chargé de mission handicap', 'chargedemissionhandicap', 5),
    ('Chargé de packaging', 'chargedepackaging', 5),
    ('Chargé de production', 'chargedeproduction', 5),
    ('Chargé de production vidéo', 'chargedeproductionvideo', 5),
    ('Chargé de programmation', 'chargedeprogrammation', 5),
    ('Chargé de recherche animalier', 'chargederechercheanimalier', 5),
    ('Chargé de recouvrement', 'chargederecouvrement', 5),
    ('Chargé de recrutement', 'chargederecrutement', 5),
    ('Chargé de relations publiques', 'chargederelationspubliques', 5),
    ('Chargé de référencement', 'chargedereferencement', 5),
    ('Chargé du développement', 'chargedudeveloppement', 5),
    ('Chargé d’accueil', 'charged’accueil', 5),
    ('Chargé d’affaires', 'charged’affaires', 5),
    ('Chargé d’affaires FTTH', 'charged’affairesftth', 5),
    ('Chargé d’affaires agricoles', 'charged’affairesagricoles', 5),
    ('Chargé d’assistance', 'charged’assistance', 5),
    ('Chargé d’indemnisation', 'charged’indemnisation', 5),
    ('Chargé d’études', 'charged’etudes', 5),
    ('Chargé d’études marketing', 'charged’etudesmarketing', 5),
    ('Chargé d’études optiques', 'charged’etudesoptiques', 5),
    ('Chargé d’études personnels', 'charged’etudespersonnels', 5),
    ('Charpentier', 'charpentier', 5),
    ('Charpentier bois', 'charpentierbois', 5),
    ('Charron', 'charron', 5),
    ('Chasseur', 'chasseur', 5),
    ('Chasseur de tête', 'chasseurdetete', 5),
    ('Chasseur de têtes', 'chasseurdetetes', 5),
    ('Chaudronnier', 'chaudronnier', 5),
    ('Chauffagiste', 'chauffagiste', 5),
    ('Chauffeur', 'chauffeur', 5),
    ('Chauffeur de Grande Remise', 'chauffeurdegranderemise', 5),
    ('Chauffeur de Petite Remise', 'chauffeurdepetiteremise', 5),
    ('Chauffeur de bus', 'chauffeurdebus', 5),
    ('Chauffeur de direction', 'chauffeurdedirection', 5),
    ('Chauffeur de maître', 'chauffeurdemaitre', 5),
    ('Chauffeur de poids-lourd', 'chauffeurdepoids-lourd', 5),
    ('Chauffeur de taxi', 'chauffeurdetaxi', 5),
    ('Chauffeur livreur', 'chauffeurlivreur', 5),
    ('Chauffeur personnel', 'chauffeurpersonnel', 5),
    ('Chauffeur routier', 'chauffeurroutier', 5),
    ('Chauffeur-livreur', 'chauffeur-livreur', 5),
    ('Chaumier', 'chaumier', 5),
    ('Chausseur', 'chausseur', 5),
    ('Chaîniste', 'chainiste', 5),
    ('Chef cuisinier', 'chefcuisinier', 5),
    ('Chef de cabinet', 'chefdecabinet', 5),
    ('Chef de caisse', 'chefdecaisse', 5),
    ('Chef de car', 'chefdecar', 5),
    ('Chef de chantier', 'chefdechantier', 5),
    ('Chef de chœur', 'chefdechœur', 5),
    ('Chef de comptoir', 'chefdecomptoir', 5),
    ('Chef de cuisine', 'chefdecuisine', 5),
    ('Chef de fabrication', 'chefdefabrication', 5),
    ('Chef de gare', 'chefdegare', 5),
    ('Chef de groupe', 'chefdegroupe', 5),
    ('Chef de laboratoire', 'chefdelaboratoire', 5),
    ('Chef de l’information', 'chefdel’information', 5),
    ('Chef de marché', 'chefdemarche', 5),
    ('Chef de mission humanitaire', 'chefdemissionhumanitaire', 5),
    ('Chef de partie', 'chefdepartie', 5),
    ('Chef de produit', 'chefdeproduit', 5),
    ('Chef de produit Web', 'chefdeproduitweb', 5),
    ('Chef de produit industriel', 'chefdeproduitindustriel', 5),
    ('Chef de produit sportif', 'chefdeproduitsportif', 5),
    ('Chef de produits', 'chefdeproduits', 5),
    ('Chef de produits voyages', 'chefdeproduitsvoyages', 5),
    ('Chef de projet', 'chefdeprojet', 5),
    ('Chef de projet MOA', 'chefdeprojetmoa', 5),
    ('Chef de projet MOE', 'chefdeprojetmoe', 5),
    ('Chef de projet consultant', 'chefdeprojetconsultant', 5),
    ('Chef de projet digital', 'chefdeprojetdigital', 5),
    ('Chef de projet e-CRM', 'chefdeprojete-crm', 5),
    ('Chef de projet e-business', 'chefdeprojete-business', 5),
    ('Chef de projet e-recrutement', 'chefdeprojete-recrutement', 5),
    ('Chef de projet eSport', 'chefdeprojetesport', 5),
    ('Chef de projet informatique', 'chefdeprojetinformatique', 5),
    ('Chef de projet marketing', 'chefdeprojetmarketing', 5),
    ('Chef de projet marketing digital', 'chefdeprojetmarketingdigital', 5),
    ('Chef de projet web', 'chefdeprojetweb', 5),
    ('Chef de projet événementiel', 'chefdeprojetevenementiel', 5),
    ('Chef de promotion', 'chefdepromotion', 5),
    ('Chef de pub', 'chefdepub', 5),
    ('Chef de publicité', 'chefdepublicite', 5),
    ('Chef de rang', 'chefderang', 5),
    ('Chef de rayon', 'chefderayon', 5),
    ('Chef de rubrique', 'chefderubrique', 5),
    ('Chef de secteur', 'chefdesecteur', 5),
    ('Chef de service', 'chefdeservice', 5),
    ('Chef de train funiculaire', 'chefdetrainfuniculaire', 5),
    ('Chef de travaux', 'chefdetravaux', 5),
    ('Chef des ventes', 'chefdesventes', 5),
    ('Chef décorateur', 'chefdecorateur', 5),
    ('Chef d’escale', 'chefd’escale', 5),
    ('Chef d’exploitation', 'chefd’exploitation', 5),
    ('Chef d’orchestre', 'chefd’orchestre', 5),
    ('Chef d’établissement', 'chefd’etablissement', 5),
    ('Chef mécanicien', 'chefmecanicien', 5),
    ('Chef opérateur', 'chefoperateur', 5),
    ('Chef réceptionniste', 'chefreceptionniste', 5),
    ('Chefs de chantier', 'chefsdechantier', 5),
    ('Chercheur', 'chercheur', 5),
    ('Chief Digital Officer', 'chiefdigitalofficer', 5),
    ('Chimiste', 'chimiste', 5),
    ('Chiropracteur', 'chiropracteur', 5),
    ('Chirurgien', 'chirurgien', 5),
    ('Chirurgien dentiste', 'chirurgiendentiste', 5),
    ('Chirurgien esthétique', 'chirurgienesthetique', 5),
    ('Chirurgien orthopédiste', 'chirurgienorthopediste', 5),
    ('Chirurgien-dentiste', 'chirurgien-dentiste', 5),
    ('Chocolatier', 'chocolatier', 5),
    ('Chocolatier – Confiseur', 'chocolatier–confiseur', 5),
    ('Chocolatier-confiseur', 'chocolatier-confiseur', 5),
    ('Chorégraphe', 'choregraphe', 5),
    ('Chromiste', 'chromiste', 5),
    ('Cirier', 'cirier', 5),
    ('Ciseleur', 'ciseleur', 5),
    ('Claviste', 'claviste', 5),
    ('Clerc de notaire', 'clercdenotaire', 5),
    ('Clerc d’huissier', 'clercd’huissier', 5),
    ('Clown', 'clown', 5),
    ('Coach', 'coach', 5),
    ('Coach Sportif', 'coachsportif', 5),
    ('Coach beauté', 'coachbeaute', 5),
    ('Coach bien-être', 'coachbien-etre', 5),
    ('Coach couple', 'coachcouple', 5),
    ('Coach de fitness', 'coachdefitness', 5),
    ('Coach de vie', 'coachdevie', 5),
    ('Coach déco', 'coachdeco', 5),
    ('Coach eSport', 'coachesport', 5),
    ('Coach en entreprise', 'coachenentreprise', 5),
    ('Coach parental', 'coachparental', 5),
    ('Coach professionnel', 'coachprofessionnel', 5),
    ('Coach scolaire', 'coachscolaire', 5),
    ('Coffreur-boiseur', 'coffreur-boiseur', 5),
    ('Cogniticien', 'cogniticien', 5),
    ('Coiffeur', 'coiffeur', 5),
    ('Coiffeur/coiffeuse', 'coiffeur/coiffeuse', 5),
    ('Collaborateur de cabinet', 'collaborateurdecabinet', 5),
    ('Collaborateur parlementaire', 'collaborateurparlementaire', 5),
    ('Commandant de bord', 'commandantdebord', 5),
    ('Commercial', 'commercial', 5),
    ('Commercial en informatique', 'commercialeninformatique', 5),
    ('Commercial télécoms', 'commercialtelecoms', 5),
    ('Commerçant', 'commercant', 5),
    ('Commerçant franchisé', 'commercantfranchise', 5),
    ('Commis', 'commis', 5),
    ('Commis de cuisine', 'commisdecuisine', 5),
    ('Commissaire aux comptes', 'commissaireauxcomptes', 5),
    ('Commissaire de police', 'commissairedepolice', 5),
    ('Commissaire des armées', 'commissairedesarmees', 5),
    ('Commissaire d’exposition', 'commissaired’exposition', 5),
    ('Commissaire priseur', 'commissairepriseur', 5),
    ('Communication', 'communication', 5),
    ('Community Manager', 'communitymanager', 5),
    ('Comportementalisme', 'comportementalisme', 5),
    ('Comportementaliste', 'comportementaliste', 5),
    ('Comportementaliste animalier', 'comportementalisteanimalier', 5),
    ('Compositeur', 'compositeur', 5),
    ('Compositeur de musique', 'compositeurdemusique', 5),
    ('Comptabilité', 'comptabilite', 5),
    ('Comptable', 'comptable', 5),
    ('Comptable immobilier', 'comptableimmobilier', 5),
    ('Comédien', 'comedien', 5),
    ('Concept artist', 'conceptartist', 5),
    ('Concepteur', 'concepteur', 5),
    ('Concepteur de jeux vidéos', 'concepteurdejeuxvideos', 5),
    ('Concepteur numérique', 'concepteurnumerique', 5),
    ('Concepteur rédacteur', 'concepteurredacteur', 5),
    ('Concepteur web', 'concepteurweb', 5),
    ('Concepteur-rédacteur', 'concepteur-redacteur', 5),
    ('Conchyliculteur', 'conchyliculteur', 5),
    ('Concierge de grand hôtel', 'conciergedegrandhotel', 5),
    ('Concierge d’entreprise', 'concierged’entreprise', 5),
    ('Concierge d’hôtel', 'concierged’hotel', 5),
    ('Conducteur', 'conducteur', 5),
    ('Conducteur de bus', 'conducteurdebus', 5),
    ('Conducteur de grue', 'conducteurdegrue', 5),
    ('Conducteur de machines agricoles', 'conducteurdemachinesagricoles', 5),
    ('Conducteur de métro', 'conducteurdemetro', 5),
    ('Conducteur de train', 'conducteurdetrain', 5),
    ('Conducteur de trains', 'conducteurdetrains', 5),
    ('Conducteur de tram', 'conducteurdetram', 5),
    ('Conducteur de tramway', 'conducteurdetramway', 5),
    ('Conducteur de travaux', 'conducteurdetravaux', 5),
    ('Conducteur d’engins de chantier', 'conducteurd’enginsdechantier', 5),
    ('Conducteur routier', 'conducteurroutier', 5),
    ('Confiseur', 'confiseur', 5),
    ('Conseiller', 'conseiller', 5),
    ('Conseiller agricole', 'conseilleragricole', 5),
    ('Conseiller conjugal', 'conseillerconjugal', 5),
    ('Conseiller culturel', 'conseillerculturel', 5),
    ('Conseiller de gestion agricole', 'conseillerdegestionagricole', 5),
    ('Conseiller de programme', 'conseillerdeprogramme', 5),
    ('Conseiller de vente luxe', 'conseillerdeventeluxe', 5),
    ('Conseiller d’insertion', 'conseillerd’insertion', 5),
    ('Conseiller d’orientation', 'conseillerd’orientation', 5),
    ('Conseiller d’orientation psychologue', 'conseillerd’orientationpsychologue', 5),
    ('Conseiller d’éducation', 'conseillerd’education', 5),
    ('Conseiller en Insertion Professionnelle', 'conseillereninsertionprofessionnelle', 5),
    ('Conseiller en assurances', 'conseillerenassurances', 5),
    ('Conseiller en beauté', 'conseillerenbeaute', 5),
    ('Conseiller en développement', 'conseillerendeveloppement', 5),
    ('Conseiller en environnement', 'conseillerenenvironnement', 5),
    ('Conseiller en gestion des RH', 'conseillerengestiondesrh', 5),
    ('Conseiller en image', 'conseillerenimage', 5),
    ('Conseiller en vente directe', 'conseillerenventedirecte', 5),
    ('Conseiller en économie sociale', 'conseillereneconomiesociale', 5),
    ('Conseiller en économie sociale et familiale', 'conseillereneconomiesocialeetfamiliale', 5),
    ('Conseiller en économie sociale et familiale (CESF)', 'conseillereneconomiesocialeetfamiliale(cesf)', 5),
    ('Conseiller familial', 'conseillerfamilial', 5),
    ('Conseiller financier', 'conseillerfinancier', 5),
    ('Conseiller fiscal', 'conseillerfiscal', 5),
    ('Conseiller funéraire', 'conseillerfuneraire', 5),
    ('Conseiller général', 'conseillergeneral', 5),
    ('Conseiller info-énergie', 'conseillerinfo-energie', 5),
    ('Conseiller municipal', 'conseillermunicipal', 5),
    ('Conseiller national', 'conseillernational', 5),
    ('Conseiller principal d’éducation', 'conseillerprincipald’education', 5),
    ('Conseiller professionnel', 'conseillerprofessionnel', 5),
    ('Conseiller régional', 'conseillerregional', 5),
    ('Conseiller viticole', 'conseillerviticole', 5),
    ('Conseiller à la sécurité', 'conseilleralasecurite', 5),
    ('Conseillère / conseiller en image', 'conseillere/conseillerenimage', 5),
    ('Conseillère de vente beauté', 'conseilleredeventebeaute', 5),
    ('Conservateur de bibliothèque', 'conservateurdebibliotheque', 5),
    ('Conservateur de musée', 'conservateurdemusee', 5),
    ('Conservateur des archives', 'conservateurdesarchives', 5),
    ('Conservateur du patrimoine', 'conservateurdupatrimoine', 5),
    ('Consolideur', 'consolideur', 5),
    ('Consultant', 'consultant', 5),
    ('Consultant IT', 'consultantit', 5),
    ('Consultant SAAS', 'consultantsaas', 5),
    ('Consultant bien-être', 'consultantbien-etre', 5),
    ('Consultant e-business', 'consultante-business', 5),
    ('Consultant e-commerce', 'consultante-commerce', 5),
    ('Consultant en informatique', 'consultanteninformatique', 5),
    ('Consultant en ingénierie touristique et culturelle', 'consultanteningenierietouristiqueetculturelle', 5),
    ('Consultant en recrutement', 'consultantenrecrutement', 5),
    ('Consultant en stratégie', 'consultantenstrategie', 5),
    ('Consultant en tourisme', 'consultantentourisme', 5),
    ('Consultant informatique', 'consultantinformatique', 5),
    ('Consultant prologiciel', 'consultantprologiciel', 5),
    ('Consultant technique', 'consultanttechnique', 5),
    ('Consultant web analytic', 'consultantwebanalytic', 5),
    ('Content manager', 'contentmanager', 5),
    ('Conteur', 'conteur', 5),
    ('Contrebandier', 'contrebandier', 5),
    ('Contremaître', 'contremaitre', 5),
    ('Contrôleur', 'controleur', 5),
    ('Contrôleur (trains)', 'controleur(trains)', 5),
    ('Contrôleur aérien', 'controleuraerien', 5),
    ('Contrôleur de gestion', 'controleurdegestion', 5),
    ('Contrôleur de travaux', 'controleurdetravaux', 5),
    ('Contrôleur des douanes', 'controleurdesdouanes', 5),
    ('Contrôleur des finances publiques', 'controleurdesfinancespubliques', 5),
    ('Contrôleur des risques', 'controleurdesrisques', 5),
    ('Contrôleur du travail', 'controleurdutravail', 5),
    ('Contrôleur financier', 'controleurfinancier', 5),
    ('Contrôleur qualité', 'controleurqualite', 5),
    ('Contrôleur sinistres', 'controleursinistres', 5),
    ('Contrôleur technique', 'controleurtechnique', 5),
    ('Convoyeur de fonds', 'convoyeurdefonds', 5),
    ('Convoyeur de l’air', 'convoyeurdel’air', 5),
    ('Coordinateur de crèches', 'coordinateurdecreches', 5),
    ('Coordinateur de production', 'coordinateurdeproduction', 5),
    ('Coordinateur social', 'coordinateursocial', 5),
    ('Coordonnateur SPS', 'coordonnateursps', 5),
    ('Copiste', 'copiste', 5),
    ('Cordiste', 'cordiste', 5),
    ('Cordonnier', 'cordonnier', 5),
    ('Correcteur', 'correcteur', 5),
    ('Correspondant Informatique', 'correspondantinformatique', 5),
    ('Correspondant local', 'correspondantlocal', 5),
    ('Corsetier', 'corsetier', 5),
    ('Cosmonaute', 'cosmonaute', 5),
    ('Costumier', 'costumier', 5),
    ('Coupeur', 'coupeur', 5),
    ('Coursier', 'coursier', 5),
    ('Courtier', 'courtier', 5),
    ('Courtier d’assurances', 'courtierd’assurances', 5),
    ('Courtier en assurance', 'courtierenassurance', 5),
    ('Courtier en assurances', 'courtierenassurances', 5),
    ('Courtier en bourse', 'courtierenbourse', 5),
    ('Courtier en travaux', 'courtierentravaux', 5),
    ('Courtier prêts immobiliers', 'courtierpretsimmobiliers', 5),
    ('Coutelier', 'coutelier', 5),
    ('Couturier', 'couturier', 5),
    ('Couvreur', 'couvreur', 5),
    ('Couvreur – zingueur', 'couvreur–zingueur', 5),
    ('Couvreur-zingueur', 'couvreur-zingueur', 5),
    ('Credit manager', 'creditmanager', 5),
    ('Critique de cinéma', 'critiquedecinema', 5),
    ('Critique d’art', 'critiqued’art', 5),
    ('Critique gastronomique', 'critiquegastronomique', 5),
    ('Critique littéraire', 'critiquelitteraire', 5),
    ('Croupier', 'croupier', 5),
    ('Cryptologue', 'cryptologue', 5),
    ('Créateur', 'createur', 5),
    ('Créateur de mode', 'createurdemode', 5),
    ('Créateur de parfum', 'createurdeparfum', 5),
    ('Crémier', 'cremier', 5),
    ('Crêpier', 'crepier', 5),
    ('Cueilleur', 'cueilleur', 5),
    ('Cuisinier', 'cuisinier', 5),
    ('Cuisiniste', 'cuisiniste', 5),
    ('Cultivateur', 'cultivateur', 5),
    ('Cyberdocumentaliste', 'cyberdocumentaliste', 5),
    ('Céramiste', 'ceramiste', 5),
    ('Céréalier', 'cerealier', 5),
    ('DJ', 'dj', 5),
    ('DRH', 'drh', 5),
    ('Dalleur', 'dalleur', 5),
    ('Dameur', 'dameur', 5),
    ('Danseur', 'danseur', 5),
    ('Data analyst', 'dataanalyst', 5),
    ('Data journaliste', 'datajournaliste', 5),
    ('Data protection officer', 'dataprotectionofficer', 5),
    ('Data scientist', 'datascientist', 5),
    ('Dealer (de drogue)', 'dealer(dedrogue)', 5),
    ('Dentellier', 'dentellier', 5),
    ('Dentiste', 'dentiste', 5),
    ('Dermatologue', 'dermatologue', 5),
    ('Designer', 'designer', 5),
    ('Designer céramique', 'designerceramique', 5),
    ('Designer de mode', 'designerdemode', 5),
    ('Designer de réalité virtuelle', 'designerderealitevirtuelle', 5),
    ('Designer d’interaction', 'designerd’interaction', 5),
    ('Designer graphique', 'designergraphique', 5),
    ('Designer graphiste', 'designergraphiste', 5),
    ('Designer industriel', 'designerindustriel', 5),
    ('Designer manager', 'designermanager', 5),
    ('Designer mobilier', 'designermobilier', 5),
    ('Designer numérique', 'designernumerique', 5),
    ('Designer packaging', 'designerpackaging', 5),
    ('Designer produit', 'designerproduit', 5),
    ('Designer sonore', 'designersonore', 5),
    ('Designer textile', 'designertextile', 5),
    ('Dessinateur', 'dessinateur', 5),
    ('Dessinateur de bande dessinées', 'dessinateurdebandedessinees', 5),
    ('Dessinateur de presse', 'dessinateurdepresse', 5),
    ('Dessinateur industriel', 'dessinateurindustriel', 5),
    ('Dessinateur projecteur FTTH', 'dessinateurprojecteurftth', 5),
    ('Diacre', 'diacre', 5),
    ('Diagnostiqueur immobilier', 'diagnostiqueurimmobilier', 5),
    ('Dialoguiste', 'dialoguiste', 5),
    ('Diamantaire', 'diamantaire', 5),
    ('Digital Evangelist', 'digitalevangelist', 5),
    ('Dinancier', 'dinancier', 5),
    ('Dinandier', 'dinandier', 5),
    ('Diplomate', 'diplomate', 5),
    ('Directeur', 'directeur', 5),
    ('Directeur RH', 'directeurrh', 5),
    ('Directeur administratif', 'directeuradministratif', 5),
    ('Directeur administratif et financier', 'directeuradministratifetfinancier', 5),
    ('Directeur artistique', 'directeurartistique', 5),
    ('Directeur artistique web', 'directeurartistiqueweb', 5),
    ('Directeur commercial', 'directeurcommercial', 5),
    ('Directeur de boutique', 'directeurdeboutique', 5),
    ('Directeur de cabinet', 'directeurdecabinet', 5),
    ('Directeur de cabinet de conseil', 'directeurdecabinetdeconseil', 5),
    ('Directeur de casino', 'directeurdecasino', 5),
    ('Directeur de casting', 'directeurdecasting', 5),
    ('Directeur de clientèle', 'directeurdeclientele', 5),
    ('Directeur de collection', 'directeurdecollection', 5),
    ('Directeur de communication', 'directeurdecommunication', 5),
    ('Directeur de conservatoire', 'directeurdeconservatoire', 5),
    ('Directeur de crèche', 'directeurdecreche', 5),
    ('Directeur de création', 'directeurdecreation', 5),
    ('Directeur de festival', 'directeurdefestival', 5),
    ('Directeur de foires', 'directeurdefoires', 5),
    ('Directeur de galerie', 'directeurdegalerie', 5),
    ('Directeur de la photographie', 'directeurdelaphotographie', 5),
    ('Directeur de la restauration', 'directeurdelarestauration', 5),
    ('Directeur de magasin de sport', 'directeurdemagasindesport', 5),
    ('Directeur de marché', 'directeurdemarche', 5),
    ('Directeur de musée', 'directeurdemusee', 5),
    ('Directeur de parc zoologique', 'directeurdeparczoologique', 5),
    ('Directeur de post-production', 'directeurdepost-production', 5),
    ('Directeur de production', 'directeurdeproduction', 5),
    ('Directeur de projets', 'directeurdeprojets', 5),
    ('Directeur de radio', 'directeurderadio', 5),
    ('Directeur de réseau', 'directeurdereseau', 5),
    ('Directeur de réseau d’agences', 'directeurdereseaud’agences', 5),
    ('Directeur de site culturel', 'directeurdesiteculturel', 5),
    ('Directeur de site industriel', 'directeurdesiteindustriel', 5),
    ('Directeur de structure jeunesse', 'directeurdestructurejeunesse', 5),
    ('Directeur de supermarché', 'directeurdesupermarche', 5),
    ('Directeur des Ressources Humaines', 'directeurdesressourceshumaines', 5),
    ('Directeur des achats', 'directeurdesachats', 5),
    ('Directeur des engagements', 'directeurdesengagements', 5),
    ('Directeur des opérations', 'directeurdesoperations', 5),
    ('Directeur des services pénitentiaires', 'directeurdesservicespenitentiaires', 5),
    ('Directeur des sports', 'directeurdessports', 5),
    ('Directeur des ventes', 'directeurdesventes', 5),
    ('Directeur du marketing', 'directeurdumarketing', 5),
    ('Directeur d’agence', 'directeurd’agence', 5),
    ('Directeur d’agence bancaire', 'directeurd’agencebancaire', 5),
    ('Directeur d’agence de gestion', 'directeurd’agencedegestion', 5),
    ('Directeur d’exploitation', 'directeurd’exploitation', 5),
    ('Directeur d’exposition', 'directeurd’exposition', 5),
    ('Directeur d’hébergement', 'directeurd’hebergement', 5),
    ('Directeur d’hôpital', 'directeurd’hopital', 5),
    ('Directeur d’hôtel', 'directeurd’hotel', 5),
    ('Directeur d’investissements', 'directeurd’investissements', 5),
    ('Directeur d’un hôtel de luxe', 'directeurd’unhoteldeluxe', 5),
    ('Directeur d’un office de tourisme', 'directeurd’unofficedetourisme', 5),
    ('Directeur d’une PME', 'directeurd’unepme', 5),
    ('Directeur d’école', 'directeurd’ecole', 5),
    ('Directeur d’études', 'directeurd’etudes', 5),
    ('Directeur environnement', 'directeurenvironnement', 5),
    ('Directeur financier', 'directeurfinancier', 5),
    ('Directeur marketing', 'directeurmarketing', 5),
    ('Directeur marketing touristique', 'directeurmarketingtouristique', 5),
    ('Directeur médical', 'directeurmedical', 5),
    ('Directeur régional des ventes', 'directeurregionaldesventes', 5),
    ('Directeur technique', 'directeurtechnique', 5),
    ('Directeur éditorial', 'directeureditorial', 5),
    ('Disquaire', 'disquaire', 5),
    ('Diététicien', 'dieteticien', 5),
    ('Docker', 'docker', 5),
    ('Docteur', 'docteur', 5),
    ('Documentaliste', 'documentaliste', 5),
    ('Documentaliste TV', 'documentalistetv', 5),
    ('Dominotier', 'dominotier', 5),
    ('Domoticien', 'domoticien', 5),
    ('Dompteur', 'dompteur', 5),
    ('Doreur', 'doreur', 5),
    ('Doreur sur cuir', 'doreursurcuir', 5),
    ('Doreur sur tranche', 'doreursurtranche', 5),
    ('Douanier', 'douanier', 5),
    ('Dresseur dans les cirques', 'dresseurdanslescirques', 5),
    ('Droguiste', 'droguiste', 5),
    ('Droit industriel', 'droitindustriel', 5),
    ('Drone Data Analyst', 'dronedataanalyst', 5),
    ('Déclarant en douane', 'declarantendouane', 5),
    ('Décorateur', 'decorateur', 5),
    ('Décorateur / décoratrice d’intérieur', 'decorateur/decoratriced’interieur', 5),
    ('Décorateur d’intérieur', 'decorateurd’interieur', 5),
    ('Décorateur en résine', 'decorateurenresine', 5),
    ('Décorateur-scénographe', 'decorateur-scenographe', 5),
    ('Décorateur-étalagiste', 'decorateur-etalagiste', 5),
    ('Délégué médical', 'deleguemedical', 5),
    ('Délégué pharmaceutique', 'deleguepharmaceutique', 5),
    ('Délégué pharmaceutique / Visiteur médical', 'deleguepharmaceutique/visiteurmedical', 5),
    ('Délégué à la tutelle', 'deleguealatutelle', 5),
    ('Démineur', 'demineur', 5),
    ('Démographe', 'demographe', 5),
    ('Démolisseur', 'demolisseur', 5),
    ('Démonstrateur', 'demonstrateur', 5),
    ('Démonstrateur de marque', 'demonstrateurdemarque', 5),
    ('Déménageur', 'demenageur', 5),
    ('Déontologue', 'deontologue', 5),
    ('Dépanneur', 'depanneur', 5),
    ('Dépanneur-remorqueur', 'depanneur-remorqueur', 5),
    ('Député', 'depute', 5),
    ('Détaillant', 'detaillant', 5),
    ('Détective', 'detective', 5),
    ('Détective privé', 'detectiveprive', 5),
    ('Développeur', 'developpeur', 5),
    ('Développeur base de données', 'developpeurbasededonnees', 5),
    ('Développeur de produits', 'developpeurdeproduits', 5),
    ('Développeur d’enseigne', 'developpeurd’enseigne', 5),
    ('Développeur informatique', 'developpeurinformatique', 5),
    ('Développeur multimédia', 'developpeurmultimedia', 5),
    ('Développeur rural', 'developpeurrural', 5),
    ('Développeur web', 'developpeurweb', 5),
    ('Développeur économique', 'developpeureconomique', 5),
    ('E-consultant interne', 'e-consultantinterne', 5),
    ('E-sportif', 'e-sportif', 5),
    ('ESportif', 'esportif', 5),
    ('Ebéniste', 'ebeniste', 5),
    ('Echafaudeur', 'echafaudeur', 5),
    ('Economiste', 'economiste', 5),
    ('Ecrivain public', 'ecrivainpublic', 5),
    ('Educateur canin', 'educateurcanin', 5),
    ('Educateur de chiens guides', 'educateurdechiensguides', 5),
    ('Educateur de jeunes', 'educateurdejeunes', 5),
    ('Educateur de jeunes enfants', 'educateurdejeunesenfants', 5),
    ('Educateur spécialisé', 'educateurspecialise', 5),
    ('Electricien', 'electricien', 5),
    ('Electromécanicien', 'electromecanicien', 5),
    ('Electronicien automobile', 'electronicienautomobile', 5),
    ('Eleveur', 'eleveur', 5),
    ('Eleveur chiens et chats', 'eleveurchiensetchats', 5),
    ('Eleveur de chevaux', 'eleveurdechevaux', 5),
    ('Emballeur professionnel', 'emballeurprofessionnel', 5),
    ('Employé', 'employe', 5),
    ('Employé administratif', 'employeadministratif', 5),
    ('Employé de banque', 'employedebanque', 5),
    ('Employé de parc de loisirs', 'employedeparcdeloisirs', 5),
    ('Employé des parcs nationaux', 'employedesparcsnationaux', 5),
    ('Employé d’assurance', 'employed’assurance', 5),
    ('Employé libre-service', 'employelibre-service', 5),
    ('Encadreur', 'encadreur', 5),
    ('Enlumineur', 'enlumineur', 5),
    ('Enseignant', 'enseignant', 5),
    ('Enseignant animateur équestre', 'enseignantanimateurequestre', 5),
    ('Enseignant-chercheur', 'enseignant-chercheur', 5),
    ('Ensemblier', 'ensemblier', 5),
    ('Entraîneur', 'entraineur', 5),
    ('Entraîneur équestre', 'entraineurequestre', 5),
    ('Entraîneur-Educateur de football', 'entraineur-educateurdefootball', 5),
    ('Entraîneur-Educateur de rugby', 'entraineur-educateurderugby', 5),
    ('Entremétier', 'entremetier', 5),
    ('Entreposeur', 'entreposeur', 5),
    ('Ergonome', 'ergonome', 5),
    ('Ergonome Web', 'ergonomeweb', 5),
    ('Ergonome du logiciel', 'ergonomedulogiciel', 5),
    ('Ergothérapeute', 'ergotherapeute', 5),
    ('Escaliéteur', 'escalieteur', 5),
    ('Esclavagiste', 'esclavagiste', 5),
    ('Espion', 'espion', 5),
    ('Esthéticien(ne)', 'estheticien(ne)', 5),
    ('Esthéticienne', 'estheticienne', 5),
    ('Ethnologue', 'ethnologue', 5),
    ('Etiopathe', 'etiopathe', 5),
    ('Exobiologiste', 'exobiologiste', 5),
    ('Expert automobile', 'expertautomobile', 5),
    ('Expert comptable', 'expertcomptable', 5),
    ('Expert d’art', 'expertd’art', 5),
    ('Expert d’infrastructure', 'expertd’infrastructure', 5),
    ('Expert en sécurité', 'expertensecurite', 5),
    ('Expert immobilier', 'expertimmobilier', 5),
    ('Expert incendies et risques', 'expertincendiesetrisques', 5),
    ('Expert judiciaire', 'expertjudiciaire', 5),
    ('Expert naturaliste', 'expertnaturaliste', 5),
    ('Expert-comptable', 'expert-comptable', 5),
    ('Explorateur', 'explorateur', 5),
    ('Exécutant', 'executant', 5),
    ('Fabricant', 'fabricant', 5),
    ('Fabricant de carreaux', 'fabricantdecarreaux', 5),
    ('Fabricant de papier', 'fabricantdepapier', 5),
    ('Fabricant de papier peint', 'fabricantdepapierpeint', 5),
    ('Facility manager', 'facilitymanager', 5),
    ('Facteur', 'facteur', 5),
    ('Facteur d’instrument', 'facteurd’instrument', 5),
    ('Facteur d’instruments', 'facteurd’instruments', 5),
    ('Fauconnier', 'fauconnier', 5),
    ('Faussaire', 'faussaire', 5),
    ('Façadier', 'facadier', 5),
    ('Faïencier', 'faiencier', 5),
    ('Femme de chambre', 'femmedechambre', 5),
    ('Femme de ménage', 'femmedemenage', 5),
    ('Fermier', 'fermier', 5),
    ('Ferrailleur', 'ferrailleur', 5),
    ('Ferronnier', 'ferronnier', 5),
    ('Ferronnier d’art', 'ferronnierd’art', 5),
    ('Ferronnier-forgeron', 'ferronnier-forgeron', 5),
    ('Feutrier', 'feutrier', 5),
    ('Figurant', 'figurant', 5),
    ('Fiscaliste', 'fiscaliste', 5),
    ('Flash designer', 'flashdesigner', 5),
    ('Flasheur', 'flasheur', 5),
    ('Fleuriste', 'fleuriste', 5),
    ('Fondeur', 'fondeur', 5),
    ('Fondeur de caractères', 'fondeurdecaracteres', 5),
    ('Fondeur d’étain', 'fondeurd’etain', 5),
    ('Fontainier', 'fontainier', 5),
    ('Forain', 'forain', 5),
    ('Forfaitiste', 'forfaitiste', 5),
    ('Forgeron', 'forgeron', 5),
    ('Formateur', 'formateur', 5),
    ('Formateur pour Adultes', 'formateurpouradultes', 5),
    ('Formier', 'formier', 5),
    ('Formulateur', 'formulateur', 5),
    ('Fossoyeur', 'fossoyeur', 5),
    ('Fournisseur', 'fournisseur', 5),
    ('Fourreur', 'fourreur', 5),
    ('Fresquiste', 'fresquiste', 5),
    ('Frigoriste', 'frigoriste', 5),
    ('Fromager', 'fromager', 5),
    ('Fromager-Crémier', 'fromager-cremier', 5),
    ('Funambule', 'funambule', 5),
    ('Fundraiser', 'fundraiser', 5),
    ('Féron', 'feron', 5),
    ('Gainier', 'gainier', 5),
    ('Galeriste', 'galeriste', 5),
    ('Game designer', 'gamedesigner', 5),
    ('Game director', 'gamedirector', 5),
    ('Gantier', 'gantier', 5),
    ('Garagiste', 'garagiste', 5),
    ('Garde chasse', 'gardechasse', 5),
    ('Garde du corps', 'gardeducorps', 5),
    ('Garde du littoral', 'gardedulittoral', 5),
    ('Garde forestier', 'gardeforestier', 5),
    ('Garde pêche', 'gardepeche', 5),
    ('Garde-champêtre', 'garde-champetre', 5),
    ('Garde-chasse', 'garde-chasse', 5),
    ('Garde-manger', 'garde-manger', 5),
    ('Garde-moniteur du parc national', 'garde-moniteurduparcnational', 5),
    ('Garde-pêche', 'garde-peche', 5),
    ('Gardien', 'gardien', 5),
    ('Gardien de la paix', 'gardiendelapaix', 5),
    ('Gardien d’immeuble', 'gardiend’immeuble', 5),
    ('Garçon de café', 'garcondecafe', 5),
    ('Gemmologue', 'gemmologue', 5),
    ('Gendarme', 'gendarme', 5),
    ('Gendarme adjoint volontaire', 'gendarmeadjointvolontaire', 5),
    ('Gestion de patrimoine', 'gestiondepatrimoine', 5),
    ('Gestionnaire de carrière', 'gestionnairedecarriere', 5),
    ('Gestionnaire de contrats', 'gestionnairedecontrats', 5),
    ('Gestionnaire de copropriété', 'gestionnairedecopropriete', 5),
    ('Gestionnaire de paie', 'gestionnairedepaie', 5),
    ('Gestionnaire de parc informatique', 'gestionnairedeparcinformatique', 5),
    ('Gestionnaire de patrimoine', 'gestionnairedepatrimoine', 5),
    ('Gestionnaire de services', 'gestionnairedeservices', 5),
    ('Gestionnaire de stock', 'gestionnairedestock', 5),
    ('Gestionnaire d’actifs', 'gestionnaired’actifs', 5),
    ('Gestionnaire immobilier', 'gestionnaireimmobilier', 5),
    ('Gestionnaire locatif', 'gestionnairelocatif', 5),
    ('Glacier', 'glacier', 5),
    ('Glaciologue', 'glaciologue', 5),
    ('Glypticien', 'glypticien', 5),
    ('Gouvernante', 'gouvernante', 5),
    ('Gouvernante de maison', 'gouvernantedemaison', 5),
    ('Gouvernante d’étage', 'gouvernanted’etage', 5),
    ('Goûteur d’eau', 'gouteurd’eau', 5),
    ('Grand reporter', 'grandreporter', 5),
    ('Graphiste', 'graphiste', 5),
    ('Graphiste web', 'graphisteweb', 5),
    ('Graphologue', 'graphologue', 5),
    ('Graveur', 'graveur', 5),
    ('Graveur de poinçons', 'graveurdepoincons', 5),
    ('Graveur sur pierre', 'graveursurpierre', 5),
    ('Greffier', 'greffier', 5),
    ('Greffier/Greffière', 'greffier/greffiere', 5),
    ('Grossiste', 'grossiste', 5),
    ('Growth Hacker', 'growthhacker', 5),
    ('Grutier', 'grutier', 5),
    ('Guest relation manager', 'guestrelationmanager', 5),
    ('Guichetier', 'guichetier', 5),
    ('Guide Interprète', 'guideinterprete', 5),
    ('Guide accompagnateur', 'guideaccompagnateur', 5),
    ('Guide de haute montagne', 'guidedehautemontagne', 5),
    ('Guide touristique', 'guidetouristique', 5),
    ('Guide-accompagnateur', 'guide-accompagnateur', 5),
    ('Guide-conférencier', 'guide-conferencier', 5),
    ('Guide-interprète', 'guide-interprete', 5),
    ('Guillocheur', 'guillocheur', 5),
    ('Gynécologue', 'gynecologue', 5),
    ('Géochimiste', 'geochimiste', 5),
    ('Géographe', 'geographe', 5),
    ('Géologue', 'geologue', 5),
    ('Géomaticien', 'geomaticien', 5),
    ('Géomètre', 'geometre', 5),
    ('Géomètre expert', 'geometreexpert', 5),
    ('Géomètre topographe', 'geometretopographe', 5),
    ('Géophysicien', 'geophysicien', 5),
    ('Gérant de patrimoine', 'gerantdepatrimoine', 5),
    ('Gérant de portefeuille', 'gerantdeportefeuille', 5),
    ('Gérant d’hôtel', 'gerantd’hotel', 5),
    ('Habilleur', 'habilleur', 5),
    ('Hacker éthique', 'hackerethique', 5),
    ('Harpiste', 'harpiste', 5),
    ('Herboriste', 'herboriste', 5),
    ('Herpétologue', 'herpetologue', 5),
    ('Historien', 'historien', 5),
    ('Home stager', 'homestager', 5),
    ('Homme d’État', 'hommed’etat', 5),
    ('Homme politique', 'hommepolitique', 5),
    ('Homologateur', 'homologateur', 5),
    ('Horiculteur', 'horiculteur', 5),
    ('Horloger', 'horloger', 5),
    ('Horticulteur', 'horticulteur', 5),
    ('Hotliner', 'hotliner', 5),
    ('Huissier', 'huissier', 5),
    ('Huissier de justice', 'huissierdejustice', 5),
    ('Humoriste', 'humoriste', 5),
    ('Hydraulicien', 'hydraulicien', 5),
    ('Hydrobiologiste', 'hydrobiologiste', 5),
    ('Hydrogéologue', 'hydrogeologue', 5),
    ('Hydrothérapeute', 'hydrotherapeute', 5),
    ('Hydrothérapeute canin', 'hydrotherapeutecanin', 5),
    ('Hygiéniste dentaire', 'hygienistedentaire', 5),
    ('Hypnothérapeute', 'hypnotherapeute', 5),
    ('Hôtelier', 'hotelier', 5),
    ('Hôtelier-restaurateur', 'hotelier-restaurateur', 5),
    ('Hôtesse de l’air', 'hotessedel’air', 5),
    ('Hôtesse de l’air, steward', 'hotessedel’air,steward', 5),
    ('Hôtesse d’accueil', 'hotessed’accueil', 5),
    ('Iconographe', 'iconographe', 5),
    ('Illustrateur', 'illustrateur', 5),
    ('Illustrateur 3D', 'illustrateur3d', 5),
    ('Imagier au pochoir', 'imagieraupochoir', 5),
    ('Imam', 'imam', 5),
    ('Imitateur', 'imitateur', 5),
    ('Immersive designer', 'immersivedesigner', 5),
    ('Imprimeur', 'imprimeur', 5),
    ('Infirmier', 'infirmier', 5),
    ('Infirmier / Infirmière', 'infirmier/infirmiere', 5),
    ('Infirmier anesthésiste', 'infirmieranesthesiste', 5),
    ('Infirmier de bloc opératoire', 'infirmierdeblocoperatoire', 5),
    ('Infirmier en pratique avancée', 'infirmierenpratiqueavancee', 5),
    ('Infirmier scolaire', 'infirmierscolaire', 5),
    ('Infirmier-anesthésiste', 'infirmier-anesthesiste', 5),
    ('Infirmière', 'infirmiere', 5),
    ('Influenceur', 'influenceur', 5),
    ('Infographe', 'infographe', 5),
    ('Infographiste', 'infographiste', 5),
    ('Infopreneur', 'infopreneur', 5),
    ('Informaticien', 'informaticien', 5),
    ('Ingénieur', 'ingenieur', 5),
    ('Ingénieur Big data', 'ingenieurbigdata', 5),
    ('Ingénieur CFAO', 'ingenieurcfao', 5),
    ('Ingénieur agronome', 'ingenieuragronome', 5),
    ('Ingénieur analyste de l’air', 'ingenieuranalystedel’air', 5),
    ('Ingénieur biomécanique', 'ingenieurbiomecanique', 5),
    ('Ingénieur biomédical', 'ingenieurbiomedical', 5),
    ('Ingénieur calcul', 'ingenieurcalcul', 5),
    ('Ingénieur chimiste', 'ingenieurchimiste', 5),
    ('Ingénieur civil', 'ingenieurcivil', 5),
    ('Ingénieur cloud computing', 'ingenieurcloudcomputing', 5),
    ('Ingénieur cogniticien', 'ingenieurcogniticien', 5),
    ('Ingénieur commercial', 'ingenieurcommercial', 5),
    ('Ingénieur de fabrication', 'ingenieurdefabrication', 5),
    ('Ingénieur de recherche', 'ingenieurderecherche', 5),
    ('Ingénieur du BTP', 'ingenieurdubtp', 5),
    ('Ingénieur du son', 'ingenieurduson', 5),
    ('Ingénieur d’affaires', 'ingenieurd’affaires', 5),
    ('Ingénieur d’étude', 'ingenieurd’etude', 5),
    ('Ingénieur en aéronautique', 'ingenieurenaeronautique', 5),
    ('Ingénieur en dépollution', 'ingenieurendepollution', 5),
    ('Ingénieur en génie thermique', 'ingenieurengeniethermique', 5),
    ('Ingénieur en mécanique', 'ingenieurenmecanique', 5),
    ('Ingénieur environnement', 'ingenieurenvironnement', 5),
    ('Ingénieur financier', 'ingenieurfinancier', 5),
    ('Ingénieur fluides', 'ingenieurfluides', 5),
    ('Ingénieur forestier', 'ingenieurforestier', 5),
    ('Ingénieur génie industriel', 'ingenieurgenieindustriel', 5),
    ('Ingénieur hospitalier', 'ingenieurhospitalier', 5),
    ('Ingénieur informaticien', 'ingenieurinformaticien', 5),
    ('Ingénieur nutritionniste', 'ingenieurnutritionniste', 5),
    ('Ingénieur technico-commercial', 'ingenieurtechnico-commercial', 5),
    ('Ingénieur textile', 'ingenieurtextile', 5),
    ('Ingénieur télépilote', 'ingenieurtelepilote', 5),
    ('Ingénieur écologue', 'ingenieurecologue', 5),
    ('Ingénieur électricien', 'ingenieurelectricien', 5),
    ('Ingénieur électronicien', 'ingenieurelectronicien', 5),
    ('Ingénieur électrotechnicien', 'ingenieurelectrotechnicien', 5),
    ('Inhalothérapeute', 'inhalotherapeute', 5),
    ('Inspecteur', 'inspecteur', 5),
    ('Inspecteur commercial', 'inspecteurcommercial', 5),
    ('Inspecteur de la DGCCRF', 'inspecteurdeladgccrf', 5),
    ('Inspecteur de l’action sanitaire et sociale', 'inspecteurdel’actionsanitaireetsociale', 5),
    ('Inspecteur du travail', 'inspecteurdutravail', 5),
    ('Inspecteur d’académie', 'inspecteurd’academie', 5),
    ('Inspecteur en génie sanitaire', 'inspecteurengeniesanitaire', 5),
    ('Inspecteur-vérificateur', 'inspecteur-verificateur', 5),
    ('Instituteur', 'instituteur', 5),
    ('Instituteur / Professeur des écoles', 'instituteur/professeurdesecoles', 5),
    ('Interprète', 'interprete', 5),
    ('Intervenant en milieu scolaire', 'intervenantenmilieuscolaire', 5),
    ('Intégrateur', 'integrateur', 5),
    ('Intégrateur d’exploitation', 'integrateurd’exploitation', 5),
    ('Intégrateur web', 'integrateurweb', 5),
    ('Intégrateur web / développeur front-end', 'integrateurweb/developpeurfront-end', 5),
    ('Ivoirier', 'ivoirier', 5),
    ('Jardinier', 'jardinier', 5),
    ('Jardinier paysagiste', 'jardinierpaysagiste', 5),
    ('Joaillier', 'joaillier', 5),
    ('Jockey', 'jockey', 5),
    ('Jongleur', 'jongleur', 5),
    ('Journaliste', 'journaliste', 5),
    ('Journaliste de mode', 'journalistedemode', 5),
    ('Journaliste d’entreprise', 'journalisted’entreprise', 5),
    ('Journaliste pour une émission', 'journalistepouruneemission', 5),
    ('Journaliste radio', 'journalisteradio', 5),
    ('Journaliste reporter d’images', 'journalistereporterd’images', 5),
    ('Journaliste sportif', 'journalistesportif', 5),
    ('Journaliste web', 'journalisteweb', 5),
    ('Juge', 'juge', 5),
    ('Juge aux affaires familiales', 'jugeauxaffairesfamiliales', 5),
    ('Juge de l’application des peines', 'jugedel’applicationdespeines', 5),
    ('Juge des enfants', 'jugedesenfants', 5),
    ('Juge des tutelles', 'jugedestutelles', 5),
    ('Juge d’instance', 'juged’instance', 5),
    ('Juge d’instruction', 'juged’instruction', 5),
    ('Juriste', 'juriste', 5),
    ('Juriste agricole', 'juristeagricole', 5),
    ('Juriste dans les assurances', 'juristedanslesassurances', 5),
    ('Juriste dans l’immobilier', 'juristedansl’immobilier', 5),
    ('Juriste du sport', 'juristedusport', 5),
    ('Juriste d’entreprise', 'juristed’entreprise', 5),
    ('Juriste d’immobilier', 'juristed’immobilier', 5),
    ('Juriste en cybersécurité', 'juristeencybersecurite', 5),
    ('Juriste en droit immobilier', 'juristeendroitimmobilier', 5),
    ('Juriste social', 'juristesocial', 5),
    ('Kinésithérapeute', 'kinesitherapeute', 5),
    ('Kinésithérapeute du sport', 'kinesitherapeutedusport', 5),
    ('Kiosquier', 'kiosquier', 5),
    ('Laborantin', 'laborantin', 5),
    ('Lad-driver', 'lad-driver', 5),
    ('Lad-jockey', 'lad-jockey', 5),
    ('Laitier', 'laitier', 5),
    ('Lapidaire', 'lapidaire', 5),
    ('Laqueur', 'laqueur', 5),
    ('Laveur de vitre', 'laveurdevitre', 5),
    ('Layout artist', 'layoutartist', 5),
    ('Lead Game designer', 'leadgamedesigner', 5),
    ('Lecteur-correcteur', 'lecteur-correcteur', 5),
    ('Level designer', 'leveldesigner', 5),
    ('Libraire', 'libraire', 5),
    ('Lieutenant de police', 'lieutenantdepolice', 5),
    ('Lieutenant de pont', 'lieutenantdepont', 5),
    ('Lieutenant de sapeur-pompier', 'lieutenantdesapeur-pompier', 5),
    ('Lieutenant de sapeurs-pompiers', 'lieutenantdesapeurs-pompiers', 5),
    ('Lieutenant pénitentiaire', 'lieutenantpenitentiaire', 5),
    ('Lighting artist', 'lightingartist', 5),
    ('Limonadier', 'limonadier', 5),
    ('Linguiste', 'linguiste', 5),
    ('Lingère', 'lingere', 5),
    ('Linotypiste', 'linotypiste', 5),
    ('Lithographe', 'lithographe', 5),
    ('Livreur', 'livreur', 5),
    ('Lobbyiste', 'lobbyiste', 5),
    ('Localier', 'localier', 5),
    ('Logisticien', 'logisticien', 5),
    ('Logisticien humanitaire', 'logisticienhumanitaire', 5),
    ('Logisticien nucléaire', 'logisticiennucleaire', 5),
    ('Logistique', 'logistique', 5),
    ('Loueur d’équidés', 'loueurd’equides', 5),
    ('Love coach', 'lovecoach', 5),
    ('Ludlowiste', 'ludlowiste', 5),
    ('Lunetier', 'lunetier', 5),
    ('Luthier', 'luthier', 5),
    ('L’administration', 'l’administration', 5),
    ('Machiniste', 'machiniste', 5),
    ('Magasinier', 'magasinier', 5),
    ('Magicien', 'magicien', 5),
    ('Magistrat', 'magistrat', 5),
    ('Magnéticien', 'magneticien', 5),
    ('Magnétiseur', 'magnetiseur', 5),
    ('Maire', 'maire', 5),
    ('Major de sapeur-pompier', 'majordesapeur-pompier', 5),
    ('Majordome', 'majordome', 5),
    ('Manager dans la restauration', 'managerdanslarestauration', 5),
    ('Manager dans le luxe', 'managerdansleluxe', 5),
    ('Manager de centre', 'managerdecentre', 5),
    ('Manager de la marque', 'managerdelamarque', 5),
    ('Manager de la supply chain', 'managerdelasupplychain', 5),
    ('Manager de l’innovation', 'managerdel’innovation', 5),
    ('Manager des ressources', 'managerdesressources', 5),
    ('Manager eSport', 'manageresport', 5),
    ('Mandataire Liquidateur', 'mandataireliquidateur', 5),
    ('Mandataire immobilier', 'mandataireimmobilier', 5),
    ('Mandataire judiciaire', 'mandatairejudiciaire', 5),
    ('Mangaka', 'mangaka', 5),
    ('Manipulateur d’électroradiolog', 'manipulateurd’electroradiolog', 5),
    ('Manipulateur en électroradiologie médicale', 'manipulateurenelectroradiologiemedicale', 5),
    ('Manipulateur radio', 'manipulateurradio', 5),
    ('Mannequin', 'mannequin', 5),
    ('Manucure', 'manucure', 5),
    ('Manutentionnaire cariste', 'manutentionnairecariste', 5),
    ('Maquettiste', 'maquettiste', 5),
    ('Maquettiste automobile', 'maquettisteautomobile', 5),
    ('Maquilleur', 'maquilleur', 5),
    ('Maquilleur ( maquillage )', 'maquilleur(maquillage)', 5),
    ('Maquilleur professionnel', 'maquilleurprofessionnel', 5),
    ('Maraîcher', 'maraicher', 5),
    ('Marbrier', 'marbrier', 5),
    ('Marchand de journaux', 'marchanddejournaux', 5),
    ('Mareyeur', 'mareyeur', 5),
    ('Margeur', 'margeur', 5),
    ('Marin', 'marin', 5),
    ('Marin de la marine marchande', 'marindelamarinemarchande', 5),
    ('Marin pêcheur', 'marinpecheur', 5),
    ('Marinier', 'marinier', 5),
    ('Marionnettiste', 'marionnettiste', 5),
    ('Marketeur', 'marketeur', 5),
    ('Marketing', 'marketing', 5),
    ('Maroquinier', 'maroquinier', 5),
    ('Marqueteur', 'marqueteur', 5),
    ('Marqueteur de pailles', 'marqueteurdepailles', 5),
    ('Marqueteur de pierres dures', 'marqueteurdepierresdures', 5),
    ('Maréchal Ferrant', 'marechalferrant', 5),
    ('Maréchal-ferrant', 'marechal-ferrant', 5),
    ('Masseur', 'masseur', 5),
    ('Masseur / Masseuse', 'masseur/masseuse', 5),
    ('Masseur kinésithérapeute', 'masseurkinesitherapeute', 5),
    ('Massicotier', 'massicotier', 5),
    ('Mathématicien', 'mathematicien', 5),
    ('Matte painter', 'mattepainter', 5),
    ('Maçon', 'macon', 5),
    ('Maître chien', 'maitrechien', 5),
    ('Maître de chai', 'maitredechai', 5),
    ('Maître de conférence', 'maitredeconference', 5),
    ('Maître de conférences', 'maitredeconferences', 5),
    ('Maître d’hôtel', 'maitred’hotel', 5),
    ('Maître nageur sauveteur', 'maitrenageursauveteur', 5),
    ('Maître ouvrier', 'maitreouvrier', 5),
    ('Maître tailleur', 'maitretailleur', 5),
    ('Maître verrier', 'maitreverrier', 5),
    ('Maître-Chien', 'maitre-chien', 5),
    ('Maître-nageur', 'maitre-nageur', 5),
    ('Maître-ouvrier d’art', 'maitre-ouvrierd’art', 5),
    ('Maïeuticien', 'maieuticien', 5),
    ('Media planner', 'mediaplanner', 5),
    ('Menuisier', 'menuisier', 5),
    ('Menuisier en sièges', 'menuisierensieges', 5),
    ('Merchandiser', 'merchandiser', 5),
    ('Metteur en scène', 'metteurenscene', 5),
    ('Meunier', 'meunier', 5),
    ('Militaire', 'militaire', 5),
    ('Mime', 'mime', 5),
    ('Ministre', 'ministre', 5),
    ('Mixeur', 'mixeur', 5),
    ('Modeleur', 'modeleur', 5),
    ('Modiste', 'modiste', 5),
    ('Modélisateur', 'modelisateur', 5),
    ('Modéliste', 'modeliste', 5),
    ('Modérateur', 'moderateur', 5),
    ('Moniteur de plongée', 'moniteurdeplongee', 5),
    ('Moniteur de ski', 'moniteurdeski', 5),
    ('Moniteur de voile', 'moniteurdevoile', 5),
    ('Moniteur d’EPMS', 'moniteurd’epms', 5),
    ('Moniteur d’auto-école', 'moniteurd’auto-ecole', 5),
    ('Moniteur éducateur', 'moniteureducateur', 5),
    ('Moniteur-éducateur', 'moniteur-educateur', 5),
    ('Monnayeur de monnaies', 'monnayeurdemonnaies', 5),
    ('Monteur', 'monteur', 5),
    ('Monteur en isolation thermique', 'monteurenisolationthermique', 5),
    ('Monteur en optique-lunetterie', 'monteurenoptique-lunetterie', 5),
    ('Monteur incorporateur', 'monteurincorporateur', 5),
    ('Monteur électricien', 'monteurelectricien', 5),
    ('Monteur-câbleur', 'monteur-cableur', 5),
    ('Mosaïste', 'mosaiste', 5),
    ('Motion designer', 'motiondesigner', 5),
    ('Mouleur', 'mouleur', 5),
    ('Musicien', 'musicien', 5),
    ('Musicothérapeute', 'musicotherapeute', 5),
    ('Muséographe', 'museographe', 5),
    ('Mytiliculteur', 'mytiliculteur', 5),
    ('Mécanicien', 'mecanicien', 5),
    ('Mécanicien automobile', 'mecanicienautomobile', 5),
    ('Mécanicien aéronautique', 'mecanicienaeronautique', 5),
    ('Mécanicien de maintenance aéronautique', 'mecaniciendemaintenanceaeronautique', 5),
    ('Mécanicien d’aéronefs', 'mecaniciend’aeronefs', 5),
    ('Mécanicien moteur', 'mecanicienmoteur', 5),
    ('Mécanicien moto', 'mecanicienmoto', 5),
    ('Mécanicien robinetier', 'mecanicienrobinetier', 5),
    ('Mécanicien réparateur', 'mecanicienreparateur', 5),
    ('Mécatronicien', 'mecatronicien', 5),
    ('Médecin', 'medecin', 5),
    ('Médecin du sport', 'medecindusport', 5),
    ('Médecin légiste', 'medecinlegiste', 5),
    ('Média-planneur', 'media-planneur', 5),
    ('Médiateur culturel', 'mediateurculturel', 5),
    ('Médiateur familial', 'mediateurfamilial', 5),
    ('Médiateur pénal', 'mediateurpenal', 5),
    ('Médiateur social', 'mediateursocial', 5),
    ('Mégissier', 'megissier', 5),
    ('Métallier', 'metallier', 5),
    ('Métayer', 'metayer', 5),
    ('Métreur', 'metreur', 5),
    ('Métrologue', 'metrologue', 5),
    ('Météorologiste', 'meteorologiste', 5),
    ('Météorologue', 'meteorologue', 5),
    ('Nacrier', 'nacrier', 5),
    ('Nageur', 'nageur', 5),
    ('Narrateur', 'narrateur', 5),
    ('Naturaliste', 'naturaliste', 5),
    ('Naturopathe', 'naturopathe', 5),
    ('Navigateur aérien', 'navigateuraerien', 5),
    ('Netsurfer', 'netsurfer', 5),
    ('Neurologue', 'neurologue', 5),
    ('Nez créateur de parfum', 'nezcreateurdeparfum', 5),
    ('Notaire', 'notaire', 5),
    ('Nourrice', 'nourrice', 5),
    ('Nutritionniste', 'nutritionniste', 5),
    ('Nutritionniste sportif', 'nutritionnistesportif', 5),
    ('Négociateur immobilier', 'negociateurimmobilier', 5),
    ('Néphrologue', 'nephrologue', 5),
    ('Océanographe', 'oceanographe', 5),
    ('Océanologue', 'oceanologue', 5),
    ('Oenologue', 'oenologue', 5),
    ('Office Manager', 'officemanager', 5),
    ('Officier', 'officier', 5),
    ('Officier de marine', 'officierdemarine', 5),
    ('Officier de police', 'officierdepolice', 5),
    ('Officier d’état civil', 'officierd’etatcivil', 5),
    ('Ophtalmologue', 'ophtalmologue', 5),
    ('Opticien', 'opticien', 5),
    ('Opticien lunetier', 'opticienlunetier', 5),
    ('Opticien-lunetier', 'opticien-lunetier', 5),
    ('Optométriste', 'optometriste', 5),
    ('Opérateur', 'operateur', 5),
    ('Opérateur de fabrication', 'operateurdefabrication', 5),
    ('Opérateur de marché ou trader', 'operateurdemarcheoutrader', 5),
    ('Opérateur de prise de vue', 'operateurdeprisedevue', 5),
    ('Opérateur de production', 'operateurdeproduction', 5),
    ('Opérateur d’usinage sur commande numérique (UCN)', 'operateurd’usinagesurcommandenumerique(ucn)', 5),
    ('Opérateur en private equity', 'operateurenprivateequity', 5),
    ('Opérateur préviz onset', 'operateurprevizonset', 5),
    ('Opérateur synthétiseur', 'operateursynthetiseur', 5),
    ('Orfèvre', 'orfevre', 5),
    ('Organisateur d’événements', 'organisateurd’evenements', 5),
    ('Organisateur e-sport', 'organisateure-sport', 5),
    ('Orienteur professionnel', 'orienteurprofessionnel', 5),
    ('Orthodentiste', 'orthodentiste', 5),
    ('Orthophoniste', 'orthophoniste', 5),
    ('Orthoprothésiste', 'orthoprothesiste', 5),
    ('Orthoptiste', 'orthoptiste', 5),
    ('Orthopédiste', 'orthopediste', 5),
    ('Orthopédiste-orthésiste', 'orthopediste-orthesiste', 5),
    ('Ostréiculteur', 'ostreiculteur', 5),
    ('Ostéopathe', 'osteopathe', 5),
    ('Ostéopathe animalier', 'osteopatheanimalier', 5),
    ('Outplacer', 'outplacer', 5),
    ('Ouvrier', 'ouvrier', 5),
    ('Ouvrier agricole', 'ouvrieragricole', 5),
    ('Ouvrier sylviculteur', 'ouvriersylviculteur', 5),
    ('Packager éditorial', 'packagereditorial', 5),
    ('Palefrenier', 'palefrenier', 5),
    ('Palefrenier-soigneur', 'palefrenier-soigneur', 5),
    ('Paléontologue', 'paleontologue', 5),
    ('Paramédicaux', 'paramedicaux', 5),
    ('Parapharmacien', 'parapharmacien', 5),
    ('Parfumeur', 'parfumeur', 5),
    ('Parqueteur', 'parqueteur', 5),
    ('Passementier', 'passementier', 5),
    ('Passeur', 'passeur', 5),
    ('Patineur', 'patineur', 5),
    ('Patronnier gradeur', 'patronniergradeur', 5),
    ('Paveur-dalleur', 'paveur-dalleur', 5),
    ('Paysagiste', 'paysagiste', 5),
    ('Paysan', 'paysan', 5),
    ('Peintre', 'peintre', 5),
    ('Peintre en bâtiment', 'peintreenbatiment', 5),
    ('Peintre en décor', 'peintreendecor', 5),
    ('Peintre en lettres', 'peintreenlettres', 5),
    ('Peintre solier', 'peintresolier', 5),
    ('Peintre sur mobilier', 'peintresurmobilier', 5),
    ('Perchman', 'perchman', 5),
    ('Perruquier', 'perruquier', 5),
    ('Perruquier – posticheur', 'perruquier–posticheur', 5),
    ('Perruquier-posticheur', 'perruquier-posticheur', 5),
    ('Personal Trainer', 'personaltrainer', 5),
    ('Personnel de surveillance', 'personneldesurveillance', 5),
    ('Pet Sitter', 'petsitter', 5),
    ('Pharmacien', 'pharmacien', 5),
    ('Photocompositeur', 'photocompositeur', 5),
    ('Photogrammètre', 'photogrammetre', 5),
    ('Photographe', 'photographe', 5),
    ('Photographe de mode', 'photographedemode', 5),
    ('Photograveur', 'photograveur', 5),
    ('Physicien', 'physicien', 5),
    ('Physicien médical', 'physicienmedical', 5),
    ('Physiothérapeute animalier', 'physiotherapeuteanimalier', 5),
    ('Phytothérapeute', 'phytotherapeute', 5),
    ('Pickpocket', 'pickpocket', 5),
    ('Pigiste', 'pigiste', 5),
    ('Pilote', 'pilote', 5),
    ('Pilote de char', 'pilotedechar', 5),
    ('Pilote de chasse', 'pilotedechasse', 5),
    ('Pilote de drone', 'pilotededrone', 5),
    ('Pilote de ligne', 'pilotedeligne', 5),
    ('Pilote de production', 'pilotedeproduction', 5),
    ('Pilote d’avion', 'piloted’avion', 5),
    ('Pilote d’exploitation', 'piloted’exploitation', 5),
    ('Pilote d’hélicoptère', 'piloted’helicoptere', 5),
    ('Pipier', 'pipier', 5),
    ('Piqueur', 'piqueur', 5),
    ('Pirate informatique', 'pirateinformatique', 5),
    ('Pizzaïolo', 'pizzaiolo', 5),
    ('Plagiste', 'plagiste', 5),
    ('Planificateur OPC', 'planificateuropc', 5),
    ('Planner stratégique', 'plannerstrategique', 5),
    ('Planneur stratégique', 'planneurstrategique', 5),
    ('Plaquiste', 'plaquiste', 5),
    ('Plasticien', 'plasticien', 5),
    ('Plisseur', 'plisseur', 5),
    ('Plombier', 'plombier', 5),
    ('Plombier-Chauffagiste', 'plombier-chauffagiste', 5),
    ('Plongeur', 'plongeur', 5),
    ('Plumassier', 'plumassier', 5),
    ('Plâtrier', 'platrier', 5),
    ('Podo-orthésiste', 'podo-orthesiste', 5),
    ('Poissonnier', 'poissonnier', 5),
    ('Policier', 'policier', 5),
    ('Policier – Gardien de la Paix', 'policier–gardiendelapaix', 5),
    ('Polisseur', 'polisseur', 5),
    ('Politicien', 'politicien', 5),
    ('Pompier', 'pompier', 5),
    ('Pompiste', 'pompiste', 5),
    ('Porcelainier', 'porcelainier', 5),
    ('Porfesseur des universités', 'porfesseurdesuniversites', 5),
    ('Portier', 'portier', 5),
    ('Poseur de sol (solier)', 'poseurdesol(solier)', 5),
    ('Postier', 'postier', 5),
    ('Potier', 'potier', 5),
    ('Potier d’étain', 'potierd’etain', 5),
    ('Poêlier', 'poelier', 5),
    ('Premier d’atelier', 'premierd’atelier', 5),
    ('Premier ministre', 'premierministre', 5),
    ('Pressier', 'pressier', 5),
    ('Prestidigitateur', 'prestidigitateur', 5),
    ('Primeur', 'primeur', 5),
    ('Pro gamer', 'progamer', 5),
    ('Procureur', 'procureur', 5),
    ('Procureur de la République', 'procureurdelarepublique', 5),
    ('Product manager', 'productmanager', 5),
    ('Product owner', 'productowner', 5),
    ('Producteur', 'producteur', 5),
    ('Professeur', 'professeur', 5),
    ('Professeur de collège', 'professeurdecollege', 5),
    ('Professeur de collège ou lycée', 'professeurdecollegeoulycee', 5),
    ('Professeur de danse', 'professeurdedanse', 5),
    ('Professeur de français langue étrangère', 'professeurdefrancaislangueetrangere', 5),
    ('Professeur de lycée', 'professeurdelycee', 5),
    ('Professeur de musique', 'professeurdemusique', 5),
    ('Professeur de sport', 'professeurdesport', 5),
    ('Professeur des écoles', 'professeurdesecoles', 5),
    ('Professeur d’EPS', 'professeurd’eps', 5),
    ('Professeur d’art dramatique', 'professeurd’artdramatique', 5),
    ('Professeur d’art dramatique ( ou de théâtre )', 'professeurd’artdramatique(oudetheatre)', 5),
    ('Professeur d’arts plastiques', 'professeurd’artsplastiques', 5),
    ('Professeur d’université', 'professeurd’universite', 5),
    ('Professeur d’éducation physique (EPS)', 'professeurd’educationphysique(eps)', 5),
    ('Professionnels du dessin animé', 'professionnelsdudessinanime', 5),
    ('Programmeur', 'programmeur', 5),
    ('Programmeur de jeux vidéo', 'programmeurdejeuxvideo', 5),
    ('Programmiste', 'programmiste', 5),
    ('Projectionniste', 'projectionniste', 5),
    ('Promoteur immobilier', 'promoteurimmobilier', 5),
    ('Prospecteur foncier', 'prospecteurfoncier', 5),
    ('Prostitué', 'prostitue', 5),
    ('Prothésiste', 'prothesiste', 5),
    ('Prothésiste dentaire', 'prothesistedentaire', 5),
    ('Prothésiste ongulaire', 'prothesisteongulaire', 5),
    ('Prothésiste-Orthésiste', 'prothesiste-orthesiste', 5),
    ('Proviseur', 'proviseur', 5),
    ('Proxénète', 'proxenete', 5),
    ('Préfet', 'prefet', 5),
    ('Préparateur', 'preparateur', 5),
    ('Préparateur de commande', 'preparateurdecommande', 5),
    ('Préparateur de commandes', 'preparateurdecommandes', 5),
    ('Préparateur de vol', 'preparateurdevol', 5),
    ('Préparateur en pharmacie', 'preparateurenpharmacie', 5),
    ('Préparateur méthodes', 'preparateurmethodes', 5),
    ('Préparateur physique', 'preparateurphysique', 5),
    ('Présentateur radio', 'presentateurradio', 5),
    ('Présentateur télé', 'presentateurtele', 5),
    ('Président de la Confédération', 'presidentdelaconfederation', 5),
    ('Président de la République', 'presidentdelarepublique', 5),
    ('Président-directeur général', 'president-directeurgeneral', 5),
    ('Président-directeur général (PDG)', 'president-directeurgeneral(pdg)', 5),
    ('Prêtre', 'pretre', 5),
    ('Psychanalyste', 'psychanalyste', 5),
    ('Psychiatre', 'psychiatre', 5),
    ('Psychologue', 'psychologue', 5),
    ('Psychologue clinicien', 'psychologueclinicien', 5),
    ('Psychologue du travail', 'psychologuedutravail', 5),
    ('Psychologue en libéral', 'psychologueenliberal', 5),
    ('Psychologue scolaire', 'psychologuescolaire', 5),
    ('Psychomotricien', 'psychomotricien', 5),
    ('Psychométricien', 'psychometricien', 5),
    ('Psychopraticien', 'psychopraticien', 5),
    ('Psychosociologue', 'psychosociologue', 5),
    ('Psychothérapeute', 'psychotherapeute', 5),
    ('Puéricultrice', 'puericultrice', 5),
    ('Pâtissier', 'patissier', 5),
    ('Péagiste', 'peagiste', 5),
    ('Pédiatre', 'pediatre', 5),
    ('Pédicure podologue', 'pedicurepodologue', 5),
    ('Pédicure – podologue', 'pedicure–podologue', 5),
    ('Pédopsychiatre', 'pedopsychiatre', 5),
    ('Pépiniériste', 'pepinieriste', 5),
    ('Pêcheur', 'pecheur', 5),
    ('Qualiticien', 'qualiticien', 5),
    ('Questeur', 'questeur', 5),
    ('Quincaillier', 'quincaillier', 5),
    ('Rabbin', 'rabbin', 5),
    ('Radiologue', 'radiologue', 5),
    ('Raffineur', 'raffineur', 5),
    ('Ramoneur', 'ramoneur', 5),
    ('Rappeur', 'rappeur', 5),
    ('Receleur', 'receleur', 5),
    ('Relaxologue', 'relaxologue', 5),
    ('Relecteur', 'relecteur', 5),
    ('Relieur', 'relieur', 5),
    ('Relieur-doreur', 'relieur-doreur', 5),
    ('Reporter', 'reporter', 5),
    ('Reporter en agence', 'reporterenagence', 5),
    ('Reporter-photographe', 'reporter-photographe', 5),
    ('Responsable', 'responsable', 5),
    ('Responsable HSE', 'responsablehse', 5),
    ('Responsable QSE', 'responsableqse', 5),
    ('Responsable accueil', 'responsableaccueil', 5),
    ('Responsable affiliation', 'responsableaffiliation', 5),
    ('Responsable billetterie', 'responsablebilletterie', 5),
    ('Responsable communication', 'responsablecommunication', 5),
    ('Responsable conseil brevets', 'responsableconseilbrevets', 5),
    ('Responsable consommateur', 'responsableconsommateur', 5),
    ('Responsable de collection', 'responsabledecollection', 5),
    ('Responsable de conditionnement', 'responsabledeconditionnement', 5),
    ('Responsable de fabrication', 'responsabledefabrication', 5),
    ('Responsable de la sécurité', 'responsabledelasecurite', 5),
    ('Responsable de logistique', 'responsabledelogistique', 5),
    ('Responsable de l’information', 'responsabledel’information', 5),
    ('Responsable de maintenance', 'responsabledemaintenance', 5),
    ('Responsable de pixels', 'responsabledepixels', 5),
    ('Responsable de production', 'responsabledeproduction', 5),
    ('Responsable de projets immobiliers', 'responsabledeprojetsimmobiliers', 5),
    ('Responsable de réservation', 'responsabledereservation', 5),
    ('Responsable de station d’eau', 'responsabledestationd’eau', 5),
    ('Responsable de vente', 'responsabledevente', 5),
    ('Responsable des Ressources Humaines', 'responsabledesressourceshumaines', 5),
    ('Responsable des opérations', 'responsabledesoperations', 5),
    ('Responsable des ventes (Sales manager)', 'responsabledesventes(salesmanager)', 5),
    ('Responsable des études', 'responsabledesetudes', 5),
    ('Responsable du personnel', 'responsabledupersonnel', 5),
    ('Responsable développement RH', 'responsabledeveloppementrh', 5),
    ('Responsable d’affaire', 'responsabled’affaire', 5),
    ('Responsable d’agence', 'responsabled’agence', 5),
    ('Responsable d’animation', 'responsabled’animation', 5),
    ('Responsable d’antenne', 'responsabled’antenne', 5),
    ('Responsable d’entrepôt', 'responsabled’entrepot', 5),
    ('Responsable d’exploitation', 'responsabled’exploitation', 5),
    ('Responsable d’édition', 'responsabled’edition', 5),
    ('Responsable d’élevage', 'responsabled’elevage', 5),
    ('Responsable e-commerce', 'responsablee-commerce', 5),
    ('Responsable emailing', 'responsableemailing', 5),
    ('Responsable expansion', 'responsableexpansion', 5),
    ('Responsable expatriation', 'responsableexpatriation', 5),
    ('Responsable export', 'responsableexport', 5),
    ('Responsable formation', 'responsableformation', 5),
    ('Responsable grands comptes', 'responsablegrandscomptes', 5),
    ('Responsable géographique', 'responsablegeographique', 5),
    ('Responsable hospitalité', 'responsablehospitalite', 5),
    ('Responsable logistique', 'responsablelogistique', 5),
    ('Responsable m-commerce', 'responsablem-commerce', 5),
    ('Responsable marketing', 'responsablemarketing', 5),
    ('Responsable marketing digital', 'responsablemarketingdigital', 5),
    ('Responsable marketing sportif', 'responsablemarketingsportif', 5),
    ('Responsable merchandising', 'responsablemerchandising', 5),
    ('Responsable méthode et outils', 'responsablemethodeetoutils', 5),
    ('Responsable paie', 'responsablepaie', 5),
    ('Responsable planning', 'responsableplanning', 5),
    ('Responsable production', 'responsableproduction', 5),
    ('Responsable promotion', 'responsablepromotion', 5),
    ('Responsable qualité', 'responsablequalite', 5),
    ('Responsable relations sociales', 'responsablerelationssociales', 5),
    ('Responsable service clientèle', 'responsableserviceclientele', 5),
    ('Responsable sponsoring', 'responsablesponsoring', 5),
    ('Responsable support', 'responsablesupport', 5),
    ('Responsable technique', 'responsabletechnique', 5),
    ('Responsable télécoms', 'responsabletelecoms', 5),
    ('Responsable éditorial', 'responsableeditorial', 5),
    ('Responsable éditorial web', 'responsableeditorialweb', 5),
    ('Ressources humaines', 'ressourceshumaines', 5),
    ('Restaurateur', 'restaurateur', 5),
    ('Restaurateur (restauration d’objets, etc.)', 'restaurateur(restaurationd’objets,etc.)', 5),
    ('Restaurateur d’art', 'restaurateurd’art', 5),
    ('Retoucheur', 'retoucheur', 5),
    ('Risk-manager', 'risk-manager', 5),
    ('Roboticien', 'roboticien', 5),
    ('Roughman', 'roughman', 5),
    ('Routier', 'routier', 5),
    ('Rubricard', 'rubricard', 5),
    ('Rudologue', 'rudologue', 5),
    ('Réalisateur', 'realisateur', 5),
    ('Réalisateur VR', 'realisateurvr', 5),
    ('Réalisateur de cinéma', 'realisateurdecinema', 5),
    ('Réalisateur de plateau', 'realisateurdeplateau', 5),
    ('Réalisateur de radio', 'realisateurderadio', 5),
    ('Réalisateurs de téléfilms', 'realisateursdetelefilms', 5),
    ('Réceptionniste', 'receptionniste', 5),
    ('Réceptionniste d’hôtel', 'receptionnisted’hotel', 5),
    ('Rédacteur', 'redacteur', 5),
    ('Rédacteur de contrats', 'redacteurdecontrats', 5),
    ('Rédacteur de documentation', 'redacteurdedocumentation', 5),
    ('Rédacteur de presse', 'redacteurdepresse', 5),
    ('Rédacteur en chef', 'redacteurenchef', 5),
    ('Rédacteur territorial', 'redacteurterritorial', 5),
    ('Rédacteur web', 'redacteurweb', 5),
    ('Rédacteur-reporter', 'redacteur-reporter', 5),
    ('Réflexologue', 'reflexologue', 5),
    ('Régisseur', 'regisseur', 5),
    ('Régisseur d’œuvre d’art', 'regisseurd’œuvred’art', 5),
    ('Régisseur général', 'regisseurgeneral', 5),
    ('Régulateur', 'regulateur', 5),
    ('Rééducateur', 'reeducateur', 5),
    ('Rôtisseur', 'rotisseur', 5),
    ('Sage-femme', 'sage-femme', 5),
    ('Sages-femmes', 'sages-femmes', 5),
    ('Sales Development Representative', 'salesdevelopmentrepresentative', 5),
    ('Santonnier', 'santonnier', 5),
    ('Sapeur pompier', 'sapeurpompier', 5),
    ('Sapeur-Pompier', 'sapeur-pompier', 5),
    ('Saucier', 'saucier', 5),
    ('Saunier', 'saunier', 5),
    ('Scripte', 'scripte', 5),
    ('Scrum master', 'scrummaster', 5),
    ('Sculpteur', 'sculpteur', 5),
    ('Sculpteur sur bois', 'sculpteursurbois', 5),
    ('Sculpteur sur métal', 'sculpteursurmetal', 5),
    ('Sculpteur sur pierre', 'sculpteursurpierre', 5),
    ('Scénariste', 'scenariste', 5),
    ('Scénographe', 'scenographe', 5),
    ('Second capitaine', 'secondcapitaine', 5),
    ('Secrétaire', 'secretaire', 5),
    ('Secrétaire administratif', 'secretaireadministratif', 5),
    ('Secrétaire administrative', 'secretaireadministrative', 5),
    ('Secrétaire comptable', 'secretairecomptable', 5),
    ('Secrétaire de documentation', 'secretairededocumentation', 5),
    ('Secrétaire de rédaction', 'secretairederedaction', 5),
    ('Secrétaire d’État', 'secretaired’etat', 5),
    ('Secrétaire d’édition', 'secretaired’edition', 5),
    ('Secrétaire médicale', 'secretairemedicale', 5),
    ('Secrétaire vétérinaire', 'secretaireveterinaire', 5),
    ('Secrétaire-assistant juridique', 'secretaire-assistantjuridique', 5),
    ('Secrétaire-assistant médical', 'secretaire-assistantmedical', 5),
    ('Sellier', 'sellier', 5),
    ('Sellier bourrelier', 'sellierbourrelier', 5),
    ('Sellier d’ameublement', 'sellierd’ameublement', 5),
    ('Sellier maroquinier', 'selliermaroquinier', 5),
    ('Serrurier', 'serrurier', 5),
    ('Serrurier métallier', 'serruriermetallier', 5),
    ('Sertisseur', 'sertisseur', 5),
    ('Serveur', 'serveur', 5),
    ('Serveur / serveuse', 'serveur/serveuse', 5),
    ('Sexologue', 'sexologue', 5),
    ('Shaper', 'shaper', 5),
    ('Shérif', 'sherif', 5),
    ('Sismologue', 'sismologue', 5),
    ('Skiman', 'skiman', 5),
    ('Skipper', 'skipper', 5),
    ('Social', 'social', 5),
    ('Socio-esthéticien', 'socio-estheticien', 5),
    ('Socio-esthéticien(ne)', 'socio-estheticien(ne)', 5),
    ('Sociologue', 'sociologue', 5),
    ('Soigneur animalier', 'soigneuranimalier', 5),
    ('Soldat', 'soldat', 5),
    ('Solier-moquettiste', 'solier-moquettiste', 5),
    ('Sommelier', 'sommelier', 5),
    ('Sophrologue', 'sophrologue', 5),
    ('Sorcier', 'sorcier', 5),
    ('Soudeur', 'soudeur', 5),
    ('Souffleur de verre', 'souffleurdeverre', 5),
    ('Sound designer', 'sounddesigner', 5),
    ('Souscripteur', 'souscripteur', 5),
    ('Spa manager', 'spamanager', 5),
    ('Spa praticien', 'spapraticien', 5),
    ('Spationaute', 'spationaute', 5),
    ('Sportif de haut niveau', 'sportifdehautniveau', 5),
    ('Sportif professionnel', 'sportifprofessionnel', 5),
    ('Staffeur ornemaniste', 'staffeurornemaniste', 5),
    ('Staffeur-stucateur', 'staffeur-stucateur', 5),
    ('Standardiste', 'standardiste', 5),
    ('Statisticien', 'statisticien', 5),
    ('Stenotypiste', 'stenotypiste', 5),
    ('Steward', 'steward', 5),
    ('Story-boarder', 'story-boarder', 5),
    ('Stratifieur', 'stratifieur', 5),
    ('Streamer', 'streamer', 5),
    ('Styliste', 'styliste', 5),
    ('Styliste de mode', 'stylistedemode', 5),
    ('Styliste modéliste', 'stylistemodeliste', 5),
    ('Styliste ongulaire', 'stylisteongulaire', 5),
    ('Substitut du procureur', 'substitutduprocureur', 5),
    ('Substitut général', 'substitutgeneral', 5),
    ('Superviseur', 'superviseur', 5),
    ('Surveillant', 'surveillant', 5),
    ('Surveillant pénitentiaire', 'surveillantpenitentiaire', 5),
    ('Sylviculteur', 'sylviculteur', 5),
    ('Sécurité civile', 'securitecivile', 5),
    ('Sénateur', 'senateur', 5),
    ('Sérigraphe', 'serigraphe', 5),
    ('Tabletier', 'tabletier', 5),
    ('Taillandier', 'taillandier', 5),
    ('Tailleur', 'tailleur', 5),
    ('Tailleur de pierre', 'tailleurdepierre', 5),
    ('Tanneur', 'tanneur', 5),
    ('Tapissier', 'tapissier', 5),
    ('Tapissier d’ameublement', 'tapissierd’ameublement', 5),
    ('Tapissier garnisseur', 'tapissiergarnisseur', 5),
    ('Tatoueur', 'tatoueur', 5),
    ('Taxidermiste', 'taxidermiste', 5),
    ('Technical artist', 'technicalartist', 5),
    ('Technicien', 'technicien', 5),
    ('Technicien alarme intrusion', 'technicienalarmeintrusion', 5),
    ('Technicien ascensoriste', 'technicienascensoriste', 5),
    ('Technicien biologiste', 'technicienbiologiste', 5),
    ('Technicien de circulation', 'techniciendecirculation', 5),
    ('Technicien de fabrication', 'techniciendefabrication', 5),
    ('Technicien de laboratoire', 'techniciendelaboratoire', 5),
    ('Technicien de laboratoire photo', 'techniciendelaboratoirephoto', 5),
    ('Technicien de l’intervention sociale et familiale', 'techniciendel’interventionsocialeetfamiliale', 5),
    ('Technicien de l’intervention sociale et familiale (TISF)', 'techniciendel’interventionsocialeetfamiliale(tisf)', 5),
    ('Technicien de maintenance', 'techniciendemaintenance', 5),
    ('Technicien de maintenance industrielle', 'techniciendemaintenanceindustrielle', 5),
    ('Technicien de maintenance informatique', 'techniciendemaintenanceinformatique', 5),
    ('Technicien de paie', 'techniciendepaie', 5),
    ('Technicien de piscine', 'techniciendepiscine', 5),
    ('Technicien de rivière', 'technicienderiviere', 5),
    ('Technicien de surface', 'techniciendesurface', 5),
    ('Technicien des effets spéciaux', 'techniciendeseffetsspeciaux', 5),
    ('Technicien du patrimoine', 'techniciendupatrimoine', 5),
    ('Technicien du spectacle', 'technicienduspectacle', 5),
    ('Technicien d’analyses biomédicales', 'techniciend’analysesbiomedicales', 5),
    ('Technicien d’antenne', 'techniciend’antenne', 5),
    ('Technicien d’essai', 'techniciend’essai', 5),
    ('Technicien d’exploitation', 'techniciend’exploitation', 5),
    ('Technicien d’infrastructures', 'techniciend’infrastructures', 5),
    ('Technicien d’intervention', 'techniciend’intervention', 5),
    ('Technicien d’études', 'techniciend’etudes', 5),
    ('Technicien en analyse médicale', 'technicienenanalysemedicale', 5),
    ('Technicien en productique', 'technicienenproductique', 5),
    ('Technicien en radioprotection', 'technicienenradioprotection', 5),
    ('Technicien forestier', 'technicienforestier', 5),
    ('Technicien machine à sous', 'technicienmachineasous', 5),
    ('Technicien piqueteur', 'technicienpiqueteur', 5),
    ('Technicien plasturgiste', 'technicienplasturgiste', 5),
    ('Technicien qualité', 'technicienqualite', 5),
    ('Technicien réseau', 'technicienreseau', 5),
    ('Technicien support clients', 'techniciensupportclients', 5),
    ('Technicien thermicien', 'technicienthermicien', 5),
    ('Technicien vidéo', 'technicienvideo', 5),
    ('Technico-commercial', 'technico-commercial', 5),
    ('Technologue', 'technologue', 5),
    ('Teinturier', 'teinturier', 5),
    ('Terrassier', 'terrassier', 5),
    ('Test manager', 'testmanager', 5),
    ('Testeur', 'testeur', 5),
    ('Testeur culinaire', 'testeurculinaire', 5),
    ('Testeur de jeux vidéo', 'testeurdejeuxvideo', 5),
    ('Thanatopracteur', 'thanatopracteur', 5),
    ('Tireur de câble', 'tireurdecable', 5),
    ('Tisserand', 'tisserand', 5),
    ('Toiletteur', 'toiletteur', 5),
    ('Toiletteur canin', 'toiletteurcanin', 5),
    ('Tonnelier', 'tonnelier', 5),
    ('Tools programmer', 'toolsprogrammer', 5),
    ('Tourneur sur bois', 'tourneursurbois', 5),
    ('Tourneur sur métal', 'tourneursurmetal', 5),
    ('Tourneur-fraiseur', 'tourneur-fraiseur', 5),
    ('Trader', 'trader', 5),
    ('Trader média', 'tradermedia', 5),
    ('Trader sportif', 'tradersportif', 5),
    ('Traducteur', 'traducteur', 5),
    ('Traducteur spécialisé', 'traducteurspecialise', 5),
    ('Traducteur-interprète', 'traducteur-interprete', 5),
    ('Traducteur-réviseur', 'traducteur-reviseur', 5),
    ('Traffic manager', 'trafficmanager', 5),
    ('Trafiquant', 'trafiquant', 5),
    ('Traiteur', 'traiteur', 5),
    ('Transporteur', 'transporteur', 5),
    ('Trapéziste', 'trapeziste', 5),
    ('Travailleur social', 'travailleursocial', 5),
    ('Tresseur', 'tresseur', 5),
    ('Trésorier', 'tresorier', 5),
    ('Tueur à gages', 'tueuragages', 5),
    ('Tuilier', 'tuilier', 5),
    ('Tuyauteur', 'tuyauteur', 5),
    ('Typographe', 'typographe', 5),
    ('Téléassistant', 'teleassistant', 5),
    ('Téléconseiller', 'teleconseiller', 5),
    ('Téléphoniste', 'telephoniste', 5),
    ('Télépilote audiovisuel', 'telepiloteaudiovisuel', 5),
    ('Télépilote sapeur-pompier', 'telepilotesapeur-pompier', 5),
    ('Télévendeur', 'televendeur', 5),
    ('Tôlier', 'tolier', 5),
    ('UI designer', 'uidesigner', 5),
    ('UX designer', 'uxdesigner', 5),
    ('Urbaniste', 'urbaniste', 5),
    ('Urgentiste', 'urgentiste', 5),
    ('Urologue', 'urologue', 5),
    ('VRP', 'vrp', 5),
    ('Valet de chambre', 'valetdechambre', 5),
    ('Vannier', 'vannier', 5),
    ('Veilleur de nuit', 'veilleurdenuit', 5),
    ('Veilleur stratégique', 'veilleurstrategique', 5),
    ('Veilleur technologique', 'veilleurtechnologique', 5),
    ('Vendeur', 'vendeur', 5),
    ('Vendeur automobile', 'vendeurautomobile', 5),
    ('Vendeur en animalerie', 'vendeurenanimalerie', 5),
    ('Vendeur en magasin', 'vendeurenmagasin', 5),
    ('Vendeur en prêt-à-porter', 'vendeurenpret-a-porter', 5),
    ('Vendeur export', 'vendeurexport', 5),
    ('Vendeur moto', 'vendeurmoto', 5),
    ('Vendeur technique', 'vendeurtechnique', 5),
    ('Vernisseur', 'vernisseur', 5),
    ('Verrier', 'verrier', 5),
    ('Vigneron', 'vigneron', 5),
    ('Visiteur médical', 'visiteurmedical', 5),
    ('Visual Merchandiser', 'visualmerchandiser', 5),
    ('Visuel merchandiser', 'visuelmerchandiser', 5),
    ('Visuel merchandiseur', 'visuelmerchandiseur', 5),
    ('Viticulteur', 'viticulteur', 5),
    ('Viticulteur, ou vigneron', 'viticulteur,ouvigneron', 5),
    ('Vitrailliste', 'vitrailliste', 5),
    ('Vitrier', 'vitrier', 5),
    ('Voilier-sellier', 'voilier-sellier', 5),
    ('Voiturier', 'voiturier', 5),
    ('Volcanologue', 'volcanologue', 5),
    ('Voleur', 'voleur', 5),
    ('Voyageur représentant placier (VRP)', 'voyageurrepresentantplacier(vrp)', 5),
    ('Vétérinaire', 'veterinaire', 5),
    ('Wagonnier', 'wagonnier', 5),
    ('Wakeboarder', 'wakeboarder', 5),
    ('Wappeur', 'wappeur', 5),
    ('Wattman', 'wattman', 5),
    ('Web Analyste', 'webanalyste', 5),
    ('Webdesigner', 'webdesigner', 5),
    ('Webdeveloper', 'webdeveloper', 5),
    ('Webmarketeur', 'webmarketeur', 5),
    ('Webmaster', 'webmaster', 5),
    ('Webmestre', 'webmestre', 5),
    ('Webplanner', 'webplanner', 5),
    ('Wedding planner', 'weddingplanner', 5),
    ('Xylophoniste', 'xylophoniste', 5),
    ('Yield manager', 'yieldmanager', 5),
    ('Ymagier', 'ymagier', 5),
    ('Yodler', 'yodler', 5),
    ('Youtubeur', 'youtubeur', 5),
    ('Zingueur', 'zingueur', 5),
    ('Zoologiste', 'zoologiste', 5),
    ('Zoologue', 'zoologue', 5),
    ('Zoothérapeute', 'zootherapeute', 5),
    ('Zythologue', 'zythologue', 5),
    ('métier en A', 'metierena', 5),
    ('métier en B', 'metierenb', 5),
    ('métier en C', 'metierenc', 5),
    ('métier en D', 'metierend', 5),
    ('métier en E', 'metierene', 5),
    ('métier en F', 'metierenf', 5),
    ('métier en G', 'metiereng', 5),
    ('métier en H', 'metierenh', 5),
    ('métier en I', 'metiereni', 5),
    ('métier en J', 'metierenj', 5),
    ('métier en K', 'metierenk', 5),
    ('métier en L', 'metierenl', 5),
    ('métier en M', 'metierenm', 5),
    ('métier en N', 'metierenn', 5),
    ('métier en O', 'metiereno', 5),
    ('métier en P', 'metierenp', 5),
    ('métier en Q', 'metierenq', 5),
    ('métier en R', 'metierenr', 5),
    ('métier en S', 'metierens', 5),
    ('métier en T', 'metierent', 5),
    ('métier en U', 'metierenu', 5),
    ('métier en V', 'metierenv', 5),
    ('métier en W', 'metierenw', 5),
    ('métier en X', 'metierenx', 5),
    ('métier en Y', 'metiereny', 5),
    ('métier en Z', 'metierenz', 5),
    ('Âtrier', 'atrier', 5),
    ('Éboueur', 'eboueur', 5),
    ('Ébéniste', 'ebeniste', 5),
    ('Écailler', 'ecailler', 5),
    ('Échafaudeur', 'echafaudeur', 5),
    ('Éclairagiste', 'eclairagiste', 5),
    ('Éclusier', 'eclusier', 5),
    ('Éco-conseiller', 'eco-conseiller', 5),
    ('Économe', 'econome', 5),
    ('Économiste', 'economiste', 5),
    ('Économiste de la construction', 'economistedelaconstruction', 5),
    ('Écotoxicologue', 'ecotoxicologue', 5),
    ('Écrivain', 'ecrivain', 5),
    ('Écrivain public', 'ecrivainpublic', 5),
    ('Éditeur', 'editeur', 5),
    ('Éditeur-directeur éditorial', 'editeur-directeureditorial', 5),
    ('Éducateur', 'educateur', 5),
    ('Éducateur de jeunes enfants', 'educateurdejeunesenfants', 5),
    ('Éducateur de la petite enfance', 'educateurdelapetiteenfance', 5),
    ('Éducateur sportif', 'educateursportif', 5),
    ('Éducateur spécialisé', 'educateurspecialise', 5),
    ('Égyptologue', 'egyptologue', 5),
    ('Élagueur', 'elagueur', 5),
    ('Électricien', 'electricien', 5),
    ('Électricien d’équipement', 'electriciend’equipement', 5),
    ('Électronicien automobile', 'electronicienautomobile', 5),
    ('Électrotechnicien', 'electrotechnicien', 5),
    ('Éleveur', 'eleveur', 5),
    ('Éleveur de chevaux', 'eleveurdechevaux', 5),
    ('Émailleur sur lave', 'emailleursurlave', 5),
    ('Émailleur sur métal', 'emailleursurmetal', 5),
    ('Épicier', 'epicier', 5),
    ('Équicien', 'equicien', 5),
    ('Équipier en restaurant rapide', 'equipierenrestaurantrapide', 5),
    ('Étalagiste', 'etalagiste', 5),
    ('Étalonneur numérique', 'etalonneurnumerique', 5),
    ('Étancheur', 'etancheur', 5),
    ('Éthologue', 'ethologue', 5),
    ('Étiopathe', 'etiopathe', 5),
    ('Évantailliste', 'evantailliste', 5),
    ('Éventailliste', 'eventailliste', 5)
ON CONFLICT (mot_normalized, categorie_id) DO NOTHING;
