INSERT INTO mots (mot, mot_normalized, categorie_id) VALUES
    ('A Moment of Innocence', 'amomentofinnocence', 7),
    ('A Song of Love', 'asongoflove', 7),
    ('A Touch of Zen', 'atouchofzen', 7),
    ('A toute épreuve', 'atouteepreuve', 7),
    ('Aaahh Belinda', 'aaahhbelinda', 7),
    ('Accatone', 'accatone', 7),
    ('Adaptation', 'adaptation', 7),
    ('Adieu, ma concubine', 'adieu,maconcubine', 7),
    ('After Hours', 'afterhours', 7),
    ('After Life', 'afterlife', 7),
    ('Aguirre, la colère de Dieu', 'aguirre,lacolerededieu', 7),
    ('Ainsi va l’amour', 'ainsival’amour', 7),
    ('Akira', 'akira', 7),
    ('Aladdin', 'aladdin', 7),
    ('Alice', 'alice', 7),
    ('Alice au pays des merveilles', 'aliceaupaysdesmerveilles', 7),
    ('Alice dans les villes', 'alicedanslesvilles', 7),
    ('Alien, le huitième passager', 'alien,lehuitiemepassager', 7),
    ('Aliens le retour', 'aliensleretour', 7),
    ('All or Nothing', 'allornothing', 7),
    ('Allemagne année zéro', 'allemagneanneezero', 7),
    ('Alphaville', 'alphaville', 7),
    ('Amadeus', 'amadeus', 7),
    ('Amarcord', 'amarcord', 7),
    ('American Beauty', 'americanbeauty', 7),
    ('American Movie', 'americanmovie', 7),
    ('Amour', 'amour', 7),
    ('Amours chiennes', 'amourschiennes', 7),
    ('Andrei Rublev', 'andreirublev', 7),
    ('Ankur', 'ankur', 7),
    ('Annie Hall', 'anniehall', 7),
    ('Another Year', 'anotheryear', 7),
    ('Antoine et Colette', 'antoineetcolette', 7),
    ('Apiyemiyekî?', 'apiyemiyeki?', 7),
    ('Apocalypse Now', 'apocalypsenow', 7),
    ('Apportez-moi la tête d’Alfredo Garcia', 'apportez-moilateted’alfredogarcia', 7),
    ('Aquaman', 'aquaman', 7),
    ('Araby', 'araby', 7),
    ('Around the World When You Were My Age', 'aroundtheworldwhenyouweremyage', 7),
    ('Ascenseur pour l’échafaud', 'ascenseurpourl’echafaud', 7),
    ('Asparagus', 'asparagus', 7),
    ('Assurance sur la mort', 'assurancesurlamort', 7),
    ('At Land', 'atland', 7),
    ('Au fil du temps', 'aufildutemps', 7),
    ('Au hasard Balthazar', 'auhasardbalthazar', 7),
    ('Au travers des oliviers', 'autraversdesoliviers', 7),
    ('Autopsie d’un meurtre', 'autopsied’unmeurtre', 7),
    ('Autumn', 'autumn', 7),
    ('Aux coeurs des ténèbres – l’apocalypse d’un metteur en scène', 'auxcoeursdestenebres–l’apocalypsed’unmetteurenscene', 7),
    ('Ava', 'ava', 7),
    ('Avatar', 'avatar', 7),
    ('Avengers', 'avengers', 7),
    ('Avengers : L’Ère d’Ultron', 'avengers:l’ered’ultron', 7),
    ('Avengers: Endgame', 'avengers:endgame', 7),
    ('Avengers: Infinity War', 'avengers:infinitywar', 7),
    ('Bacurau', 'bacurau', 7),
    ('Baisers volés', 'baisersvoles', 7),
    ('Band of Outsiders', 'bandofoutsiders', 7),
    ('Bande de filles', 'bandedefilles', 7),
    ('Baraka', 'baraka', 7),
    ('Barberousse', 'barberousse', 7),
    ('Barry Lyndon', 'barrylyndon', 7),
    ('Barton Fink', 'bartonfink', 7),
    ('Beau travail', 'beautravail', 7),
    ('Before Midnight', 'beforemidnight', 7),
    ('Before Sunrise', 'beforesunrise', 7),
    ('Before Sunset', 'beforesunset', 7),
    ('Belle de jour', 'belledejour', 7),
    ('Benny’s Video', 'benny’svideo', 7),
    ('Berlin', 'berlin', 7),
    ('Bienvenue Mister Chance', 'bienvenuemisterchance', 7),
    ('Biutiful', 'biutiful', 7),
    ('Bixa Travesty', 'bixatravesty', 7),
    ('Black Panther', 'blackpanther', 7),
    ('Black Panthers', 'blackpanthers', 7),
    ('Black Power Mixtape', 'blackpowermixtape', 7),
    ('Blade Runner', 'bladerunner', 7),
    ('Blow Out', 'blowout', 7),
    ('Blow-Up', 'blow-up', 7),
    ('Blue Velvet', 'bluevelvet', 7),
    ('Bob le flambeur', 'bobleflambeur', 7),
    ('Bonheur', 'bonheur', 7),
    ('Bonjour', 'bonjour', 7),
    ('Bonnie et Clyde', 'bonnieetclyde', 7),
    ('Bons baisers de Bruges', 'bonsbaisersdebruges', 7),
    ('Boogie Nights', 'boogienights', 7),
    ('Boro in the Box', 'borointhebox', 7),
    ('Boulevard du crépuscule', 'boulevardducrepuscule', 7),
    ('Brazil', 'brazil', 7),
    ('Breaking the Waves', 'breakingthewaves', 7),
    ('Breakwater', 'breakwater', 7),
    ('Breathless', 'breathless', 7),
    ('Bruce Lee and the Outlaw', 'bruceleeandtheoutlaw', 7),
    ('Brève histoire d’amour', 'brevehistoired’amour', 7),
    ('Brève rencontre', 'breverencontre', 7),
    ('Buddies', 'buddies', 7),
    ('Buffalo ’66', 'buffalo’66', 7),
    ('Burden of Dreams', 'burdenofdreams', 7),
    ('Burning', 'burning', 7),
    ('Butch Cassidy et le Kid', 'butchcassidyetlekid', 7),
    ('Cabaret', 'cabaret', 7),
    ('Caché', 'cache', 7),
    ('Cadet d’eau douce', 'cadetd’eaudouce', 7),
    ('Call Me by Your Name', 'callmebyyourname', 7),
    ('Canine', 'canine', 7),
    ('Captain America: Civil War', 'captainamerica:civilwar', 7),
    ('Captain Marvel', 'captainmarvel', 7),
    ('Casablanca', 'casablanca', 7),
    ('Casino', 'casino', 7),
    ('Ce magnifique gâteau!', 'cemagnifiquegateau!', 7),
    ('Cemetery of Splendour', 'cemeteryofsplendour', 7),
    ('Cendres et diamant', 'cendresetdiamant', 7),
    ('Central do Brasil', 'centraldobrasil', 7),
    ('Certains l’aiment chaud', 'certainsl’aimentchaud', 7),
    ('Cet obscur objet du désir', 'cetobscurobjetdudesir', 7),
    ('Chansons du deuxième étage', 'chansonsdudeuxiemeetage', 7),
    ('Chantons sous la pluie', 'chantonssouslapluie', 7),
    ('Charade', 'charade', 7),
    ('Chat noir, chat blanc', 'chatnoir,chatblanc', 7),
    ('Chien enragé', 'chienenrage', 7),
    ('Chinatown', 'chinatown', 7),
    ('Chronique d’un été', 'chroniqued’unete', 7),
    ('Chungking Express', 'chungkingexpress', 7),
    ('Cinq pièces faciles', 'cinqpiecesfaciles', 7),
    ('Cinéma Paradiso', 'cinemaparadiso', 7),
    ('Citizen Kane', 'citizenkane', 7),
    ('Close-up', 'close-up', 7),
    ('Cléo de 5 à 7', 'cleode5a7', 7),
    ('Compte sur moi', 'comptesurmoi', 7),
    ('Comédies et Proverbes: Le rayon vert', 'comediesetproverbes:lerayonvert', 7),
    ('Conversation secrète', 'conversationsecrete', 7),
    ('Copie conforme', 'copieconforme', 7),
    ('Corps et âme', 'corpsetame', 7),
    ('Crimes et délits', 'crimesetdelits', 7),
    ('Cris et chuchotements', 'crisetchuchotements', 7),
    ('Crooklyn', 'crooklyn', 7),
    ('Crumb', 'crumb', 7),
    ('Cría Cuervos', 'criacuervos', 7),
    ('Cure', 'cure', 7),
    ('Céline et Julie vont en bateau', 'celineetjulievontenbateau', 7),
    ('C’est arrivé près de chez vous', 'c’estarrivepresdechezvous', 7),
    ('Daguerréotypes', 'daguerreotypes', 7),
    ('Damnation', 'damnation', 7),
    ('Dancer in the Dark', 'dancerinthedark', 7),
    ('Dans la peau de John Malkovich', 'danslapeaudejohnmalkovich', 7),
    ('Dans ses yeux', 'danssesyeux', 7),
    ('De l’autre côté', 'del’autrecote', 7),
    ('Dead Man', 'deadman', 7),
    ('Derrière le miroir', 'derrierelemiroir', 7),
    ('Dersou Ouzala', 'dersououzala', 7),
    ('Des temps et des vents', 'destempsetdesvents', 7),
    ('Detachment', 'detachment', 7),
    ('Divorce à l’italienne', 'divorceal’italienne', 7),
    ('Do the Right Thing', 'dotherightthing', 7),
    ('Docteur Folamour ou : comment j’ai appris à ne plus m’en faire et à aimer la bombe', 'docteurfolamourou:commentj’aiapprisaneplusm’enfaireetaaimerlabombe', 7),
    ('Dogs Don’t Wear Pants', 'dogsdon’twearpants', 7),
    ('Dogville', 'dogville', 7),
    ('Domicile conjugal', 'domicileconjugal', 7),
    ('Douleur et gloire', 'douleuretgloire', 7),
    ('Douze hommes en colère', 'douzehommesencolere', 7),
    ('Down by Law', 'downbylaw', 7),
    ('Dream Work', 'dreamwork', 7),
    ('Drive', 'drive', 7),
    ('Dronningen', 'dronningen', 7),
    ('Du rififi chez les hommes', 'durififichezleshommes', 7),
    ('Du silence et des ombres', 'dusilenceetdesombres', 7),
    ('Echo', 'echo', 7),
    ('Ed Wood', 'edwood', 7),
    ('Eka & Natia, chronique d’une jeunesse géorgienne', 'eka&natia,chroniqued’unejeunessegeorgienne', 7),
    ('El Topo', 'eltopo', 7),
    ('Elephant Man', 'elephantman', 7),
    ('Ema', 'ema', 7),
    ('En attendant le carnaval', 'enattendantlecarnaval', 7),
    ('En quatrième vitesse', 'enquatriemevitesse', 7),
    ('Encounters at the End of the World', 'encountersattheendoftheworld', 7),
    ('End of Summer', 'endofsummer', 7),
    ('Ennemis intimes', 'ennemisintimes', 7),
    ('Enquête sur un citoyen au-dessus de tout soupçon', 'enquetesuruncitoyenau-dessusdetoutsoupcon', 7),
    ('Enter the Void', 'enterthevoid', 7),
    ('Entre le ciel et l’enfer', 'entrelecieletl’enfer', 7),
    ('Entr’acte', 'entr’acte', 7),
    ('Eraserhead', 'eraserhead', 7),
    ('Ernest et Célestine', 'ernestetcelestine', 7),
    ('Et là-bas, quelle heure est-il?', 'etla-bas,quelleheureest-il?', 7),
    ('Et pour quelques dollars de plus', 'etpourquelquesdollarsdeplus', 7),
    ('Eternal Sunshine of the Spotless Mind', 'eternalsunshineofthespotlessmind', 7),
    ('Europa', 'europa', 7),
    ('Europe 51', 'europe51', 7),
    ('Evil Dead 2', 'evildead2', 7),
    ('Extraordinary Stories', 'extraordinarystories', 7),
    ('Face à face', 'faceaface', 7),
    ('Faces', 'faces', 7),
    ('Faites le mur', 'faiteslemur', 7),
    ('Falstaff', 'falstaff', 7),
    ('Family Romance, LLC', 'familyromance,llc', 7),
    ('Fanny et Alexandre', 'fannyetalexandre', 7),
    ('Fantasia', 'fantasia', 7),
    ('Fantastic Mr. Fox', 'fantasticmr.fox', 7),
    ('Farewell Amor', 'farewellamor', 7),
    ('Fargo', 'fargo', 7),
    ('Fast and Furious 7', 'fastandfurious7', 7),
    ('Fast and Furious 8', 'fastandfurious8', 7),
    ('Faust, une légende allemande', 'faust,unelegendeallemande', 7),
    ('Faux-semblants', 'faux-semblants', 7),
    ('Femmes au bord de la crise de nerfs', 'femmesauborddelacrisedenerfs', 7),
    ('Fenêtre sur cour', 'fenetresurcour', 7),
    ('Festen', 'festen', 7),
    ('Fight Club', 'fightclub', 7),
    ('Fish Tank', 'fishtank', 7),
    ('Fitzcarraldo', 'fitzcarraldo', 7),
    ('Frances Ha', 'francesha', 7),
    ('Frankenstein', 'frankenstein', 7),
    ('Frankenstein Junior', 'frankensteinjunior', 7),
    ('Freaks : La Monstrueuse Parade', 'freaks:lamonstrueuseparade', 7),
    ('Freedom', 'freedom', 7),
    ('French Connection', 'frenchconnection', 7),
    ('Full Metal Jacket', 'fullmetaljacket', 7),
    ('Funny Games', 'funnygames', 7),
    ('Gay USA', 'gayusa', 7),
    ('Ghost in the Shell', 'ghostintheshell', 7),
    ('Gimme Shelter', 'gimmeshelter', 7),
    ('Glengarry', 'glengarry', 7),
    ('Good Bye, Dragon Inn', 'goodbye,dragoninn', 7),
    ('Good Time', 'goodtime', 7),
    ('Goodbye, Children', 'goodbye,children', 7),
    ('Grey Gardens', 'greygardens', 7),
    ('Grizzly Man', 'grizzlyman', 7),
    ('Hana-bi – feux d’artifice', 'hana-bi–feuxd’artifice', 7),
    ('Hannah et ses soeurs', 'hannahetsessoeurs', 7),
    ('Happy Together', 'happytogether', 7),
    ('Harakiri', 'harakiri', 7),
    ('Harold et Maude', 'haroldetmaude', 7),
    ('Harry Potter et les Reliques de la Mort : Partie 2', 'harrypotteretlesreliquesdelamort:partie2', 7),
    ('Harry Potter à l’école des sorciers', 'harrypotteral’ecoledessorciers', 7),
    ('Haute pègre', 'hautepegre', 7),
    ('Head-on', 'head-on', 7),
    ('Heat', 'heat', 7),
    ('Hedgehog in the fog', 'hedgehoginthefog', 7),
    ('Herbes flottantes', 'herbesflottantes', 7),
    ('Heureux comme Lazzaro', 'heureuxcommelazzaro', 7),
    ('Hiroshima, mon amour', 'hiroshima,monamour', 7),
    ('Holy Motors', 'holymotors', 7),
    ('Home', 'home', 7),
    ('Hoop Dreams', 'hoopdreams', 7),
    ('House', 'house', 7),
    ('Hunger', 'hunger', 7),
    ('Husbands', 'husbands', 7),
    ('I Am Not a Witch', 'iamnotawitch', 7),
    ('I Still Hide to Smoke', 'istillhidetosmoke', 7),
    ('Ida', 'ida', 7),
    ('If....', 'if....', 7),
    ('Il est difficile d’être un dieu', 'ilestdifficiled’etreundieu', 7),
    ('Il posto', 'ilposto', 7),
    ('Il était une fois dans l’Ouest', 'iletaitunefoisdansl’ouest', 7),
    ('Il était une fois en Amérique', 'iletaitunefoisenamerique', 7),
    ('Il était une fois en Anatolie', 'iletaitunefoisenanatolie', 7),
    ('Illumination', 'illumination', 7),
    ('Impitoyable', 'impitoyable', 7),
    ('In the Mood for Love', 'inthemoodforlove', 7),
    ('Incendies', 'incendies', 7),
    ('Inception', 'inception', 7),
    ('Indianara', 'indianara', 7),
    ('Indiscrétions', 'indiscretions', 7),
    ('Inglourious Basterds', 'inglouriousbasterds', 7),
    ('Inland Sea', 'inlandsea', 7),
    ('Intouchables', 'intouchables', 7),
    ('Iron Man 3', 'ironman3', 7),
    ('Ivan le Terrible, Partie I', 'ivanleterrible,partiei', 7),
    ('Ivy', 'ivy', 7),
    ('Jacquot de Nantes', 'jacquotdenantes', 7),
    ('Je ne suis pas votre nègre', 'jenesuispasvotrenegre', 7),
    ('Jean-Michel Basquiat: The Radiant Child', 'jean-michelbasquiat:theradiantchild', 7),
    ('Jeanne Dielman, 23, Quai du Commerce, 1080 Bruxelles', 'jeannedielman,23,quaiducommerce,1080bruxelles', 7),
    ('Jeux dangereux', 'jeuxdangereux', 7),
    ('Jeux interdits', 'jeuxinterdits', 7),
    ('Jiro Rêve de Sushi', 'jirorevedesushi', 7),
    ('Jodorowsky’s Dune', 'jodorowsky’sdune', 7),
    ('John McCabe', 'johnmccabe', 7),
    ('Johnny Guitare', 'johnnyguitare', 7),
    ('Joker', 'joker', 7),
    ('Jour de colère', 'jourdecolere', 7),
    ('Journal d’un curé de campagne', 'journald’uncuredecampagne', 7),
    ('Journal intime', 'journalintime', 7),
    ('Jules et Jim', 'julesetjim', 7),
    ('Juliette des esprits', 'juliettedesesprits', 7),
    ('Junun', 'junun', 7),
    ('Jurassic Park', 'jurassicpark', 7),
    ('Jurassic World', 'jurassicworld', 7),
    ('Jurassic World: Fallen Kingdom', 'jurassicworld:fallenkingdom', 7),
    ('Kagemusha', 'kagemusha', 7),
    ('Kes', 'kes', 7),
    ('Kiki la petite sorcière', 'kikilapetitesorciere', 7),
    ('Killer of Sheep', 'killerofsheep', 7),
    ('Kirikou et la sorcière', 'kirikouetlasorciere', 7),
    ('Koyaanisqatsi', 'koyaanisqatsi', 7),
    ('Kwaidan', 'kwaidan', 7),
    ('L.A. Confidential', 'l.a.confidential', 7),
    ('La Chasse', 'lachasse', 7),
    ('La Horde sauvage', 'lahordesauvage', 7),
    ('La Mort aux trousses', 'lamortauxtrousses', 7),
    ('La Reine des neiges', 'lareinedesneiges', 7),
    ('La Reine des neiges 2', 'lareinedesneiges2', 7),
    ('La Soupe au canard', 'lasoupeaucanard', 7),
    ('La Splendeur des Ambersons', 'lasplendeurdesambersons', 7),
    ('La balade sauvage', 'labaladesauvage', 7),
    ('La ballade de Bruno', 'laballadedebruno', 7),
    ('La barbe à papa', 'labarbeapapa', 7),
    ('La bataille d’Alger', 'labatailled’alger', 7),
    ('La belle et la bête', 'labelleetlabete', 7),
    ('La belle noiseuse', 'labellenoiseuse', 7),
    ('La chevauchée fantastique', 'lachevaucheefantastique', 7),
    ('La cité de Dieu', 'lacitededieu', 7),
    ('La ciénaga', 'lacienaga', 7),
    ('La collectionneuse', 'lacollectionneuse', 7),
    ('La complainte du sentier', 'lacomplaintedusentier', 7),
    ('La corde', 'lacorde', 7),
    ('La cérémonie', 'laceremonie', 7),
    ('La dame de Shanghai', 'ladamedeshanghai', 7),
    ('La dame du vendredi', 'ladameduvendredi', 7),
    ('La dernière corvée', 'ladernierecorvee', 7),
    ('La dernière séance', 'laderniereseance', 7),
    ('La dolce vita', 'ladolcevita', 7),
    ('La double vie de Véronique', 'ladoubleviedeveronique', 7),
    ('La famille Tenenbaum', 'lafamilletenenbaum', 7),
    ('La favorite', 'lafavorite', 7),
    ('La femme de l’aviateur', 'lafemmedel’aviateur', 7),
    ('La femme des sables', 'lafemmedessables', 7),
    ('La fiancée de Frankenstein', 'lafianceedefrankenstein', 7),
    ('La fille aux allumettes', 'lafilleauxallumettes', 7),
    ('La forteresse cachée', 'laforteressecachee', 7),
    ('La fureur de vivre', 'lafureurdevivre', 7),
    ('La garçonnière', 'lagarconniere', 7),
    ('La grande bellezza', 'lagrandebellezza', 7),
    ('La grande illusion', 'lagrandeillusion', 7),
    ('La grande évasion', 'lagrandeevasion', 7),
    ('La griffe du passé', 'lagriffedupasse', 7),
    ('La grotte des rêves perdus', 'lagrottedesrevesperdus', 7),
    ('La grève', 'lagreve', 7),
    ('La guerre des étoiles', 'laguerredesetoiles', 7),
    ('La haine', 'lahaine', 7),
    ('La honte', 'lahonte', 7),
    ('La jetée', 'lajetee', 7),
    ('La ligne rouge', 'lalignerouge', 7),
    ('La liste de Schindler', 'lalistedeschindler', 7),
    ('La maison et le monde', 'lamaisonetlemonde', 7),
    ('La maman et la putain', 'lamamanetlaputain', 7),
    ('La marque du tueur', 'lamarquedutueur', 7),
    ('La merditude des choses', 'lamerditudedeschoses', 7),
    ('La montagne sacrée', 'lamontagnesacree', 7),
    ('La mort de Dante Lăzărescu', 'lamortdedantelazarescu', 7),
    ('La noire de...', 'lanoirede...', 7),
    ('La nourriture', 'lanourriture', 7),
    ('La nuit', 'lanuit', 7),
    ('La nuit américaine', 'lanuitamericaine', 7),
    ('La nuit des morts-vivants', 'lanuitdesmorts-vivants', 7),
    ('La nuit du chasseur', 'lanuitduchasseur', 7),
    ('La passion de Jeanne d’Arc', 'lapassiondejeanned’arc', 7),
    ('La pianiste', 'lapianiste', 7),
    ('La piel que habito', 'lapielquehabito', 7),
    ('La planète sauvage', 'laplanetesauvage', 7),
    ('La poursuite infernale', 'lapoursuiteinfernale', 7),
    ('La prisonnière du désert', 'laprisonnieredudesert', 7),
    ('La promesse', 'lapromesse', 7),
    ('La randonnée', 'larandonnee', 7),
    ('La religieuse', 'lareligieuse', 7),
    ('La rue de la honte', 'laruedelahonte', 7),
    ('La rue des crocodiles', 'laruedescrocodiles', 7),
    ('La rue rouge', 'laruerouge', 7),
    ('La ruée vers l’or', 'larueeversl’or', 7),
    ('La règle du jeu', 'laregledujeu', 7),
    ('La soif du mal', 'lasoifdumal', 7),
    ('La sorcellerie à travers les âges', 'lasorcellerieatraverslesages', 7),
    ('La source', 'lasource', 7),
    ('La strada', 'lastrada', 7),
    ('La terre', 'laterre', 7),
    ('La tortue rouge', 'latortuerouge', 7),
    ('La tour de guet', 'latourdeguet', 7),
    ('La vache', 'lavache', 7),
    ('La valse des pantins', 'lavalsedespantins', 7),
    ('La vie de Brian', 'laviedebrian', 7),
    ('La vie des autres', 'laviedesautres', 7),
    ('La vie est belle', 'lavieestbelle', 7),
    ('La visite de la fanfare', 'lavisitedelafanfare', 7),
    ('Lacombe, Lucien', 'lacombe,lucien', 7),
    ('Lady Vengeance', 'ladyvengeance', 7),
    ('Laura', 'laura', 7),
    ('Laurence Anyways', 'laurenceanyways', 7),
    ('Lawrence d’Arabie', 'lawrenced’arabie', 7),
    ('Le Ballon Rouge', 'leballonrouge', 7),
    ('Le Cabinet du docteur Caligari', 'lecabinetdudocteurcaligari', 7),
    ('Le Cameraman', 'lecameraman', 7),
    ('Le Château de l’araignée', 'lechateaudel’araignee', 7),
    ('Le Cirque', 'lecirque', 7),
    ('Le Colonel Blimp', 'lecolonelblimp', 7),
    ('Le Dictateur', 'ledictateur', 7),
    ('Le Géant de fer', 'legeantdefer', 7),
    ('Le Havre', 'lehavre', 7),
    ('Le Hobbit : Un voyage inattendu', 'lehobbit:unvoyageinattendu', 7),
    ('Le Kid', 'lekid', 7),
    ('Le Livre de la jungle', 'lelivredelajungle', 7),
    ('Le Monde de Dory', 'lemondededory', 7),
    ('Le Mécano de la General – Le mécano de la Générale', 'lemecanodelageneral–lemecanodelagenerale', 7),
    ('Le Narcisse noir', 'lenarcissenoir', 7),
    ('Le Paradis de Suzaki', 'leparadisdesuzaki', 7),
    ('Le Roi lionNote 1', 'leroilionnote1', 7),
    ('Le Seigneur des anneaux : Le Retour du roi', 'leseigneurdesanneaux:leretourduroi', 7),
    ('Le Voleur de Bicyclette', 'levoleurdebicyclette', 7),
    ('Le bateau', 'lebateau', 7),
    ('Le bon, la brute et le truand', 'lebon,labruteetletruand', 7),
    ('Le bonheur', 'lebonheur', 7),
    ('Le carnaval des âmes', 'lecarnavaldesames', 7),
    ('Le cercle rouge', 'lecerclerouge', 7),
    ('Le chant de la forêt', 'lechantdelaforet', 7),
    ('Le charme discret de la bourgeoisie', 'lecharmediscretdelabourgeoisie', 7),
    ('Le cheval de Turin', 'lechevaldeturin', 7),
    ('Le château ambulant', 'lechateauambulant', 7),
    ('Le château dans le ciel', 'lechateaudansleciel', 7),
    ('Le conformiste', 'leconformiste', 7),
    ('Le conte de la princesse Kaguya', 'lecontedelaprincessekaguya', 7),
    ('Le corbeau', 'lecorbeau', 7),
    ('Le couteau dans l’eau', 'lecouteaudansl’eau', 7),
    ('Le crime était presque parfait', 'lecrimeetaitpresqueparfait', 7),
    ('Le cuirassé Potemkine', 'lecuirassepotemkine', 7),
    ('Le cuisinier, le voleur, sa femme et son amant', 'lecuisinier,levoleur,safemmeetsonamant', 7),
    ('Le cygne de cristal', 'lecygnedecristal', 7),
    ('Le dernier des hommes', 'ledernierdeshommes', 7),
    ('Le dernier métro', 'lederniermetro', 7),
    ('Le diable, probablement...', 'lediable,probablement...', 7),
    ('Le dieu d’osier', 'ledieud’osier', 7),
    ('Le dossier Adams', 'ledossieradams', 7),
    ('Le doulos', 'ledoulos', 7),
    ('Le droit du plus fort', 'ledroitduplusfort', 7),
    ('Le désert rouge', 'ledesertrouge', 7),
    ('Le fabuleux destin d’Amélie Poulain', 'lefabuleuxdestind’ameliepoulain', 7),
    ('Le fantôme de la liberté', 'lefantomedelaliberte', 7),
    ('Le faucon maltais', 'lefauconmaltais', 7),
    ('Le feu follet', 'lefeufollet', 7),
    ('Le fils', 'lefils', 7),
    ('Le fils de Saul', 'lefilsdesaul', 7),
    ('Le fjord des baleines', 'lefjorddesbaleines', 7),
    ('Le funambule', 'lefunambule', 7),
    ('Le gamin au vélo', 'legaminauvelo', 7),
    ('Le garde du corps', 'legardeducorps', 7),
    ('Le genou de Claire', 'legenoudeclaire', 7),
    ('Le gouffre aux chimères', 'legouffreauxchimeres', 7),
    ('Le goût de la cerise', 'legoutdelacerise', 7),
    ('Le goût du saké', 'legoutdusake', 7),
    ('Le grand chantage', 'legrandchantage', 7),
    ('Le grand sommeil', 'legrandsommeil', 7),
    ('Le guépard', 'leguepard', 7),
    ('Le hasard', 'lehasard', 7),
    ('Le labyrinthe de Pan', 'lelabyrinthedepan', 7),
    ('Le lac aux oies sauvages', 'lelacauxoiessauvages', 7),
    ('Le lauréat', 'lelaureat', 7),
    ('Le locataire', 'lelocataire', 7),
    ('Le magicien d’Oz', 'lemagiciend’oz', 7),
    ('Le mariage de Maria Braun', 'lemariagedemariabraun', 7),
    ('Le miroir', 'lemiroir', 7),
    ('Le monde d’Apu', 'lemonded’apu', 7),
    ('Le mystère Picasso', 'lemysterepicasso', 7),
    ('Le mépris', 'lemepris', 7),
    ('Le parrain', 'leparrain', 7),
    ('Le parrain II', 'leparrainii', 7),
    ('Le pianiste', 'lepianiste', 7),
    ('Le point de non-retour', 'lepointdenon-retour', 7),
    ('Le poirier sauvage', 'lepoiriersauvage', 7),
    ('Le pont de la rivière Kwai', 'lepontdelarivierekwai', 7),
    ('Le pont des Arts', 'lepontdesarts', 7),
    ('Le port de la drogue', 'leportdeladrogue', 7),
    ('Le port de l’angoisse', 'leportdel’angoisse', 7),
    ('Le privé', 'leprive', 7),
    ('Le procès', 'leproces', 7),
    ('Le quattro volte', 'lequattrovolte', 7),
    ('Le retour', 'leretour', 7),
    ('Le roi et l’oiseau', 'leroietl’oiseau', 7),
    ('Le roi lion', 'leroilion', 7),
    ('Le ruban blanc', 'lerubanblanc', 7),
    ('Le sacrifice', 'lesacrifice', 7),
    ('Le salaire de la peur', 'lesalairedelapeur', 7),
    ('Le samouraï', 'lesamourai', 7),
    ('Le sang d’un poète', 'lesangd’unpoete', 7),
    ('Le scaphandre et le papillon', 'lescaphandreetlepapillon', 7),
    ('Le secret de Veronika Voss', 'lesecretdeveronikavoss', 7),
    ('Le seigneur des anneaux – La communauté de l’anneau', 'leseigneurdesanneaux–lacommunautedel’anneau', 7),
    ('Le seigneur des anneaux – Le retour du roi', 'leseigneurdesanneaux–leretourduroi', 7),
    ('Le seigneur des anneaux – Les deux tours', 'leseigneurdesanneaux–lesdeuxtours', 7),
    ('Le sel de la Terre', 'leseldelaterre', 7),
    ('Le septième continent', 'leseptiemecontinent', 7),
    ('Le septième sceau', 'leseptiemesceau', 7),
    ('Le silence', 'lesilence', 7),
    ('Le silence de la mer', 'lesilencedelamer', 7),
    ('Le silence des agneaux', 'lesilencedesagneaux', 7),
    ('Le souffle au coeur', 'lesouffleaucoeur', 7),
    ('Le tango de Satan', 'letangodesatan', 7),
    ('Le temps des gitans', 'letempsdesgitans', 7),
    ('Le testament du docteur Mabuse', 'letestamentdudocteurmabuse', 7),
    ('Le testament d’Orphée', 'letestamentd’orphee', 7),
    ('Le tombeau des lucioles', 'letombeaudeslucioles', 7),
    ('Le train sifflera 3 fois', 'letrainsifflera3fois', 7),
    ('Le troisième homme', 'letroisiemehomme', 7),
    ('Le trou', 'letrou', 7),
    ('Le trésor de la Sierra Madre', 'letresordelasierramadre', 7),
    ('Le vent nous emportera', 'leventnousemportera', 7),
    ('Le vent se lève', 'leventseleve', 7),
    ('Le violent', 'leviolent', 7),
    ('Le visage d’un autre', 'levisaged’unautre', 7),
    ('Le visiteur', 'levisiteur', 7),
    ('Le voyage dans la lune', 'levoyagedanslalune', 7),
    ('Le voyage de Chihiro', 'levoyagedechihiro', 7),
    ('Le voyeur', 'levoyeur', 7),
    ('Les 39 marches', 'les39marches', 7),
    ('Les Funérailles des roses', 'lesfuneraillesdesroses', 7),
    ('Les Indestructibles 2', 'lesindestructibles2', 7),
    ('Les Minions', 'lesminions', 7),
    ('Les Oiseaux', 'lesoiseaux', 7),
    ('Les Salauds dorment en paix', 'lessalaudsdormentenpaix', 7),
    ('Les Temps Modernes', 'lestempsmodernes', 7),
    ('Les Tortues volent aussi', 'lestortuesvolentaussi', 7),
    ('Les affranchis', 'lesaffranchis', 7),
    ('Les ailes du désir', 'lesailesdudesir', 7),
    ('Les amants crucifiés', 'lesamantscrucifies', 7),
    ('Les amants de Montparnasse', 'lesamantsdemontparnasse', 7),
    ('Les amants du Pont-Neuf', 'lesamantsdupont-neuf', 7),
    ('Les amants du cercle polaire', 'lesamantsducerclepolaire', 7),
    ('Les amours d’une blonde', 'lesamoursd’uneblonde', 7),
    ('Les anges déchus', 'lesangesdechus', 7),
    ('Les aventuriers de l’arche perdue', 'lesaventuriersdel’archeperdue', 7),
    ('Les bruits de Recife', 'lesbruitsderecife', 7),
    ('Les chaussons rouges', 'leschaussonsrouges', 7),
    ('Les chevaux de feu', 'leschevauxdefeu', 7),
    ('Les chiens de paille', 'leschiensdepaille', 7),
    ('Les collections de Mithat Bey', 'lescollectionsdemithatbey', 7),
    ('Les communiants', 'lescommuniants', 7),
    ('Les contes de la lune vague après la pluie', 'lescontesdelalunevagueapreslapluie', 7),
    ('Les demoiselles de Rochefort', 'lesdemoisellesderochefort', 7),
    ('Les diables', 'lesdiables', 7),
    ('Les diaboliques', 'lesdiaboliques', 7),
    ('Les dites cariatides', 'lesditescariatides', 7),
    ('Les délices de Tokyo', 'lesdelicesdetokyo', 7),
    ('Les enchaînés', 'lesenchaines', 7),
    ('Les enfants du paradis', 'lesenfantsduparadis', 7),
    ('Les feux de la rampe', 'lesfeuxdelarampe', 7),
    ('Les fils de l’homme', 'lesfilsdel’homme', 7),
    ('Les fraises sauvages', 'lesfraisessauvages', 7),
    ('Les frissons de l’angoisse', 'lesfrissonsdel’angoisse', 7),
    ('Les garçons sauvages', 'lesgarconssauvages', 7),
    ('Les glaneurs et la glaneuse', 'lesglaneursetlaglaneuse', 7),
    ('Les harmonies Werckmeister', 'lesharmonieswerckmeister', 7),
    ('Les hirondelles de Kaboul', 'leshirondellesdekaboul', 7),
    ('Les hommes du président', 'leshommesdupresident', 7),
    ('Les innocents', 'lesinnocents', 7),
    ('Les larmes amères de Petra von Kant', 'leslarmesameresdepetravonkant', 7),
    ('Les lumières de la ville', 'leslumieresdelaville', 7),
    ('Les misérables', 'lesmiserables', 7),
    ('Les moissons du ciel', 'lesmoissonsduciel', 7),
    ('Les nuits de Cabiria', 'lesnuitsdecabiria', 7),
    ('Les nuits de la pleine lune', 'lesnuitsdelapleinelune', 7),
    ('Les parapluies de Cherbourg', 'lesparapluiesdecherbourg', 7),
    ('Les petites marguerites', 'lespetitesmarguerites', 7),
    ('Les plages d’Agnès', 'lesplagesd’agnes', 7),
    ('Les plus belles années de notre vie', 'lesplusbellesanneesdenotrevie', 7),
    ('Les possibilités du dialogue', 'lespossibilitesdudialogue', 7),
    ('Les quatre cents coups', 'lesquatrecentscoups', 7),
    ('Les raisins de la colère', 'lesraisinsdelacolere', 7),
    ('Les sentiers de la gloire', 'lessentiersdelagloire', 7),
    ('Les sept samouraïs', 'lesseptsamourais', 7),
    ('Les triplettes de Belleville', 'lestriplettesdebelleville', 7),
    ('Les vacances de Monsieur Hulot', 'lesvacancesdemonsieurhulot', 7),
    ('Les vitelloni – Les inutiles', 'lesvitelloni–lesinutiles', 7),
    ('Les voyages de Sullivan', 'lesvoyagesdesullivan', 7),
    ('Les yeux sans visage', 'lesyeuxsansvisage', 7),
    ('Les évadés', 'lesevades', 7),
    ('Lettre d’une inconnue', 'lettred’uneinconnue', 7),
    ('Leviathan', 'leviathan', 7),
    ('Leçons de ténèbres', 'leconsdetenebres', 7),
    ('Lilya 4-Ever', 'lilya4-ever', 7),
    ('Locataires', 'locataires', 7),
    ('Lola', 'lola', 7),
    ('Los Angeles Plays Itself', 'losangelesplaysitself', 7),
    ('Lost Highway', 'losthighway', 7),
    ('Lost in Translation', 'lostintranslation', 7),
    ('Loulou', 'loulou', 7),
    ('Love Exposure', 'loveexposure', 7),
    ('Love Meetings', 'lovemeetings', 7),
    ('Love Streams – Torrents d’amour', 'lovestreams–torrentsd’amour', 7),
    ('Luke la main froide', 'lukelamainfroide', 7),
    ('Lumière silencieuse', 'lumieresilencieuse', 7),
    ('Là-Haut', 'la-haut', 7),
    ('Léon', 'leon', 7),
    ('Léon Morin, prêtre', 'leonmorin,pretre', 7),
    ('L’Arnaque', 'l’arnaque', 7),
    ('L’Atalante – Le chaland qui passe', 'l’atalante–lechalandquipasse', 7),
    ('L’amateur', 'l’amateur', 7),
    ('L’ami américain', 'l’amiamericain', 7),
    ('L’ami de mon amie', 'l’amidemonamie', 7),
    ('L’amour l’après-midi', 'l’amourl’apres-midi', 7),
    ('L’ange bleu', 'l’angebleu', 7),
    ('L’ange exterminateur', 'l’angeexterminateur', 7),
    ('L’année dernière à Marienbad', 'l’anneederniereamarienbad', 7),
    ('L’année des treize lunes', 'l’anneedestreizelunes', 7),
    ('L’arche russe', 'l’archerusse', 7),
    ('L’argent', 'l’argent', 7),
    ('L’armée des douze singes', 'l’armeedesdouzesinges', 7),
    ('L’armée des ombres', 'l’armeedesombres', 7),
    ('L’arnaqueur', 'l’arnaqueur', 7),
    ('L’assassinat de Jesse James par le lâche Robert Ford', 'l’assassinatdejessejamesparlelacherobertford', 7),
    ('L’aurore', 'l’aurore', 7),
    ('L’avventura', 'l’avventura', 7),
    ('L’enfance d’Ivan', 'l’enfanced’ivan', 7),
    ('L’enfer d’Henri-Georges Clouzot', 'l’enferd’henri-georgesclouzot', 7),
    ('L’enfer est à lui', 'l’enferestalui', 7),
    ('L’enigme de Kaspar Hauser', 'l’enigmedekasparhauser', 7),
    ('L’esprit de la ruche', 'l’espritdelaruche', 7),
    ('L’exorciste', 'l’exorciste', 7),
    ('L’heure du loup', 'l’heureduloup', 7),
    ('L’homme qui tua Liberty Valance', 'l’hommequitualibertyvalance', 7),
    ('L’homme qui voulait savoir', 'l’hommequivoulaitsavoir', 7),
    ('L’homme sans passé', 'l’hommesanspasse', 7),
    ('L’homme à la caméra', 'l’hommealacamera', 7),
    ('L’illusionniste', 'l’illusionniste', 7),
    ('L’impossible monsieur Bébé', 'l’impossiblemonsieurbebe', 7),
    ('L’inconnu du Nord-Express', 'l’inconnudunord-express', 7),
    ('L’intendant Sansho', 'l’intendantsansho', 7),
    ('L’odeur de la papaye verte', 'l’odeurdelapapayeverte', 7),
    ('L’ombre d’un doute', 'l’ombred’undoute', 7),
    ('L’ultime razzia', 'l’ultimerazzia', 7),
    ('L’âge d’or', 'l’aged’or', 7),
    ('L’éclipse', 'l’eclipse', 7),
    ('L’éloge du rien', 'l’elogedurien', 7),
    ('L’éternité et un jour', 'l’eterniteetunjour', 7),
    ('L’étrange Noël de monsieur Jack', 'l’etrangenoeldemonsieurjack', 7),
    ('L’étreinte du serpent', 'l’etreinteduserpent', 7),
    ('L’été de Kikujiro', 'l’etedekikujiro', 7),
    ('L’évangile selon St Matthieu', 'l’evangileselonstmatthieu', 7),
    ('M le maudit', 'mlemaudit', 7),
    ('Ma nuit chez Maud', 'manuitchezmaud', 7),
    ('Ma vie de courgette', 'maviedecourgette', 7),
    ('Maborosi', 'maborosi', 7),
    ('Macadam cow-boy', 'macadamcow-boy', 7),
    ('Macadam à deux voies', 'macadamadeuxvoies', 7),
    ('Madame de...', 'madamede...', 7),
    ('Mademoiselle', 'mademoiselle', 7),
    ('Magnolia', 'magnolia', 7),
    ('Malcolm X', 'malcolmx', 7),
    ('Mamma Roma', 'mammaroma', 7),
    ('Manhattan', 'manhattan', 7),
    ('Marina Abramović: The Artist is Present', 'marinaabramovic:theartistispresent', 7),
    ('Maris et femmes', 'marisetfemmes', 7),
    ('Marketa Lazarová', 'marketalazarova', 7),
    ('Mary et Max.', 'maryetmax.', 7),
    ('Masculin, féminin: 15 faits précis', 'masculin,feminin:15faitsprecis', 7),
    ('Matrix', 'matrix', 7),
    ('Matthias et Maxime', 'matthiasetmaxime', 7),
    ('Mauvais sang', 'mauvaissang', 7),
    ('Mean Streets', 'meanstreets', 7),
    ('Melancholia', 'melancholia', 7),
    ('Memento', 'memento', 7),
    ('Memories of Murder', 'memoriesofmurder', 7),
    ('Meshes of the Afternoon', 'meshesoftheafternoon', 7),
    ('Metropolis', 'metropolis', 7),
    ('Meurtre d’un bookmaker chinois', 'meurtred’unbookmakerchinois', 7),
    ('Microhabitat', 'microhabitat', 7),
    ('Mikey et Nicky', 'mikeyetnicky', 7),
    ('Millennium Actress', 'millenniumactress', 7),
    ('Miller’s Crossing', 'miller’scrossing', 7),
    ('Milou en mai', 'milouenmai', 7),
    ('Mirage de la vie', 'miragedelavie', 7),
    ('Mishima, une vie en quatre chapitres', 'mishima,unevieenquatrechapitres', 7),
    ('Missing – Porté disparu', 'missing–portedisparu', 7),
    ('Moi, Daniel Blake', 'moi,danielblake', 7),
    ('Moi, moche et méchant 2', 'moi,mocheetmechant2', 7),
    ('Moi, moche et méchant 3', 'moi,mocheetmechant3', 7),
    ('Mommy', 'mommy', 7),
    ('Mon homme Godfrey', 'monhommegodfrey', 7),
    ('Mon oncle', 'mononcle', 7),
    ('Mon oncle d’Amérique', 'mononcled’amerique', 7),
    ('Mon voisin Totoro', 'monvoisintotoro', 7),
    ('Monika', 'monika', 7),
    ('Monsieur Klein', 'monsieurklein', 7),
    ('Monsieur Smith au sénat', 'monsieursmithausenat', 7),
    ('Monsieur Verdoux', 'monsieurverdoux', 7),
    ('Monthy Python, le sens de la vie', 'monthypython,lesensdelavie', 7),
    ('Monty Python, Sacré Graal', 'montypython,sacregraal', 7),
    ('Moon – La face cachée', 'moon–lafacecachee', 7),
    ('Moonlight', 'moonlight', 7),
    ('Moonrise Kingdom', 'moonrisekingdom', 7),
    ('Morse', 'morse', 7),
    ('Mort à Venise', 'mortavenise', 7),
    ('Mother', 'mother', 7),
    ('Mouchette', 'mouchette', 7),
    ('Mulholland Drive', 'mulhollanddrive', 7),
    ('Mur Murs', 'murmurs', 7),
    ('Mustang', 'mustang', 7),
    ('My dinner with André', 'mydinnerwithandre', 7),
    ('Mysterious Skin', 'mysteriousskin', 7),
    ('Mystery Train', 'mysterytrain', 7),
    ('Mère et fils', 'mereetfils', 7),
    ('Mélo', 'melo', 7),
    ('Nainsukh', 'nainsukh', 7),
    ('Naked', 'naked', 7),
    ('Nashville', 'nashville', 7),
    ('Nausicaä de la vallée du vent', 'nausicaadelavalleeduvent', 7),
    ('Ne coupez pas!', 'necoupezpas!', 7),
    ('Ne croyez surtout pas que je hurle', 'necroyezsurtoutpasquejehurle', 7),
    ('Ne vous retournez pas', 'nevousretournezpas', 7),
    ('Network, main basse sur la télévision', 'network,mainbassesurlatelevision', 7),
    ('New York-Miami', 'newyork-miami', 7),
    ('Night on Earth', 'nightonearth', 7),
    ('Ninotchka', 'ninotchka', 7),
    ('No country for old men – Non, ce pays n’est pas pour le vieil homme', 'nocountryforoldmen–non,cepaysn’estpaspourlevieilhomme', 7),
    ('No direction home : Bob Dylan', 'nodirectionhome:bobdylan', 7),
    ('Noblesse oblige', 'noblesseoblige', 7),
    ('Nobody Knows', 'nobodyknows', 7),
    ('Nobody’s Business', 'nobody’sbusiness', 7),
    ('Nos années sauvages', 'nosanneessauvages', 7),
    ('Nos meilleures années – 1ère Partie', 'nosmeilleuresannees–1erepartie', 7),
    ('Nosferatu le vampire', 'nosferatulevampire', 7),
    ('Nosferatu – fantôme de la nuit', 'nosferatu–fantomedelanuit', 7),
    ('Nostalghia', 'nostalghia', 7),
    ('Nostalgie de la lumière', 'nostalgiedelalumiere', 7),
    ('Notre pain quotidien', 'notrepainquotidien', 7),
    ('Notre petite soeur', 'notrepetitesoeur', 7),
    ('Nous, les vivants', 'nous,lesvivants', 7),
    ('Nouvelle donne', 'nouvelledonne', 7),
    ('Nuages de mai', 'nuagesdemai', 7),
    ('Nuit et brouillard', 'nuitetbrouillard', 7),
    ('Oldboy', 'oldboy', 7),
    ('Olla', 'olla', 7),
    ('Oncle Boonmee, celui qui se souvient de ses vies anterieures', 'oncleboonmee,celuiquisesouvientdesesviesanterieures', 7),
    ('Onibaba', 'onibaba', 7),
    ('Opening Night', 'openingnight', 7),
    ('Opération diabolique', 'operationdiabolique', 7),
    ('Orange mécanique', 'orangemecanique', 7),
    ('Ordet', 'ordet', 7),
    ('Orphée', 'orphee', 7),
    ('Oslo, 31 août', 'oslo,31aout', 7),
    ('Overseas', 'overseas', 7),
    ('Où est la maison de mon ami?', 'ouestlamaisondemonami?', 7),
    ('Paprika', 'paprika', 7),
    ('Papusza', 'papusza', 7),
    ('Parasite', 'parasite', 7),
    ('Paris Is Burning', 'parisisburning', 7),
    ('Paris, Texas', 'paris,texas', 7),
    ('Parle avec elle', 'parleavecelle', 7),
    ('Partie de campagne', 'partiedecampagne', 7),
    ('Paterson', 'paterson', 7),
    ('Pauline à la plage', 'paulinealaplage', 7),
    ('Paysage dans le Brouillard', 'paysagedanslebrouillard', 7),
    ('Peace', 'peace', 7),
    ('Perfect Blue', 'perfectblue', 7),
    ('Persepolis', 'persepolis', 7),
    ('Persona', 'persona', 7),
    ('Petit Dieter doit voler', 'petitdieterdoitvoler', 7),
    ('Phantom Thread', 'phantomthread', 7),
    ('Phoenix', 'phoenix', 7),
    ('Pickpocket', 'pickpocket', 7),
    ('Pierrot le fou', 'pierrotlefou', 7),
    ('Pina', 'pina', 7),
    ('Pink Floyd – The Wall', 'pinkfloyd–thewall', 7),
    ('Pique-nique à Hanging Rock', 'pique-niqueahangingrock', 7),
    ('Pirates des Caraïbes : La Fontaine de Jouvence', 'piratesdescaraibes:lafontainedejouvence', 7),
    ('Pirates des Caraïbes : Le Secret du coffre maudit', 'piratesdescaraibes:lesecretducoffremaudit', 7),
    ('Pirosmani', 'pirosmani', 7),
    ('Pitié pour eux', 'pitiepoureux', 7),
    ('Pixote, la loi du plus faible', 'pixote,laloiduplusfaible', 7),
    ('Play Time', 'playtime', 7),
    ('Plein soleil', 'pleinsoleil', 7),
    ('Ponette', 'ponette', 7),
    ('Ponyo sur la falaise', 'ponyosurlafalaise', 7),
    ('Popeye the Sailor Meets Sindbad the Sailor', 'popeyethesailormeetssindbadthesailor', 7),
    ('Porco Rosso', 'porcorosso', 7),
    ('Portrait de la jeune fille en feu', 'portraitdelajeunefilleenfeu', 7),
    ('Possession', 'possession', 7),
    ('Pour une poignée de dollars', 'pourunepoigneededollars', 7),
    ('Poésie', 'poesie', 7),
    ('Princesse Mononoké', 'princessemononoke', 7),
    ('Printemps tardif', 'printempstardif', 7),
    ('Printemps, été, automne, hiver... et printemps', 'printemps,ete,automne,hiver...etprintemps', 7),
    ('Profession: Reporter', 'profession:reporter', 7),
    ('Psychose', 'psychose', 7),
    ('Pulp Fiction', 'pulpfiction', 7),
    ('Punishment Park', 'punishmentpark', 7),
    ('Quai des Orfèvres', 'quaidesorfevres', 7),
    ('Quand la ville dort', 'quandlavilledort', 7),
    ('Quand nous étions sorcières', 'quandnousetionssorcieres', 7),
    ('Quand passent les cigognes', 'quandpassentlescigognes', 7),
    ('Que le spectacle commence', 'quelespectaclecommence', 7),
    ('Qui a peur de Virginia Woolf?', 'quiapeurdevirginiawoolf?', 7),
    ('Qu’est-il arrivé à Baby Jane?', 'qu’est-ilarriveababyjane?', 7),
    ('Raging Bull', 'ragingbull', 7),
    ('Ran', 'ran', 7),
    ('Rashomon', 'rashomon', 7),
    ('Ratcatcher', 'ratcatcher', 7),
    ('Rbg', 'rbg', 7),
    ('Rebecca', 'rebecca', 7),
    ('Rendez-vous', 'rendez-vous', 7),
    ('Requiem for a Dream', 'requiemforadream', 7),
    ('Requiem pour un massacre', 'requiempourunmassacre', 7),
    ('Reservoir Dogs', 'reservoirdogs', 7),
    ('Retour', 'retour', 7),
    ('Retour vers le futur', 'retourverslefutur', 7),
    ('Revanche', 'revanche', 7),
    ('Rio bravo', 'riobravo', 7),
    ('Rocco et ses frères', 'roccoetsesfreres', 7),
    ('Rogue One: A Star Wars Story', 'rogueone:astarwarsstory', 7),
    ('Roma', 'roma', 7),
    ('Rome ville ouverte', 'romevilleouverte', 7),
    ('Rosemary’s Baby', 'rosemary’sbaby', 7),
    ('Rosetta', 'rosetta', 7),
    ('Rushmore', 'rushmore', 7),
    ('Rusty James', 'rustyjames', 7),
    ('Ryuichi Sakamoto: Coda', 'ryuichisakamoto:coda', 7),
    ('Règlement de comptes', 'reglementdecomptes', 7),
    ('Réminiscences d’un voyage en Lituanie', 'reminiscencesd’unvoyageenlituanie', 7),
    ('Répulsion', 'repulsion', 7),
    ('Réveil dans la terreur', 'reveildanslaterreur', 7),
    ('Rêves', 'reves', 7),
    ('Safe', 'safe', 7),
    ('Salaam Bombay!', 'salaambombay!', 7),
    ('Salut les cubains', 'salutlescubains', 7),
    ('Salé, sucré', 'sale,sucre', 7),
    ('Samsara', 'samsara', 7),
    ('Sang pour sang', 'sangpoursang', 7),
    ('Sanjuro', 'sanjuro', 7),
    ('Sans soleil', 'sanssoleil', 7),
    ('Sans toit ni loi', 'sanstoitniloi', 7),
    ('Santa sangre', 'santasangre', 7),
    ('Sayat Nova – La couleur de la grenade', 'sayatnova–lacouleurdelagrenade', 7),
    ('Scarface', 'scarface', 7),
    ('Scorpio Rising', 'scorpiorising', 7),
    ('Scènes de la vie conjugale', 'scenesdelavieconjugale', 7),
    ('Se7en', 'se7en', 7),
    ('Secrets et mensonges', 'secretsetmensonges', 7),
    ('Selfie', 'selfie', 7),
    ('Senna', 'senna', 7),
    ('Serpico', 'serpico', 7),
    ('Shadows', 'shadows', 7),
    ('Shaun of the Dead', 'shaunofthedead', 7),
    ('Sherlock Junior', 'sherlockjunior', 7),
    ('Shining', 'shining', 7),
    ('Shock Corridor', 'shockcorridor', 7),
    ('Short Cuts', 'shortcuts', 7),
    ('Si tu tends l’oreille', 'situtendsl’oreille', 7),
    ('Sieranevada', 'sieranevada', 7),
    ('Sigur Rós – Heima', 'sigurros–heima', 7),
    ('Simon du désert', 'simondudesert', 7),
    ('Sivas', 'sivas', 7),
    ('Skyfall', 'skyfall', 7),
    ('So Long, My Son', 'solong,myson', 7),
    ('Solaris', 'solaris', 7),
    ('Something Useful', 'somethinguseful', 7),
    ('Sommeil d’hiver', 'sommeild’hiver', 7),
    ('Sonate d’automne', 'sonated’automne', 7),
    ('Sonatine, mélodie mortelle', 'sonatine,melodiemortelle', 7),
    ('Sourires d’une nuit d’été', 'souriresd’unenuitd’ete', 7),
    ('Souvenirs, goutte à goutte', 'souvenirs,goutteagoutte', 7),
    ('Soy Cuba', 'soycuba', 7),
    ('Spider-Man: Far From Home', 'spider-man:farfromhome', 7),
    ('Spider-Man: Nouvelle Génération', 'spider-man:nouvellegeneration', 7),
    ('Spinal Tap', 'spinaltap', 7),
    ('Stalker', 'stalker', 7),
    ('Star Wars : Episode I : La Menace Fantôme', 'starwars:episodei:lamenacefantome', 7),
    ('Star Wars : Episode V – L’Empire contre-attaque', 'starwars:episodev–l’empirecontre-attaque', 7),
    ('Star Wars, épisode II : L’Attaque des clones', 'starwars,episodeii:l’attaquedesclones', 7),
    ('Star Wars, épisode III : La revanche des Siths', 'starwars,episodeiii:larevanchedessiths', 7),
    ('Star Wars, épisode IX : L’Ascension de Skywalker', 'starwars,episodeix:l’ascensiondeskywalker', 7),
    ('Star Wars, épisode V : L’Empire contre-attaque', 'starwars,episodev:l’empirecontre-attaque', 7),
    ('Star Wars, épisode VI : Le retour du Jedi', 'starwars,episodevi:leretourdujedi', 7),
    ('Star Wars, épisode VII : Le Réveil de la Force', 'starwars,episodevii:lereveildelaforce', 7),
    ('Star Wars, épisode VIII : Les Derniers Jedi', 'starwars,episodeviii:lesderniersjedi', 7),
    ('States of Grace', 'statesofgrace', 7),
    ('Still Life', 'stilllife', 7),
    ('Still Walking', 'stillwalking', 7),
    ('Stop Making Sense', 'stopmakingsense', 7),
    ('Stranger Than Paradise', 'strangerthanparadise', 7),
    ('Structure de cristal', 'structuredecristal', 7),
    ('Sueurs froides', 'sueursfroides', 7),
    ('Sugar Man', 'sugarman', 7),
    ('Sun in the Last Days of the Shogunate', 'suninthelastdaysoftheshogunate', 7),
    ('Sur les quais', 'surlesquais', 7),
    ('Suspiria', 'suspiria', 7),
    ('Swagger', 'swagger', 7),
    ('Swallow', 'swallow', 7),
    ('Sympathy for Mr Vengeance', 'sympathyformrvengeance', 7),
    ('Syndromes and a Century', 'syndromesandacentury', 7),
    ('Synecdoche, New York', 'synecdoche,newyork', 7),
    ('Tabou', 'tabou', 7),
    ('Talking About Trees', 'talkingabouttrees', 7),
    ('Tampopo', 'tampopo', 7),
    ('Taxi Driver', 'taxidriver', 7),
    ('Taxi Téhéran', 'taxiteheran', 7),
    ('Tel père, tel fils', 'telpere,telfils', 7),
    ('Terminator 2 – Le jugement dernier', 'terminator2–lejugementdernier', 7),
    ('Tetsuo', 'tetsuo', 7),
    ('The Act of Killing', 'theactofkilling', 7),
    ('The Ascent', 'theascent', 7),
    ('The Basilisks', 'thebasilisks', 7),
    ('The Big Lebowski', 'thebiglebowski', 7),
    ('The Border Fence', 'theborderfence', 7),
    ('The Collector', 'thecollector', 7),
    ('The Cove – La baie de la honte', 'thecove–labaiedelahonte', 7),
    ('The Dark Knight', 'thedarkknight', 7),
    ('The Dark Knight : Le Chevalier noir', 'thedarkknight:lechevaliernoir', 7),
    ('The Dark Knight Rises', 'thedarkknightrises', 7),
    ('The Devil and Daniel Johnston', 'thedevilanddanieljohnston', 7),
    ('The End of Evangelion', 'theendofevangelion', 7),
    ('The Fall', 'thefall', 7),
    ('The Five Obstructions', 'thefiveobstructions', 7),
    ('The Florida Project', 'thefloridaproject', 7),
    ('The Fog of War', 'thefogofwar', 7),
    ('The Grand Budapest Hotel', 'thegrandbudapesthotel', 7),
    ('The Hole', 'thehole', 7),
    ('The House Is Black', 'thehouseisblack', 7),
    ('The Killer', 'thekiller', 7),
    ('The Lighthouse', 'thelighthouse', 7),
    ('The Lost Weekend', 'thelostweekend', 7),
    ('The Lunchbox', 'thelunchbox', 7),
    ('The Master', 'themaster', 7),
    ('The Orphan', 'theorphan', 7),
    ('The Play', 'theplay', 7),
    ('The Point', 'thepoint', 7),
    ('The Selfish Giant', 'theselfishgiant', 7),
    ('The Servant', 'theservant', 7),
    ('The Small Town', 'thesmalltown', 7),
    ('The Terrorizers', 'theterrorizers', 7),
    ('The Thing', 'thething', 7),
    ('The Tree of Life', 'thetreeoflife', 7),
    ('The Trial', 'thetrial', 7),
    ('The Vampires of Poverty', 'thevampiresofpoverty', 7),
    ('The White Diamond', 'thewhitediamond', 7),
    ('The Wolf House', 'thewolfhouse', 7),
    ('There will be blood', 'therewillbeblood', 7),
    ('This Is England', 'thisisengland', 7),
    ('Théorème', 'theoreme', 7),
    ('Tirez sur le pianiste', 'tirezsurlepianiste', 7),
    ('Titanic', 'titanic', 7),
    ('Tokyo Godfathers', 'tokyogodfathers', 7),
    ('Tokyo Sonata', 'tokyosonata', 7),
    ('Tomboy', 'tomboy', 7),
    ('Toni Erdmann', 'tonierdmann', 7),
    ('Toss-Up', 'toss-up', 7),
    ('Tous les autres s’appellent Ali', 'touslesautress’appellentali', 7),
    ('Tous les matins du monde', 'touslesmatinsdumonde', 7),
    ('Tout ce que le ciel permet', 'toutcequelecielpermet', 7),
    ('Tout sur ma mère', 'toutsurmamere', 7),
    ('Toy Story', 'toystory', 7),
    ('Toy Story 2', 'toystory2', 7),
    ('Toy Story 3', 'toystory3', 7),
    ('Toy Story 4', 'toystory4', 7),
    ('Toyland', 'toyland', 7),
    ('Trains étroitement surveillés', 'trainsetroitementsurveilles', 7),
    ('Trainspotting', 'trainspotting', 7),
    ('Transformers 3 : La Face cachée de la Lune', 'transformers3:lafacecacheedelalune', 7),
    ('Transformers : L’Âge de l’extinction', 'transformers:l’agedel’extinction', 7),
    ('Transit', 'transit', 7),
    ('Tripping With Nils Frahm', 'trippingwithnilsfrahm', 7),
    ('Trois couleurs: Blanc', 'troiscouleurs:blanc', 7),
    ('Trois couleurs: Bleu', 'troiscouleurs:bleu', 7),
    ('Trois couleurs: Rouge', 'troiscouleurs:rouge', 7),
    ('Trois femmes', 'troisfemmes', 7),
    ('Tropical Malady', 'tropicalmalady', 7),
    ('Trust Me', 'trustme', 7),
    ('Tu ne tueras point', 'tunetueraspoint', 7),
    ('Tuer Bill, volume 1', 'tuerbill,volume1', 7),
    ('Twin Peaks – Les 7 derniers jours de Laura Palmer', 'twinpeaks–les7derniersjoursdelaurapalmer', 7),
    ('Tyrannosaur', 'tyrannosaur', 7),
    ('Témoin à charge', 'temoinacharge', 7),
    ('Umberto D.', 'umbertod.', 7),
    ('Un après-midi de chien', 'unapres-mididechien', 7),
    ('Un chien andalou', 'unchienandalou', 7),
    ('Un coeur pris au piège', 'uncoeurprisaupiege', 7),
    ('Un condamné à mort s’est échappé', 'uncondamneamorts’estechappe', 7),
    ('Un crime dans la tête', 'uncrimedanslatete', 7),
    ('Un jour sans fin', 'unjoursansfin', 7),
    ('Un prophète', 'unprophete', 7),
    ('Un temps pour l’ivresse des chevaux', 'untempspourl’ivressedeschevaux', 7),
    ('Un tramway nommé désir', 'untramwaynommedesir', 7),
    ('Uncle Yanco', 'uncleyanco', 7),
    ('Underground', 'underground', 7),
    ('Une affaire de famille', 'uneaffairedefamille', 7),
    ('Une belle journée d’été', 'unebellejourneed’ete', 7),
    ('Une femme disparaît', 'unefemmedisparait', 7),
    ('Une femme est une femme', 'unefemmeestunefemme', 7),
    ('Une femme sous influence', 'unefemmesousinfluence', 7),
    ('Une grande fille', 'unegrandefille', 7),
    ('Une histoire vraie', 'unehistoirevraie', 7),
    ('Une passion', 'unepassion', 7),
    ('Une question de vie ou de mort', 'unequestiondevieoudemort', 7),
    ('Une séparation', 'uneseparation', 7),
    ('Une vie simple', 'uneviesimple', 7),
    ('Usual Suspects', 'usualsuspects', 7),
    ('Uzak – Lointain', 'uzak–lointain', 7),
    ('Vacances romaines', 'vacancesromaines', 7),
    ('Valse avec Bachir', 'valseavecbachir', 7),
    ('Valérie au pays des merveilles', 'valerieaupaysdesmerveilles', 7),
    ('Vampires en toute intimité', 'vampiresentouteintimite', 7),
    ('Vampyr, ou l’étrange aventure de David Gray', 'vampyr,oul’etrangeaventurededavidgray', 7),
    ('Vera Drake', 'veradrake', 7),
    ('Victoria', 'victoria', 7),
    ('Videodrome', 'videodrome', 7),
    ('Viridiana', 'viridiana', 7),
    ('Virus Tropical', 'virustropical', 7),
    ('Visages, villages', 'visages,villages', 7),
    ('Vive l’amour', 'vivel’amour', 7),
    ('Vivre', 'vivre', 7),
    ('Vivre sa vie: Film en douze tableaux', 'vivresavie:filmendouzetableaux', 7),
    ('Vol au-dessus d’un nid de coucou', 'volau-dessusd’unniddecoucou', 7),
    ('Volver', 'volver', 7),
    ('Voyage au bout de l’enfer', 'voyageauboutdel’enfer', 7),
    ('Voyage en Italie', 'voyageenitalie', 7),
    ('Voyage à Tokyo', 'voyageatokyo', 7),
    ('Vérités et mensonges', 'veritesetmensonges', 7),
    ('WALLE', 'walle', 7),
    ('Wadjda', 'wadjda', 7),
    ('Wallace & Gromit: Le mauvais pantalon', 'wallace&gromit:lemauvaispantalon', 7),
    ('We Need to Talk About Kevin', 'weneedtotalkaboutkevin', 7),
    ('Week-end', 'week-end', 7),
    ('Wild Tales', 'wildtales', 7),
    ('Winnipeg, mon amour', 'winnipeg,monamour', 7),
    ('Withnail and I', 'withnailandi', 7),
    ('Wittgenstein Plays Chess With Marcel Duchamp, or How Not To Do Philosophy', 'wittgensteinplayschesswithmarcelduchamp,orhownottodophilosophy', 7),
    ('Woman at War', 'womanatwar', 7),
    ('Written on the Wind', 'writtenonthewind', 7),
    ('X-Files', 'x-files', 7),
    ('X-Files: Régénération', 'x-files:regeneration', 7),
    ('X-Men 2', 'x-men2', 7),
    ('X-Men : Dark Phoenix', 'x-men:darkphoenix', 7),
    ('X-Men Le commencement', 'x-menlecommencement', 7),
    ('X-Men Origins: Wolverine', 'x-menorigins:wolverine', 7),
    ('X-Men – L’Affrontement final', 'x-men–l’affrontementfinal', 7),
    ('X-Men: Apocalypse', 'x-men:apocalypse', 7),
    ('X-Men: Days of Future Past', 'x-men:daysoffuturepast', 7),
    ('XX', 'xx', 7),
    ('Xenia', 'xenia', 7),
    ('Xiao Mei', 'xiaomei', 7),
    ('Yi Yi', 'yiyi', 7),
    ('Your Turn', 'yourturn', 7),
    ('Zelig', 'zelig', 7),
    ('Zombie', 'zombie', 7),
    ('Zombies', 'zombies', 7),
    ('Zootopie', 'zootopie', 7),
    ('Zéro de conduite : Jeunes diables au collège', 'zerodeconduite:jeunesdiablesaucollege', 7),
    ('acteur en A', 'acteurena', 7),
    ('acteur en B', 'acteurenb', 7),
    ('acteur en C', 'acteurenc', 7),
    ('acteur en D', 'acteurend', 7),
    ('acteur en E', 'acteurene', 7),
    ('acteur en F', 'acteurenf', 7),
    ('acteur en G', 'acteureng', 7),
    ('acteur en H', 'acteurenh', 7),
    ('acteur en I', 'acteureni', 7),
    ('acteur en J', 'acteurenj', 7),
    ('acteur en K', 'acteurenk', 7),
    ('acteur en L', 'acteurenl', 7),
    ('acteur en M', 'acteurenm', 7),
    ('acteur en N', 'acteurenn', 7),
    ('acteur en O', 'acteureno', 7),
    ('acteur en P', 'acteurenp', 7),
    ('acteur en Q', 'acteurenq', 7),
    ('acteur en R', 'acteurenr', 7),
    ('acteur en S', 'acteurens', 7),
    ('acteur en T', 'acteurent', 7),
    ('acteur en U', 'acteurenu', 7),
    ('acteur en V', 'acteurenv', 7),
    ('acteur en W', 'acteurenw', 7),
    ('acteur en X', 'acteurenx', 7),
    ('acteur en Y', 'acteureny', 7),
    ('acteur en Z', 'acteurenz', 7),
    ('dessin animé en A', 'dessinanimeena', 7),
    ('dessin animé en B', 'dessinanimeenb', 7),
    ('dessin animé en C', 'dessinanimeenc', 7),
    ('dessin animé en D', 'dessinanimeend', 7),
    ('dessin animé en E', 'dessinanimeene', 7),
    ('dessin animé en F', 'dessinanimeenf', 7),
    ('dessin animé en G', 'dessinanimeeng', 7),
    ('dessin animé en H', 'dessinanimeenh', 7),
    ('dessin animé en I', 'dessinanimeeni', 7),
    ('dessin animé en J', 'dessinanimeenj', 7),
    ('dessin animé en K', 'dessinanimeenk', 7),
    ('dessin animé en L', 'dessinanimeenl', 7),
    ('dessin animé en M', 'dessinanimeenm', 7),
    ('dessin animé en N', 'dessinanimeenn', 7),
    ('dessin animé en O', 'dessinanimeeno', 7),
    ('dessin animé en P', 'dessinanimeenp', 7),
    ('dessin animé en Q', 'dessinanimeenq', 7),
    ('dessin animé en R', 'dessinanimeenr', 7),
    ('dessin animé en S', 'dessinanimeens', 7),
    ('dessin animé en T', 'dessinanimeent', 7),
    ('dessin animé en U', 'dessinanimeenu', 7),
    ('dessin animé en V', 'dessinanimeenv', 7),
    ('dessin animé en W', 'dessinanimeenw', 7),
    ('dessin animé en X', 'dessinanimeenx', 7),
    ('dessin animé en Y', 'dessinanimeeny', 7),
    ('dessin animé en Z', 'dessinanimeenz', 7),
    ('film Disney en A', 'filmdisneyena', 7),
    ('film Disney en B', 'filmdisneyenb', 7),
    ('film Disney en C', 'filmdisneyenc', 7),
    ('film Disney en D', 'filmdisneyend', 7),
    ('film Disney en E', 'filmdisneyene', 7),
    ('film Disney en F', 'filmdisneyenf', 7),
    ('film Disney en G', 'filmdisneyeng', 7),
    ('film Disney en H', 'filmdisneyenh', 7),
    ('film Disney en I', 'filmdisneyeni', 7),
    ('film Disney en J', 'filmdisneyenj', 7),
    ('film Disney en K', 'filmdisneyenk', 7),
    ('film Disney en L', 'filmdisneyenl', 7),
    ('film Disney en M', 'filmdisneyenm', 7),
    ('film Disney en N', 'filmdisneyenn', 7),
    ('film Disney en O', 'filmdisneyeno', 7),
    ('film Disney en P', 'filmdisneyenp', 7),
    ('film Disney en Q', 'filmdisneyenq', 7),
    ('film Disney en R', 'filmdisneyenr', 7),
    ('film Disney en S', 'filmdisneyens', 7),
    ('film Disney en T', 'filmdisneyent', 7),
    ('film Disney en U', 'filmdisneyenu', 7),
    ('film Disney en V', 'filmdisneyenv', 7),
    ('film Disney en W', 'filmdisneyenw', 7),
    ('film Disney en X', 'filmdisneyenx', 7),
    ('film Disney en Y', 'filmdisneyeny', 7),
    ('film Disney en Z', 'filmdisneyenz', 7),
    ('série en A', 'serieena', 7),
    ('série en B', 'serieenb', 7),
    ('série en C', 'serieenc', 7),
    ('série en D', 'serieend', 7),
    ('série en E', 'serieene', 7),
    ('série en F', 'serieenf', 7),
    ('série en G', 'serieeng', 7),
    ('série en H', 'serieenh', 7),
    ('série en I', 'serieeni', 7),
    ('série en J', 'serieenj', 7),
    ('série en K', 'serieenk', 7),
    ('série en L', 'serieenl', 7),
    ('série en M', 'serieenm', 7),
    ('série en N', 'serieenn', 7),
    ('série en O', 'serieeno', 7),
    ('série en P', 'serieenp', 7),
    ('série en Q', 'serieenq', 7),
    ('série en R', 'serieenr', 7),
    ('série en S', 'serieens', 7),
    ('série en T', 'serieent', 7),
    ('série en U', 'serieenu', 7),
    ('série en V', 'serieenv', 7),
    ('série en W', 'serieenw', 7),
    ('série en X', 'serieenx', 7),
    ('série en Y', 'serieeny', 7),
    ('série en Z', 'serieenz', 7),
    ('xXx', 'xxx', 7),
    ('À la recherche de Vivian Maier', 'alarecherchedevivianmaier', 7),
    ('À l’est d’Eden', 'al’estd’eden', 7),
    ('À nos amours', 'anosamours', 7),
    ('À propos d’Elly', 'aproposd’elly', 7),
    ('À travers le miroir', 'atraverslemiroir', 7),
    ('Ève', 'eve', 7),
    ('Épouses et concubines', 'epousesetconcubines', 7),
    ('Été 93', 'ete93', 7),
    ('Été précoce', 'eteprecoce', 7),
    ('Être et avoir', 'etreetavoir', 7)
ON CONFLICT (mot_normalized, categorie_id) DO NOTHING;
