INSERT INTO mots (mot, mot_normalized, categorie_id) VALUES
    ('Accrobranche', 'accrobranche', 8),
    ('Acrosport', 'acrosport', 8),
    ('Agility', 'agility', 8),
    ('Airsoft', 'airsoft', 8),
    ('Alpinisme', 'alpinisme', 8),
    ('Apnée', 'apnee', 8),
    ('Aquabike', 'aquabike', 8),
    ('Aquabiking', 'aquabiking', 8),
    ('Aquagym', 'aquagym', 8),
    ('Aquajogging', 'aquajogging', 8),
    ('Aquarunning', 'aquarunning', 8),
    ('Aquathlon', 'aquathlon', 8),
    ('Aquatriathlon', 'aquatriathlon', 8),
    ('Arts du cirque', 'artsducirque', 8),
    ('Athlétisme', 'athletisme', 8),
    ('Aviation', 'aviation', 8),
    ('Aviron', 'aviron', 8),
    ('Aérobic', 'aerobic', 8),
    ('Aéromodélisme', 'aeromodelisme', 8),
    ('Aérostation', 'aerostation', 8),
    ('Aïkido', 'aikido', 8),
    ('BMX', 'bmx', 8),
    ('Baby-foot', 'baby-foot', 8),
    ('Badminton', 'badminton', 8),
    ('Ball-Trap', 'ball-trap', 8),
    ('Bandy', 'bandy', 8),
    ('Base jump', 'basejump', 8),
    ('Base-jump', 'base-jump', 8),
    ('Baseball', 'baseball', 8),
    ('Basketball', 'basketball', 8),
    ('Bateau-Dragon', 'bateau-dragon', 8),
    ('Beach soccer', 'beachsoccer', 8),
    ('Beach tennis', 'beachtennis', 8),
    ('Beach volley', 'beachvolley', 8),
    ('Biathlon', 'biathlon', 8),
    ('Billard', 'billard', 8),
    ('Bloc', 'bloc', 8),
    ('Boardercross', 'boardercross', 8),
    ('Bobsleigh', 'bobsleigh', 8),
    ('Boccia', 'boccia', 8),
    ('Bodyboard', 'bodyboard', 8),
    ('Bodybuilding', 'bodybuilding', 8),
    ('Boomerang', 'boomerang', 8),
    ('Bouzkachi', 'bouzkachi', 8),
    ('Bowling', 'bowling', 8),
    ('Boxe', 'boxe', 8),
    ('Boxe anglaise', 'boxeanglaise', 8),
    ('Boxe chinoise', 'boxechinoise', 8),
    ('Boxe française', 'boxefrancaise', 8),
    ('Boxe thaïlandaise', 'boxethailandaise', 8),
    ('Bras de fer', 'brasdefer', 8),
    ('Bridge', 'bridge', 8),
    ('Béhourd', 'behourd', 8),
    ('Caber', 'caber', 8),
    ('Calcio florentin', 'calcioflorentin', 8),
    ('Canicross', 'canicross', 8),
    ('Canne de combat', 'cannedecombat', 8),
    ('Canoë', 'canoe', 8),
    ('Canoë-kayak', 'canoe-kayak', 8),
    ('Canyoning', 'canyoning', 8),
    ('Canyonisme', 'canyonisme', 8),
    ('Capoeira', 'capoeira', 8),
    ('Carrom', 'carrom', 8),
    ('Catch', 'catch', 8),
    ('Chanbara', 'chanbara', 8),
    ('Char à voile', 'charavoile', 8),
    ('Chase tag', 'chasetag', 8),
    ('Cheerleading', 'cheerleading', 8),
    ('Cirque', 'cirque', 8),
    ('Claquettes', 'claquettes', 8),
    ('Coasteering', 'coasteering', 8),
    ('Combat', 'combat', 8),
    ('Compétition automobile', 'competitionautomobile', 8),
    ('Corde à sauter', 'cordeasauter', 8),
    ('Course', 'course', 8),
    ('Course aérienne', 'courseaerienne', 8),
    ('Course camarguaise', 'coursecamarguaise', 8),
    ('Course de cote', 'coursedecote', 8),
    ('Course de drones', 'coursededrones', 8),
    ('Course d’obstacles', 'coursed’obstacles', 8),
    ('Course d’orientation', 'coursed’orientation', 8),
    ('Course landaise', 'courselandaise', 8),
    ('Course à pied', 'courseapied', 8),
    ('Cricket', 'cricket', 8),
    ('Croquet', 'croquet', 8),
    ('Cross', 'cross', 8),
    ('Cross training', 'crosstraining', 8),
    ('Cross triathlon', 'crosstriathlon', 8),
    ('Cross-country', 'cross-country', 8),
    ('Crossfit', 'crossfit', 8),
    ('Culturisme', 'culturisme', 8),
    ('Curling', 'curling', 8),
    ('Cyclisme', 'cyclisme', 8),
    ('Cyclisme artistique', 'cyclismeartistique', 8),
    ('Cyclisme sur piste', 'cyclismesurpiste', 8),
    ('Cyclisme sur route', 'cyclismesurroute', 8),
    ('Cyclo cross', 'cyclocross', 8),
    ('Cyclotourisme', 'cyclotourisme', 8),
    ('Dames', 'dames', 8),
    ('Danse', 'danse', 8),
    ('Danse africaine', 'danseafricaine', 8),
    ('Danse classique', 'danseclassique', 8),
    ('Danse contemporaine', 'dansecontemporaine', 8),
    ('Danse country', 'dansecountry', 8),
    ('Danse indienne', 'danseindienne', 8),
    ('Danse orientale', 'danseorientale', 8),
    ('Danse rock', 'danserock', 8),
    ('Danse sportive', 'dansesportive', 8),
    ('Danse sur glace', 'dansesurglace', 8),
    ('Deltaplane', 'deltaplane', 8),
    ('Disc golf', 'discgolf', 8),
    ('Dodgeball', 'dodgeball', 8),
    ('Double Dutch', 'doubledutch', 8),
    ('Dragon boat', 'dragonboat', 8),
    ('Dragster', 'dragster', 8),
    ('Drift', 'drift', 8),
    ('Duathlon', 'duathlon', 8),
    ('Décathlon', 'decathlon', 8),
    ('Enduro', 'enduro', 8),
    ('Equitation', 'equitation', 8),
    ('Escalade', 'escalade', 8),
    ('Escrime', 'escrime', 8),
    ('Esports', 'esports', 8),
    ('Extreme Football League', 'extremefootballleague', 8),
    ('Fierljeppen', 'fierljeppen', 8),
    ('Fitness', 'fitness', 8),
    ('Flag', 'flag', 8),
    ('Flamenco', 'flamenco', 8),
    ('Floorball', 'floorball', 8),
    ('Fléchettes', 'flechettes', 8),
    ('Folkrace', 'folkrace', 8),
    ('Football', 'football', 8),
    ('Football américain', 'footballamericain', 8),
    ('Football australien', 'footballaustralien', 8),
    ('Football gaélique', 'footballgaelique', 8),
    ('Footgolf', 'footgolf', 8),
    ('Footing', 'footing', 8),
    ('Footpool', 'footpool', 8),
    ('Force athlétique', 'forceathletique', 8),
    ('Full contact', 'fullcontact', 8),
    ('Funboard', 'funboard', 8),
    ('Futsal', 'futsal', 8),
    ('Giraviation', 'giraviation', 8),
    ('Glisse', 'glisse', 8),
    ('Golf', 'golf', 8),
    ('Gouren', 'gouren', 8),
    ('Grappling', 'grappling', 8),
    ('Gymnastique', 'gymnastique', 8),
    ('Gymnastique artistique', 'gymnastiqueartistique', 8),
    ('Gymnastique rythmique', 'gymnastiquerythmique', 8),
    ('Haka pei', 'hakapei', 8),
    ('Hakko-Ryu', 'hakko-ryu', 8),
    ('Haltérophilie', 'halterophilie', 8),
    ('Handball', 'handball', 8),
    ('Handisport', 'handisport', 8),
    ('Hapkido', 'hapkido', 8),
    ('Hip hop', 'hiphop', 8),
    ('Hockey', 'hockey', 8),
    ('Hockey subaquatique', 'hockeysubaquatique', 8),
    ('Hockey sur gazon', 'hockeysurgazon', 8),
    ('Hockey sur glace', 'hockeysurglace', 8),
    ('Horse ball', 'horseball', 8),
    ('Hurling', 'hurling', 8),
    ('Iaïdo', 'iaido', 8),
    ('Javelot tir sur cible', 'javelottirsurcible', 8),
    ('Jet ski', 'jetski', 8),
    ('Jetski', 'jetski', 8),
    ('Jett kune do', 'jettkunedo', 8),
    ('Jeu de paume', 'jeudepaume', 8),
    ('Jianzi', 'jianzi', 8),
    ('Jiu-jitsu brésilien', 'jiu-jitsubresilien', 8),
    ('Jodo', 'jodo', 8),
    ('Jorkyball', 'jorkyball', 8),
    ('Joutes', 'joutes', 8),
    ('Joutes nautiques', 'joutesnautiques', 8),
    ('Ju-Jitsu', 'ju-jitsu', 8),
    ('Judo', 'judo', 8),
    ('Kabaddi', 'kabaddi', 8),
    ('Kalarippayatt', 'kalarippayatt', 8),
    ('Kali Arnis Eskrima', 'kaliarniseskrima', 8),
    ('Kaninhop', 'kaninhop', 8),
    ('Karaté', 'karate', 8),
    ('Karting', 'karting', 8),
    ('Kayak', 'kayak', 8),
    ('Kempo', 'kempo', 8),
    ('Kendo', 'kendo', 8),
    ('Kenjutsu', 'kenjutsu', 8),
    ('Kick boxing', 'kickboxing', 8),
    ('Kin-ball', 'kin-ball', 8),
    ('Kitesurf', 'kitesurf', 8),
    ('Kitesurfing', 'kitesurfing', 8),
    ('Kobudo', 'kobudo', 8),
    ('Korfbal', 'korfbal', 8),
    ('Krav maga', 'kravmaga', 8),
    ('Krav-maga', 'krav-maga', 8),
    ('Kung fu', 'kungfu', 8),
    ('Kyokushinkai', 'kyokushinkai', 8),
    ('Kyudo', 'kyudo', 8),
    ('Lancer de disque', 'lancerdedisque', 8),
    ('Lancer de javelot', 'lancerdejavelot', 8),
    ('Lancer de marteau', 'lancerdemarteau', 8),
    ('Lancer de poids', 'lancerdepoids', 8),
    ('Luge', 'luge', 8),
    ('Luge de course', 'lugedecourse', 8),
    ('Lutte', 'lutte', 8),
    ('MMA', 'mma', 8),
    ('Marathon', 'marathon', 8),
    ('Marche', 'marche', 8),
    ('Marche aquatique', 'marcheaquatique', 8),
    ('Marche athlétique', 'marcheathletique', 8),
    ('Marche nordique', 'marchenordique', 8),
    ('Marche sportive', 'marchesportive', 8),
    ('Mixed martial art', 'mixedmartialart', 8),
    ('Monocycle', 'monocycle', 8),
    ('Moto', 'moto', 8),
    ('Moto cross', 'motocross', 8),
    ('Moto-ball', 'moto-ball', 8),
    ('Motoneige', 'motoneige', 8),
    ('Mountainboard', 'mountainboard', 8),
    ('Musculation', 'musculation', 8),
    ('Naban', 'naban', 8),
    ('Naginata', 'naginata', 8),
    ('Natation', 'natation', 8),
    ('Natation synchronisée', 'natationsynchronisee', 8),
    ('Nautisme', 'nautisme', 8),
    ('Netball', 'netball', 8),
    ('Ninjitsu', 'ninjitsu', 8),
    ('Nunchaku', 'nunchaku', 8),
    ('Omnikin', 'omnikin', 8),
    ('Paddle', 'paddle', 8),
    ('Padel', 'padel', 8),
    ('Paintball', 'paintball', 8),
    ('Pancrace', 'pancrace', 8),
    ('Parachutisme', 'parachutisme', 8),
    ('Paramoteur', 'paramoteur', 8),
    ('Parapente', 'parapente', 8),
    ('Parkour', 'parkour', 8),
    ('Patin à glace', 'patinaglace', 8),
    ('Patinage', 'patinage', 8),
    ('Patinage artistique', 'patinageartistique', 8),
    ('Patinage de vitesse', 'patinagedevitesse', 8),
    ('Patinage synchronisé', 'patinagesynchronise', 8),
    ('Pelote basque', 'pelotebasque', 8),
    ('Pencak-Silat', 'pencak-silat', 8),
    ('Pentathlon', 'pentathlon', 8),
    ('Pentathlon moderne', 'pentathlonmoderne', 8),
    ('Pesäpallo', 'pesapallo', 8),
    ('Peteca', 'peteca', 8),
    ('Pilates', 'pilates', 8),
    ('Ping-Pong', 'ping-pong', 8),
    ('Planche à voile', 'plancheavoile', 8),
    ('Planeur', 'planeur', 8),
    ('Plongeon', 'plongeon', 8),
    ('Plongée', 'plongee', 8),
    ('Plongée en apnée', 'plongeeenapnee', 8),
    ('Plumfoot', 'plumfoot', 8),
    ('Pole dance', 'poledance', 8),
    ('Polo', 'polo', 8),
    ('Pétanque', 'petanque', 8),
    ('Pêche', 'peche', 8),
    ('Pêche sportive', 'pechesportive', 8),
    ('Qi gong', 'qigong', 8),
    ('Quad', 'quad', 8),
    ('Quidditch', 'quidditch', 8),
    ('Quilles', 'quilles', 8),
    ('Qwan Ki Do', 'qwankido', 8),
    ('Rafting', 'rafting', 8),
    ('Ragga', 'ragga', 8),
    ('Raid', 'raid', 8),
    ('Rallycross', 'rallycross', 8),
    ('Rallye', 'rallye', 8),
    ('Rallye automobile', 'rallyeautomobile', 8),
    ('Randonnée', 'randonnee', 8),
    ('Raquette à neige', 'raquetteaneige', 8),
    ('Ringuette', 'ringuette', 8),
    ('Rink hockey', 'rinkhockey', 8),
    ('Rock', 'rock', 8),
    ('Rodéo', 'rodeo', 8),
    ('Roller', 'roller', 8),
    ('Roller derby', 'rollerderby', 8),
    ('Roller in line hockey', 'rollerinlinehockey', 8),
    ('Rugby', 'rugby', 8),
    ('Rugby subaquatique', 'rugbysubaquatique', 8),
    ('Rugby à XIII', 'rugbyaxiii', 8),
    ('Rugby à XV', 'rugbyaxv', 8),
    ('Rugby à sept', 'rugbyasept', 8),
    ('Régate', 'regate', 8),
    ('Salsa', 'salsa', 8),
    ('Samba', 'samba', 8),
    ('Sambo', 'sambo', 8),
    ('Sarbacane', 'sarbacane', 8),
    ('Saut en hauteur', 'sautenhauteur', 8),
    ('Saut en longueur', 'sautenlongueur', 8),
    ('Saut à la perche', 'sautalaperche', 8),
    ('Saut à ski', 'sautaski', 8),
    ('Sauvetage', 'sauvetage', 8),
    ('Savate', 'savate', 8),
    ('Self défense', 'selfdefense', 8),
    ('Sepak takraw', 'sepaktakraw', 8),
    ('Shinty', 'shinty', 8),
    ('Skateboard', 'skateboard', 8),
    ('Skater hockey', 'skaterhockey', 8),
    ('Skeleton', 'skeleton', 8),
    ('Ski', 'ski', 8),
    ('Ski acrobatique', 'skiacrobatique', 8),
    ('Ski alpin', 'skialpin', 8),
    ('Ski de fond', 'skidefond', 8),
    ('Ski nautique', 'skinautique', 8),
    ('Ski nordique', 'skinordique', 8),
    ('Skicross', 'skicross', 8),
    ('Slackline', 'slackline', 8),
    ('Slamball', 'slamball', 8),
    ('Snorkeling', 'snorkeling', 8),
    ('Snowboard', 'snowboard', 8),
    ('Snowkite', 'snowkite', 8),
    ('Snowscoot', 'snowscoot', 8),
    ('Snowskate', 'snowskate', 8),
    ('Softball', 'softball', 8),
    ('Speed riding', 'speedriding', 8),
    ('Spinning', 'spinning', 8),
    ('Spéléologie', 'speleologie', 8),
    ('Squash', 'squash', 8),
    ('Step', 'step', 8),
    ('Sumo', 'sumo', 8),
    ('Supermotard', 'supermotard', 8),
    ('Surf', 'surf', 8),
    ('Tae Bo', 'taebo', 8),
    ('Taekwondo', 'taekwondo', 8),
    ('Tai-chi-chuan', 'tai-chi-chuan', 8),
    ('Taihojutsu', 'taihojutsu', 8),
    ('Tambourin', 'tambourin', 8),
    ('Tango', 'tango', 8),
    ('Tau’a rapa nui', 'tau’arapanui', 8),
    ('Taï chi', 'taichi', 8),
    ('Taïso', 'taiso', 8),
    ('Tchoukball', 'tchoukball', 8),
    ('Tennis', 'tennis', 8),
    ('Tennis de table', 'tennisdetable', 8),
    ('Tennis léger', 'tennisleger', 8),
    ('Teqball', 'teqball', 8),
    ('Tir', 'tir', 8),
    ('Tir sportif', 'tirsportif', 8),
    ('Tir à l’arc', 'tiral’arc', 8),
    ('Tractor pulling', 'tractorpulling', 8),
    ('Trail', 'trail', 8),
    ('Trampoline', 'trampoline', 8),
    ('Traîneaux', 'traineaux', 8),
    ('Triathlon', 'triathlon', 8),
    ('Tricking', 'tricking', 8),
    ('Triple saut', 'triplesaut', 8),
    ('Trottinette', 'trottinette', 8),
    ('Trottinette freestyle', 'trottinettefreestyle', 8),
    ('Tumbling', 'tumbling', 8),
    ('Twirling', 'twirling', 8),
    ('Twirling baton', 'twirlingbaton', 8),
    ('ULM', 'ulm', 8),
    ('Ultimate', 'ultimate', 8),
    ('Ultimate fresbee', 'ultimatefresbee', 8),
    ('Unihockey', 'unihockey', 8),
    ('VTT', 'vtt', 8),
    ('Varappe', 'varappe', 8),
    ('Voile', 'voile', 8),
    ('Volata', 'volata', 8),
    ('Volley-ball', 'volley-ball', 8),
    ('Volleyball', 'volleyball', 8),
    ('Voltige', 'voltige', 8),
    ('Voltige aérienne', 'voltigeaerienne', 8),
    ('Voltige en cercle', 'voltigeencercle', 8),
    ('Vovinam Viet Vo Dao', 'vovinamvietvodao', 8),
    ('Vélo', 'velo', 8),
    ('Vélocross', 'velocross', 8),
    ('Wakeboard', 'wakeboard', 8),
    ('Waterpolo', 'waterpolo', 8),
    ('Watfit', 'watfit', 8),
    ('Waveboard', 'waveboard', 8),
    ('Wing chun', 'wingchun', 8),
    ('Wingsuit', 'wingsuit', 8),
    ('Yoga', 'yoga', 8),
    ('Yoseikan budo', 'yoseikanbudo', 8),
    ('Yukigassen', 'yukigassen', 8),
    ('Zumba', 'zumba', 8),
    ('Échecs', 'echecs', 8),
    ('Équitation', 'equitation', 8)
ON CONFLICT (mot_normalized, categorie_id) DO NOTHING;
