-- Insertion des catégories
INSERT INTO categories (nom) VALUES
  ('Prénom'),
  ('Pays'),
  ('Capitale'),
  ('Animal'),
  ('Métier'),
  ('Fruit ou légume'),
  ('Film')
ON CONFLICT (nom) DO NOTHING;

-- Seed des mots (avec normalisation pour les accents)

-- Prénoms (categorie_id = 1)
INSERT INTO mots (mot, mot_normalized, categorie_id) VALUES
  ('Alice', 'alice', 1),
  ('Antoine', 'antoine', 1),
  ('Amélie', 'amelie', 1),
  ('Arthur', 'arthur', 1),
  ('Benjamin', 'benjamin', 1),
  ('Brigitte', 'brigitte', 1),
  ('Bernard', 'bernard', 1),
  ('Camille', 'camille', 1),
  ('Charles', 'charles', 1),
  ('Chloé', 'chloe', 1),
  ('Claire', 'claire', 1),
  ('David', 'david', 1),
  ('Daniel', 'daniel', 1),
  ('Diane', 'diane', 1),
  ('Emma', 'emma', 1),
  ('Élise', 'elise', 1),
  ('Éric', 'eric', 1),
  ('François', 'francois', 1),
  ('Franck', 'franck', 1),
  ('Florence', 'florence', 1),
  ('Gabriel', 'gabriel', 1),
  ('Gérard', 'gerard', 1),
  ('Guillaume', 'guillaume', 1),
  ('Hugo', 'hugo', 1),
  ('Hélène', 'helene', 1),
  ('Henri', 'henri', 1),
  ('Isabelle', 'isabelle', 1),
  ('Ivan', 'ivan', 1),
  ('Jacques', 'jacques', 1),
  ('Julien', 'julien', 1),
  ('Jean', 'jean', 1),
  ('Julie', 'julie', 1),
  ('Kevin', 'kevin', 1),
  ('Karine', 'karine', 1),
  ('Louis', 'louis', 1),
  ('Léa', 'lea', 1),
  ('Lucas', 'lucas', 1),
  ('Marc', 'marc', 1),
  ('Marie', 'marie', 1),
  ('Martin', 'martin', 1),
  ('Mathieu', 'mathieu', 1),
  ('Nicolas', 'nicolas', 1),
  ('Nathalie', 'nathalie', 1),
  ('Nathan', 'nathan', 1),
  ('Olivier', 'olivier', 1),
  ('Oscar', 'oscar', 1),
  ('Pierre', 'pierre', 1),
  ('Paul', 'paul', 1),
  ('Pascal', 'pascal', 1),
  ('Quentin', 'quentin', 1),
  ('Robert', 'robert', 1),
  ('Raphaël', 'raphael', 1),
  ('Sophie', 'sophie', 1),
  ('Simon', 'simon', 1),
  ('Sarah', 'sarah', 1),
  ('Thomas', 'thomas', 1),
  ('Théo', 'theo', 1),
  ('Tristan', 'tristan', 1),
  ('Valentin', 'valentin', 1),
  ('Victor', 'victor', 1),
  ('Vincent', 'vincent', 1),
  ('William', 'william', 1),
  ('Xavier', 'xavier', 1),
  ('Yves', 'yves', 1),
  ('Yann', 'yann', 1),
  ('Zoé', 'zoe', 1)
ON CONFLICT (mot_normalized, categorie_id) DO NOTHING;

-- Pays (categorie_id = 2)
INSERT INTO mots (mot, mot_normalized, categorie_id) VALUES
  ('Afghanistan', 'afghanistan', 2),
  ('Afrique du Sud', 'afrique du sud', 2),
  ('Albanie', 'albanie', 2),
  ('Algérie', 'algerie', 2),
  ('Allemagne', 'allemagne', 2),
  ('Andorre', 'andorre', 2),
  ('Angola', 'angola', 2),
  ('Argentine', 'argentine', 2),
  ('Arménie', 'armenie', 2),
  ('Australie', 'australie', 2),
  ('Autriche', 'autriche', 2),
  ('Belgique', 'belgique', 2),
  ('Brésil', 'bresil', 2),
  ('Bulgarie', 'bulgarie', 2),
  ('Cambodge', 'cambodge', 2),
  ('Cameroun', 'cameroun', 2),
  ('Canada', 'canada', 2),
  ('Chili', 'chili', 2),
  ('Chine', 'chine', 2),
  ('Chypre', 'chypre', 2),
  ('Colombie', 'colombie', 2),
  ('Croatie', 'croatie', 2),
  ('Cuba', 'cuba', 2),
  ('Danemark', 'danemark', 2),
  ('Égypte', 'egypte', 2),
  ('Équateur', 'equateur', 2),
  ('Espagne', 'espagne', 2),
  ('Estonie', 'estonie', 2),
  ('États-Unis', 'etats-unis', 2),
  ('Éthiopie', 'ethiopie', 2),
  ('Finlande', 'finlande', 2),
  ('France', 'france', 2),
  ('Gabon', 'gabon', 2),
  ('Grèce', 'grece', 2),
  ('Guatemala', 'guatemala', 2),
  ('Haïti', 'haiti', 2),
  ('Hongrie', 'hongrie', 2),
  ('Inde', 'inde', 2),
  ('Indonésie', 'indonesie', 2),
  ('Irak', 'irak', 2),
  ('Iran', 'iran', 2),
  ('Irlande', 'irlande', 2),
  ('Islande', 'islande', 2),
  ('Israël', 'israel', 2),
  ('Italie', 'italie', 2),
  ('Japon', 'japon', 2),
  ('Jordanie', 'jordanie', 2),
  ('Kazakhstan', 'kazakhstan', 2),
  ('Kenya', 'kenya', 2),
  ('Laos', 'laos', 2),
  ('Liban', 'liban', 2),
  ('Libye', 'libye', 2),
  ('Luxembourg', 'luxembourg', 2),
  ('Madagascar', 'madagascar', 2),
  ('Malaisie', 'malaisie', 2),
  ('Mali', 'mali', 2),
  ('Malte', 'malte', 2),
  ('Maroc', 'maroc', 2),
  ('Mexique', 'mexique', 2),
  ('Monaco', 'monaco', 2),
  ('Mongolie', 'mongolie', 2),
  ('Mozambique', 'mozambique', 2),
  ('Namibie', 'namibie', 2),
  ('Népal', 'nepal', 2),
  ('Niger', 'niger', 2),
  ('Nigéria', 'nigeria', 2),
  ('Norvège', 'norvege', 2),
  ('Oman', 'oman', 2),
  ('Ouganda', 'ouganda', 2),
  ('Pakistan', 'pakistan', 2),
  ('Panama', 'panama', 2),
  ('Paraguay', 'paraguay', 2),
  ('Pérou', 'perou', 2),
  ('Philippines', 'philippines', 2),
  ('Pologne', 'pologne', 2),
  ('Portugal', 'portugal', 2),
  ('Qatar', 'qatar', 2),
  ('Roumanie', 'roumanie', 2),
  ('Russie', 'russie', 2),
  ('Rwanda', 'rwanda', 2),
  ('Sénégal', 'senegal', 2),
  ('Serbie', 'serbie', 2),
  ('Singapour', 'singapour', 2),
  ('Slovaquie', 'slovaquie', 2),
  ('Slovénie', 'slovenie', 2),
  ('Somalie', 'somalie', 2),
  ('Soudan', 'soudan', 2),
  ('Suède', 'suede', 2),
  ('Suisse', 'suisse', 2),
  ('Syrie', 'syrie', 2),
  ('Taïwan', 'taiwan', 2),
  ('Tanzanie', 'tanzanie', 2),
  ('Tchad', 'tchad', 2),
  ('Thaïlande', 'thailande', 2),
  ('Togo', 'togo', 2),
  ('Tunisie', 'tunisie', 2),
  ('Turquie', 'turquie', 2),
  ('Ukraine', 'ukraine', 2),
  ('Uruguay', 'uruguay', 2),
  ('Venezuela', 'venezuela', 2),
  ('Vietnam', 'vietnam', 2),
  ('Yémen', 'yemen', 2),
  ('Zambie', 'zambie', 2),
  ('Zimbabwe', 'zimbabwe', 2)
ON CONFLICT (mot_normalized, categorie_id) DO NOTHING;

-- Capitales (categorie_id = 3)
INSERT INTO mots (mot, mot_normalized, categorie_id) VALUES
  ('Abou Dabi', 'abou dabi', 3),
  ('Accra', 'accra', 3),
  ('Addis-Abeba', 'addis-abeba', 3),
  ('Alger', 'alger', 3),
  ('Amsterdam', 'amsterdam', 3),
  ('Ankara', 'ankara', 3),
  ('Athènes', 'athenes', 3),
  ('Bagdad', 'bagdad', 3),
  ('Bakou', 'bakou', 3),
  ('Bangkok', 'bangkok', 3),
  ('Beyrouth', 'beyrouth', 3),
  ('Bissau', 'bissau', 3),
  ('Bogota', 'bogota', 3),
  ('Brasilia', 'brasilia', 3),
  ('Bruxelles', 'bruxelles', 3),
  ('Bucarest', 'bucarest', 3),
  ('Budapest', 'budapest', 3),
  ('Buenos Aires', 'buenos aires', 3),
  ('Canberra', 'canberra', 3),
  ('Caracas', 'caracas', 3),
  ('Copenhague', 'copenhague', 3),
  ('Dacca', 'dacca', 3),
  ('Dakar', 'dakar', 3),
  ('Damas', 'damas', 3),
  ('Delhi', 'delhi', 3),
  ('Doha', 'doha', 3),
  ('Dublin', 'dublin', 3),
  ('Erevan', 'erevan', 3),
  ('Helsinki', 'helsinki', 3),
  ('Islamabad', 'islamabad', 3),
  ('Jakarta', 'jakarta', 3),
  ('Jérusalem', 'jerusalem', 3),
  ('Kaboul', 'kaboul', 3),
  ('Kampala', 'kampala', 3),
  ('Katmandou', 'katmandou', 3),
  ('Kiev', 'kiev', 3),
  ('Kigali', 'kigali', 3),
  ('La Havane', 'la havane', 3),
  ('La Paz', 'la paz', 3),
  ('Le Caire', 'le caire', 3),
  ('Lima', 'lima', 3),
  ('Lisbonne', 'lisbonne', 3),
  ('Londres', 'londres', 3),
  ('Luanda', 'luanda', 3),
  ('Luxembourg', 'luxembourg', 3),
  ('Madrid', 'madrid', 3),
  ('Manille', 'manille', 3),
  ('Mexico', 'mexico', 3),
  ('Minsk', 'minsk', 3),
  ('Mogadiscio', 'mogadiscio', 3),
  ('Monaco', 'monaco', 3),
  ('Moscou', 'moscou', 3),
  ('Nairobi', 'nairobi', 3),
  ('Oslo', 'oslo', 3),
  ('Ottawa', 'ottawa', 3),
  ('Ouagadougou', 'ouagadougou', 3),
  ('Paris', 'paris', 3),
  ('Pékin', 'pekin', 3),
  ('Phnom Penh', 'phnom penh', 3),
  ('Prague', 'prague', 3),
  ('Pretoria', 'pretoria', 3),
  ('Quito', 'quito', 3),
  ('Rabat', 'rabat', 3),
  ('Reykjavik', 'reykjavik', 3),
  ('Riga', 'riga', 3),
  ('Riyad', 'riyad', 3),
  ('Rome', 'rome', 3),
  ('Sanaa', 'sanaa', 3),
  ('Santiago', 'santiago', 3),
  ('Séoul', 'seoul', 3),
  ('Sofia', 'sofia', 3),
  ('Stockholm', 'stockholm', 3),
  ('Tallinn', 'tallinn', 3),
  ('Tbilissi', 'tbilissi', 3),
  ('Téhéran', 'teheran', 3),
  ('Tel Aviv', 'tel aviv', 3),
  ('Tirana', 'tirana', 3),
  ('Tokyo', 'tokyo', 3),
  ('Tripoli', 'tripoli', 3),
  ('Tunis', 'tunis', 3),
  ('Varsovie', 'varsovie', 3),
  ('Vienne', 'vienne', 3),
  ('Washington', 'washington', 3),
  ('Wellington', 'wellington', 3),
  ('Zagreb', 'zagreb', 3)
ON CONFLICT (mot_normalized, categorie_id) DO NOTHING;

-- Animaux (categorie_id = 4)
INSERT INTO mots (mot, mot_normalized, categorie_id) VALUES
  ('Aigle', 'aigle', 4),
  ('Albatros', 'albatros', 4),
  ('Alligator', 'alligator', 4),
  ('Alpaga', 'alpaga', 4),
  ('Âne', 'ane', 4),
  ('Antilope', 'antilope', 4),
  ('Araignée', 'araignee', 4),
  ('Autruche', 'autruche', 4),
  ('Baleine', 'baleine', 4),
  ('Bélier', 'belier', 4),
  ('Bison', 'bison', 4),
  ('Bœuf', 'boeuf', 4),
  ('Buffle', 'buffle', 4),
  ('Cafard', 'cafard', 4),
  ('Caméléon', 'cameleon', 4),
  ('Canard', 'canard', 4),
  ('Castor', 'castor', 4),
  ('Cerf', 'cerf', 4),
  ('Chameau', 'chameau', 4),
  ('Chat', 'chat', 4),
  ('Chauve-souris', 'chauve-souris', 4),
  ('Cheval', 'cheval', 4),
  ('Chèvre', 'chevre', 4),
  ('Chien', 'chien', 4),
  ('Chimpanzé', 'chimpanze', 4),
  ('Cobra', 'cobra', 4),
  ('Cochon', 'cochon', 4),
  ('Colombe', 'colombe', 4),
  ('Coq', 'coq', 4),
  ('Corbeau', 'corbeau', 4),
  ('Coyote', 'coyote', 4),
  ('Crabe', 'crabe', 4),
  ('Crapaud', 'crapaud', 4),
  ('Crocodile', 'crocodile', 4),
  ('Dauphin', 'dauphin', 4),
  ('Dinde', 'dinde', 4),
  ('Dinosaure', 'dinosaure', 4),
  ('Dromadaire', 'dromadaire', 4),
  ('Écureuil', 'ecureuil', 4),
  ('Éléphant', 'elephant', 4),
  ('Escargot', 'escargot', 4),
  ('Faisan', 'faisan', 4),
  ('Faucon', 'faucon', 4),
  ('Flamant rose', 'flamant rose', 4),
  ('Fourmi', 'fourmi', 4),
  ('Gazelle', 'gazelle', 4),
  ('Girafe', 'girafe', 4),
  ('Gorille', 'gorille', 4),
  ('Grenouille', 'grenouille', 4),
  ('Guépard', 'guepard', 4),
  ('Hamster', 'hamster', 4),
  ('Hérisson', 'herisson', 4),
  ('Hibou', 'hibou', 4),
  ('Hippopotame', 'hippopotame', 4),
  ('Hirondelle', 'hirondelle', 4),
  ('Hyène', 'hyene', 4),
  ('Iguane', 'iguane', 4),
  ('Jaguar', 'jaguar', 4),
  ('Kangourou', 'kangourou', 4),
  ('Koala', 'koala', 4),
  ('Lapin', 'lapin', 4),
  ('Léopard', 'leopard', 4),
  ('Lézard', 'lezard', 4),
  ('Libellule', 'libellule', 4),
  ('Lièvre', 'lievre', 4),
  ('Lion', 'lion', 4),
  ('Loup', 'loup', 4),
  ('Loutre', 'loutre', 4),
  ('Lynx', 'lynx', 4),
  ('Manchot', 'manchot', 4),
  ('Marmotte', 'marmotte', 4),
  ('Méduse', 'meduse', 4),
  ('Mouche', 'mouche', 4),
  ('Mouton', 'mouton', 4),
  ('Moustique', 'moustique', 4),
  ('Oie', 'oie', 4),
  ('Oiseau', 'oiseau', 4),
  ('Ours', 'ours', 4),
  ('Paon', 'paon', 4),
  ('Papillon', 'papillon', 4),
  ('Perroquet', 'perroquet', 4),
  ('Phoque', 'phoque', 4),
  ('Pie', 'pie', 4),
  ('Pigeon', 'pigeon', 4),
  ('Poisson', 'poisson', 4),
  ('Porc', 'porc', 4),
  ('Poule', 'poule', 4),
  ('Poulpe', 'poulpe', 4),
  ('Puma', 'puma', 4),
  ('Rat', 'rat', 4),
  ('Raton laveur', 'raton laveur', 4),
  ('Renard', 'renard', 4),
  ('Requin', 'requin', 4),
  ('Rhinocéros', 'rhinoceros', 4),
  ('Sanglier', 'sanglier', 4),
  ('Sauterelle', 'sauterelle', 4),
  ('Scorpion', 'scorpion', 4),
  ('Serpent', 'serpent', 4),
  ('Singe', 'singe', 4),
  ('Souris', 'souris', 4),
  ('Taupe', 'taupe', 4),
  ('Taureau', 'taureau', 4),
  ('Tigre', 'tigre', 4),
  ('Tortue', 'tortue', 4),
  ('Vache', 'vache', 4),
  ('Vautour', 'vautour', 4),
  ('Vipère', 'vipere', 4),
  ('Wapiti', 'wapiti', 4),
  ('Yak', 'yak', 4),
  ('Zèbre', 'zebre', 4)
ON CONFLICT (mot_normalized, categorie_id) DO NOTHING;

-- Métiers (categorie_id = 5)
INSERT INTO mots (mot, mot_normalized, categorie_id) VALUES
  ('Acteur', 'acteur', 5),
  ('Agriculteur', 'agriculteur', 5),
  ('Architecte', 'architecte', 5),
  ('Artiste', 'artiste', 5),
  ('Astronaute', 'astronaute', 5),
  ('Avocat', 'avocat', 5),
  ('Boulanger', 'boulanger', 5),
  ('Boucher', 'boucher', 5),
  ('Caissier', 'caissier', 5),
  ('Chanteur', 'chanteur', 5),
  ('Charpentier', 'charpentier', 5),
  ('Chauffeur', 'chauffeur', 5),
  ('Chef', 'chef', 5),
  ('Chirurgien', 'chirurgien', 5),
  ('Coiffeur', 'coiffeur', 5),
  ('Comptable', 'comptable', 5),
  ('Cuisinier', 'cuisinier', 5),
  ('Danseur', 'danseur', 5),
  ('Décorateur', 'decorateur', 5),
  ('Dentiste', 'dentiste', 5),
  ('Designer', 'designer', 5),
  ('Développeur', 'developpeur', 5),
  ('Directeur', 'directeur', 5),
  ('Ébéniste', 'ebeniste', 5),
  ('Électricien', 'electricien', 5),
  ('Entrepreneur', 'entrepreneur', 5),
  ('Facteur', 'facteur', 5),
  ('Fermier', 'fermier', 5),
  ('Fleuriste', 'fleuriste', 5),
  ('Garagiste', 'garagiste', 5),
  ('Gardien', 'gardien', 5),
  ('Gérant', 'gerant', 5),
  ('Graphiste', 'graphiste', 5),
  ('Guide', 'guide', 5),
  ('Huissier', 'huissier', 5),
  ('Infirmier', 'infirmier', 5),
  ('Informaticien', 'informaticien', 5),
  ('Ingénieur', 'ingenieur', 5),
  ('Jardinier', 'jardinier', 5),
  ('Journaliste', 'journaliste', 5),
  ('Juge', 'juge', 5),
  ('Kinésithérapeute', 'kinesitherapeute', 5),
  ('Libraire', 'libraire', 5),
  ('Maçon', 'macon', 5),
  ('Magasinier', 'magasinier', 5),
  ('Manager', 'manager', 5),
  ('Mannequin', 'mannequin', 5),
  ('Mécanicien', 'mecanicien', 5),
  ('Médecin', 'medecin', 5),
  ('Menuisier', 'menuisier', 5),
  ('Militaire', 'militaire', 5),
  ('Musicien', 'musicien', 5),
  ('Notaire', 'notaire', 5),
  ('Opticien', 'opticien', 5),
  ('Ouvrier', 'ouvrier', 5),
  ('Pâtissier', 'patissier', 5),
  ('Peintre', 'peintre', 5),
  ('Pharmacien', 'pharmacien', 5),
  ('Photographe', 'photographe', 5),
  ('Pilote', 'pilote', 5),
  ('Plombier', 'plombier', 5),
  ('Policier', 'policier', 5),
  ('Pompier', 'pompier', 5),
  ('Professeur', 'professeur', 5),
  ('Psychologue', 'psychologue', 5),
  ('Réalisateur', 'realisateur', 5),
  ('Réceptionniste', 'receptionniste', 5),
  ('Sage-femme', 'sage-femme', 5),
  ('Scientifique', 'scientifique', 5),
  ('Sculpteur', 'sculpteur', 5),
  ('Secrétaire', 'secretaire', 5),
  ('Serveur', 'serveur', 5),
  ('Sociologue', 'sociologue', 5),
  ('Styliste', 'styliste', 5),
  ('Technicien', 'technicien', 5),
  ('Traducteur', 'traducteur', 5),
  ('Usineur', 'usineur', 5),
  ('Vendeur', 'vendeur', 5),
  ('Vétérinaire', 'veterinaire', 5),
  ('Viticulteur', 'viticulteur', 5),
  ('Webdesigner', 'webdesigner', 5),
  ('Zoologue', 'zoologue', 5)
ON CONFLICT (mot_normalized, categorie_id) DO NOTHING;

-- Fruits ou légumes (categorie_id = 6)
INSERT INTO mots (mot, mot_normalized, categorie_id) VALUES
  ('Abricot', 'abricot', 6),
  ('Ail', 'ail', 6),
  ('Ananas', 'ananas', 6),
  ('Artichaut', 'artichaut', 6),
  ('Asperge', 'asperge', 6),
  ('Aubergine', 'aubergine', 6),
  ('Avocat', 'avocat', 6),
  ('Banane', 'banane', 6),
  ('Betterave', 'betterave', 6),
  ('Brocoli', 'brocoli', 6),
  ('Carotte', 'carotte', 6),
  ('Cassis', 'cassis', 6),
  ('Céleri', 'celeri', 6),
  ('Cerise', 'cerise', 6),
  ('Champignon', 'champignon', 6),
  ('Chou', 'chou', 6),
  ('Chou-fleur', 'chou-fleur', 6),
  ('Citron', 'citron', 6),
  ('Citrouille', 'citrouille', 6),
  ('Clémentine', 'clementine', 6),
  ('Concombre', 'concombre', 6),
  ('Coing', 'coing', 6),
  ('Courge', 'courge', 6),
  ('Courgette', 'courgette', 6),
  ('Datte', 'datte', 6),
  ('Endive', 'endive', 6),
  ('Épinard', 'epinard', 6),
  ('Fenouil', 'fenouil', 6),
  ('Figue', 'figue', 6),
  ('Fraise', 'fraise', 6),
  ('Framboise', 'framboise', 6),
  ('Fruit de la passion', 'fruit de la passion', 6),
  ('Gingembre', 'gingembre', 6),
  ('Goyave', 'goyave', 6),
  ('Grenade', 'grenade', 6),
  ('Groseille', 'groseille', 6),
  ('Haricot', 'haricot', 6),
  ('Kaki', 'kaki', 6),
  ('Kiwi', 'kiwi', 6),
  ('Laitue', 'laitue', 6),
  ('Lentille', 'lentille', 6),
  ('Litchi', 'litchi', 6),
  ('Mandarine', 'mandarine', 6),
  ('Mangue', 'mangue', 6),
  ('Melon', 'melon', 6),
  ('Menthe', 'menthe', 6),
  ('Mirabelle', 'mirabelle', 6),
  ('Mûre', 'mure', 6),
  ('Myrtille', 'myrtille', 6),
  ('Navet', 'navet', 6),
  ('Noisette', 'noisette', 6),
  ('Noix', 'noix', 6),
  ('Oignon', 'oignon', 6),
  ('Olive', 'olive', 6),
  ('Orange', 'orange', 6),
  ('Pamplemousse', 'pamplemousse', 6),
  ('Papaye', 'papaye', 6),
  ('Pastèque', 'pasteque', 6),
  ('Patate', 'patate', 6),
  ('Pêche', 'peche', 6),
  ('Persil', 'persil', 6),
  ('Petits pois', 'petits pois', 6),
  ('Piment', 'piment', 6),
  ('Poireau', 'poireau', 6),
  ('Poire', 'poire', 6),
  ('Poivron', 'poivron', 6),
  ('Pomme', 'pomme', 6),
  ('Pomme de terre', 'pomme de terre', 6),
  ('Potiron', 'potiron', 6),
  ('Prune', 'prune', 6),
  ('Pruneau', 'pruneau', 6),
  ('Radis', 'radis', 6),
  ('Raisin', 'raisin', 6),
  ('Rhubarbe', 'rhubarbe', 6),
  ('Roquette', 'roquette', 6),
  ('Salade', 'salade', 6),
  ('Tomate', 'tomate', 6),
  ('Topinambour', 'topinambour', 6),
  ('Vanille', 'vanille', 6),
  ('Wasabi', 'wasabi', 6)
ON CONFLICT (mot_normalized, categorie_id) DO NOTHING;

-- Films (categorie_id = 7)
INSERT INTO mots (mot, mot_normalized, categorie_id) VALUES
  ('Alien', 'alien', 7),
  ('Amélie Poulain', 'amelie poulain', 7),
  ('Armageddon', 'armageddon', 7),
  ('Avatar', 'avatar', 7),
  ('Avengers', 'avengers', 7),
  ('Bambi', 'bambi', 7),
  ('Batman', 'batman', 7),
  ('Bienvenue chez les Chtis', 'bienvenue chez les chtis', 7),
  ('Blanche-Neige', 'blanche-neige', 7),
  ('Braveheart', 'braveheart', 7),
  ('Casablanca', 'casablanca', 7),
  ('Cars', 'cars', 7),
  ('Cendrillon', 'cendrillon', 7),
  ('Coco', 'coco', 7),
  ('Dune', 'dune', 7),
  ('Encanto', 'encanto', 7),
  ('ET', 'et', 7),
  ('Forrest Gump', 'forrest gump', 7),
  ('Frozen', 'frozen', 7),
  ('Gladiator', 'gladiator', 7),
  ('Grease', 'grease', 7),
  ('Gravity', 'gravity', 7),
  ('Harry Potter', 'harry potter', 7),
  ('Inception', 'inception', 7),
  ('Indiana Jones', 'indiana jones', 7),
  ('Interstellar', 'interstellar', 7),
  ('Intouchables', 'intouchables', 7),
  ('Jaws', 'jaws', 7),
  ('Joker', 'joker', 7),
  ('Jumanji', 'jumanji', 7),
  ('Jurassic Park', 'jurassic park', 7),
  ('King Kong', 'king kong', 7),
  ('La La Land', 'la la land', 7),
  ('Le Roi Lion', 'le roi lion', 7),
  ('Le Seigneur des Anneaux', 'le seigneur des anneaux', 7),
  ('Les Bronzés', 'les bronzes', 7),
  ('Les Visiteurs', 'les visiteurs', 7),
  ('Madagascar', 'madagascar', 7),
  ('Matrix', 'matrix', 7),
  ('Minions', 'minions', 7),
  ('Moana', 'moana', 7),
  ('Mulan', 'mulan', 7),
  ('Nemo', 'nemo', 7),
  ('Oppenheimer', 'oppenheimer', 7),
  ('Parasite', 'parasite', 7),
  ('Pinocchio', 'pinocchio', 7),
  ('Pocahontas', 'pocahontas', 7),
  ('Psycho', 'psycho', 7),
  ('Pulp Fiction', 'pulp fiction', 7),
  ('Ratatouille', 'ratatouille', 7),
  ('Rocky', 'rocky', 7),
  ('Scarface', 'scarface', 7),
  ('Shining', 'shining', 7),
  ('Shrek', 'shrek', 7),
  ('Spider-Man', 'spider-man', 7),
  ('Star Wars', 'star wars', 7),
  ('Superman', 'superman', 7),
  ('Tenet', 'tenet', 7),
  ('Terminator', 'terminator', 7),
  ('The Godfather', 'the godfather', 7),
  ('The Truman Show', 'the truman show', 7),
  ('Titanic', 'titanic', 7),
  ('Toy Story', 'toy story', 7),
  ('Transformers', 'transformers', 7),
  ('Up', 'up', 7),
  ('Vice-versa', 'vice-versa', 7),
  ('Wall-E', 'wall-e', 7),
  ('Wonder Woman', 'wonder woman', 7),
  ('X-Men', 'x-men', 7),
  ('Zootopie', 'zootopie', 7)
ON CONFLICT (mot_normalized, categorie_id) DO NOTHING;